### ISSUE TITLE
Is there an Overview of uncovered Code?

### ISSUE THREAD

**Issue by Mr-Pearce** [FortuneN/FineCodeCoverage#1]
Probably not really an "issue" but a feature request.
But is there a way to visualize the uncovered Code in some Tree view that shows your solution, Classes, methods that are not covered?

I have a by now bigger project with some tests. Your (fine) tool showed me that a some stuff is uncovered (what i have to cover now)
and it would be nice to have a overview instead of just highlighted code lines per open file.

Also it would be useful to "ignore" or "it *IS* covered" some of these methods.
For example i have a database with a lot of tables with a lot of properties (146 tables atm) and all of the Property getters are highlighted because most of them never will be explicitly used.

I checked out your code but i have absolutely no knowledge of vs extension and just dumped all the lines in the log to see an overview but a real ui with some clickable nodes that lead to the corresponding method in your files would be reaaaaaally nice!

**Comment by FortuneN** [comment]
I like this as a feature. Can't give timelines but i assure you; it is coming.

**Comment by FortuneN** [comment]
Please review the latest version

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
