### ISSUE TITLE
Coverlet timed out (.net core 3.1 project)

### ISSUE THREAD

**Issue by Arcturuss** [FortuneN/FineCodeCoverage#10]
### Installed product versions
- Visual Studio: 2019 community 16.7.6
- This extension: 1.0.89
- Windows 10 x64

### Description
Coverlet.console seems to hang when started by extension, but works fine when I run it manually with same parameters (both global executable and local in AppData/Local/FineCodeCoverage/coverlet/). It creates `_outputfolder/diagnostics.log`, but no `_cover.tool.xml`.

Probably it's an issue in coverlet itself, but still.

### Steps to recreate
1. run test project (netcoreapp3.1) with some passing and some failing tests

I've managed to reproduce same behavior running coverlet from simple .netcore console app with parameters like this:
    
    var processStartInfo = new ProcessStartInfo
        {
            CreateNoWindow = true,
            UseShellExecute = false,
            RedirectStandardError = true,
            RedirectStandardOutput = true,
            ...
        };

but it works fine, when running in separate window with no stream redirection:

    var processStartInfo = new ProcessStartInfo
        {
            CreateNoWindow = false,
            UseShellExecute = false,
            RedirectStandardError = false,
            RedirectStandardOutput = false,
            ...
        };

When I made these changes in extension itself, it started working, but with visible console window for coverlet obviously :)

**Comment by stefan-ziel** [comment]
Same for me. VS "Output" window says:
```
Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Ensure Work Folder Exists (Project.Data.Services.Tests)

Fine Code Coverage : Synchronize Output Files To Work Folder (Project.Data.Services.Tests)

Fine Code Coverage : Run Coverage Tool (Project.Data.Services.Tests)

Fine Code Coverage : Coverlet Run (Project.Data.Services.Tests) Arguments 
"C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\Project.Data.Services.Tests.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--include-test-assembly
--target "dotnet"
--output "C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\_outputfolder\_cover.tool.xml"
--targetargs "test  ""C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\Project.Data.Services.Tests.dll"" --nologo --blame --results-directory ""C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\_outputfolder"" --diag ""C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\_outputfolder/diagnostics.log""  "

Fine Code Coverage : Run Coverage Tool (Project.Data.Services.Tests) Failed
System.Exception: Coverlet timed out after 119,9852219 seconds (CoverToolTimeout is 120 seconds)
   at FineCodeCoverage.Engine.Coverlet.CoverletUtil.RunCoverlet(CoverageProject project, Boolean throwError) in C:\projects\finecodecoverage\FineCodeCoverage\Core\Coverlet\CoverletUtil.cs:line 237
   at FineCodeCoverage.Engine.FCCEngine.<>c.<ReloadCoverage>b__23_16(CoverageProject project) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 364
   at FineCodeCoverage.Engine.Model.CoverageProject.Step(String stepName, Action`1 action) in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 36

Fine Code Coverage : ================================== DONE ===================================
```
Running the command by hand 
```
C:\Users\me\AppData\Local\FineCodeCoverage\coverlet\coverlet "C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\Project.Data.Services.Tests.dll" --format "cobertura" --exclude-by-file "**/Migrations/*" --exclude-by-attribute "GeneratedCode" --include-test-assembly --target "dotnet" --output "C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\_outputfolder\_cover.tool.xml" --targetargs "test  ""C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\Project.Data.Services.Tests.dll"" --nologo --blame --results-directory ""C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\_outputfolder"" --diag ""C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\_outputfolder/diagnostics.log""  "

Logging Vstest Diagnostics in file: C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\_outputfolder\diagnostics.log
A total of 1 test files matched the specified pattern.
Test Run Successful.
Total tests: 22
     Passed: 22
 Total time: 4,9276 Seconds

Calculating coverage result...
  Generating report 'C:\Users\me\AppData\Local\FineCodeCoverage\8BABC81EEF116DE78FF07290442D34BF\_outputfolder\_cover.tool.xml'
+------------------------------------------+--------+--------+--------+
| Module                                   | Line   | Branch | Method |
+------------------------------------------+--------+--------+--------+
| Project.Core                             | 7,82%  | 9,17%  | 12,52% |
+------------------------------------------+--------+--------+--------+

+---------+--------+--------+--------+
|         | Line   | Branch | Method |
+---------+--------+--------+--------+
| Total   | 7,42%  | 5,12%  | 3,88%  |
+---------+--------+--------+--------+
| Average | 15,36% | 18,44% | 14,95% |
+---------+--------+--------+--------+
```

**Comment by ninjelli** [comment]
I also have this issue, even after updating my csproj file with the following:

`<PropertyGroup Label="FineCodeCoverage">
    <CoverToolTimeout>
      4000
    </CoverToolTimeout>
  </PropertyGroup>`

**Comment by FortuneN** [comment]
@ninjelli 

(1) Your previous edit 

> I also have this issue, even after updating my csproj file with the following:
> 
> <PropertyGroup Label="FineCodeCoverage"> <CoverToolTimeout> 4000 </CoverToolTimeout> </PropertyGroup>

Do you make that change on the Test project? (as opposed to to the Project being tested)
I ask because if changing the Global options works, then project local settings should work as well -> BUT only if applied on the Test project

(2) Is it common for this extension to run for so long though?

It quickly BUT does take longer for solutions that have projects to be processed.
Which step(s) take longer run?

**Comment by FortuneN** [comment]
@Arcturuss @stefan-ziel 

From a question in the FAQ:

A timeout exception is thrown if tests run for "too long".

Why?

There are scenarios under which the cover tool (OpenCover or Coverlet) may fail and FCC does not get a signal to proceed.
The timeout is there so you don't wait forever.

What can i do?

By default the 'CoverToolTimeout' is 160 seconds.
There is nothing special about 160 and you can change it if you want to give your tests more time to run without timing out.

How can i change CoverToolTimeout?

Approach (1)
Navigate to "Tools > Options > Fine Code Coverage > CoverToolTimeout".
The number is in seconds and you can set it as high as you want.
Options/settings in the "Options" dialog apply to ALL projects

Approach (2)
Create an xml tag in your project file (csproj/vbproj)
<PropertyGroup Label="FineCodeCoverage">
<CoverToolTimeout>
160
</CoverToolTimeout>
</PropertyGroup>
Again, the number is in seconds and you can set it as high as you want.
Options/settings in the project file apply to that specific project

**Comment by Arcturuss** [comment]
> I put that in place as a circuit breaker to avoid endless waits when the cover (coverlet/opencover) tool 'hangs'

That is the case for me. Increasing timeout to 240s didn't help, and my tests run for max 15s when started manually from console.

> The other thing is that for a solution, i run the cover tool (coverlet/opencover) in parallel for mutiple projects in a solution [I will evaluate if running in series makes a difference]

Probably it won't, because all issues I've experienced were with single test project and single instance of coverlet running.

I've explained in first message, what I've done to make extension work. The issue is not with timeout itself, but with coverlet behaving odd when started with specific parameters (windowless and with standard output/error streams redirect).

**Comment by FortuneN** [comment]
@Arcturuss 

> I've explained in first message, what I've done to make extension work.
> ... behaving odd when started with specific parameters (windowless and with standard output/error streams redirect)

I understand there.
Unfortunately we can't run with the open console window.
I will continue to investigate what else could be done to get the desired behavior 'windolessly' :)

**Comment by stefan-ziel** [comment]
@FortuneN there must be another problem beside long running tests, as in my example above the command line execution terminates within seconds ...

**Comment by FortuneN** [comment]
@stefan-ziel 

Perhaps. Is the process failing everytime? Does it ever succeed say with another project?

**Comment by ninjelli** [comment]
(1) Yes, I added the XML to the test project

(2) Fine Code Coverage : OpenCover Run (Test) Arguments. I have not gotten this step to run successfully yet.

**Comment by stefan-ziel** [comment]
@FortuneN some rare times it succeeds. but I´m unable to discover any pattern. The rest of the time coverlet is been called but does not run at all (0% CPU)
![image](https://user-images.githubusercontent.com/21267169/96926113-8a67cc00-148b-11eb-9169-2c243f7f04b2.png)

**Comment by stefan-ziel** [comment]
More precisely... the first time after a windows restart it works. After that it fails even restarting VS. Other related message
´´´
Fine Code Coverage : Synchronize Output Files To Work Folder (LINCROS-Routing.Algoritmo.Tests)

Fine Code Coverage : Synchronize Output Files To Work Folder (LINCROS-Routing.Algoritmo.Tests) Failed
System.IO.IOException: The process cannot access the file 'C:\Users\LINCROS\AppData\Local\FineCodeCoverage\963C7EB527242D151AC702BB13F69440\project.Core.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at FineCodeCoverage.Engine.FileSynchronization.FileSynchronizationUtil.Synchronize(String sourceFolder, String destinationFolder) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FileSynchronization\FileSynchronizationUtil.cs:line 21
   at FineCodeCoverage.Engine.FCCEngine.<>c.<ReloadCoverage>b__23_16(CoverageProject project) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 427
   at FineCodeCoverage.Engine.Model.CoverageProject.Step(String stepName, Action`1 action) in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 36
´´´

**Comment by FortuneN** [comment]
If you can, please provide a simple repro that i can test against.
One from each of you please

**Comment by FortuneN** [comment]
Please guys; I think i have a fix but i need some repros to test. Please

**Comment by stefan-ziel** [comment]
@FortuneN  sorry ... I am in the same mess with my product ... at the moment no time left ...

**Comment by Arcturuss** [comment]
@FortuneN well, now I cannot reproduce this bug. Seems like it comes ang goes. I will make minimal repro when it appears again.

**Comment by FortuneN** [comment]
Please try the latest version and let me know how it goes

**Comment by FortuneN** [comment]
Is the issue resolved; Can i close?

**Comment by FortuneN** [comment]
Please post a review 

https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
