### ISSUE TITLE
Works only when all tests are passing

### ISSUE THREAD

**Issue by Arcturuss** [FortuneN/FineCodeCoverage#11]
### Installed product versions
- Visual Studio: 2019 community 16.7.6
- This extension: 1.0.89
- Windows 10 x64

### Description
Extension throws an error and doesn't show anything when there are failing tests in project

### Steps to recreate
1. run tests on project with some tests failing

### Current behavior
Extension throws an error when coverlet exits with exit code other than 0

### Expected behavior
Should work with coverlet exit codes 1 and 2 too 
https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.console/ExitCodes.cs

**Comment by FortuneN** [comment]
Thank you very very very much @Arcturuss.
Please check the latest version.

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
