### ISSUE TITLE
Error processing unit test events

### ISSUE THREAD

**Issue by pschnabel** [FortuneN/FineCodeCoverage#113]
- Visual Studio: [2019 Professional]
- This extension: [1.1.131]

After the test runs ther is an exception in FFC log.

![image](https://user-images.githubusercontent.com/29749427/110956998-814c9e00-834b-11eb-9171-cd78d3db7934.png)

**Comment by tonyhallett** [comment]
What version of Microsoft.NET.Test.Sdk do you have installed ?
```<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />```
What test runner are you using and how is it specified ?

**Comment by tonyhallett** [comment]
Also what version of visual studio ?

**Comment by tonyhallett** [comment]
Do this [vsix](https://ci.appveyor.com/api/buildjobs/ivju00ipee91owrx/artifacts/FineCodeCoverage.vsix) resolve the issue ?

**Comment by pschnabel** [comment]
@tonyhallett  thank you for your replay

> What version of Microsoft.NET.Test.Sdk do you have installed ?
> `<PackageReference Include="Microsoft.NET.Test.Sdk" Version="..." />`
> What test runner are you using and how is it specified ?


  <ItemGroup>
    <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.13.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
  </ItemGroup>



> Also what version of visual studio ?

![image](https://user-images.githubusercontent.com/29749427/111266880-7172d980-862b-11eb-9929-1534e5db0d8d.png)

> Do this [vsix](https://ci.appveyor.com/api/buildjobs/ivju00ipee91owrx/artifacts/FineCodeCoverage.vsix) resolve the issue ?

No, still get the same output

**Comment by tonyhallett** [comment]
Can you update your nuget references and try again

**Comment by pschnabel** [comment]
> Can you update your nuget references and try again

`  <PackageReference Include="nunit" Version="3.13.1" />`  
`  <PackageReference Include="NUnit3TestAdapter" Version="4.0.0-beta.1" />`  
`  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0-preview-20210219-03" />`  

Still same output

**Comment by tonyhallett** [comment]
Can you post the latest exception, there should be a difference from your first exception.

**Comment by pschnabel** [comment]
> Can you post the latest exception, there should be a difference from your first exception.
![image](https://user-images.githubusercontent.com/29749427/111288669-ad666880-8644-11eb-81da-425bf7736c54.png)

**Comment by tonyhallett** [comment]
This is obviously not an optimum solution but can you update visual studio to the latest version ?

**Comment by pschnabel** [comment]
@tonyhallett thank you, aufter updating VS, its working

**Comment by tonyhallett** [comment]
@pschnabel Thanks for raising this issue.  At some point in the near future I will update the source to allow for the differences in the internal types between versions that FCC reflects on.

One last thing - does the code run correctly when using the vsix from the marketplace ?

**Comment by pschnabel** [comment]
@tonyhallett after updating VS, the marketpalce works too.
