### ISSUE TITLE
Risk Hotspots tab has no content.

### ISSUE THREAD

**Issue by theomnislayer** [FortuneN/FineCodeCoverage#115]
Installed versions:
Visual Studio 2019 Professional 16.9.2 and Community 16.9.2 (Latest as of March 17, 2021)
Fine Code Coverage 1.1.131

Solution/Project Details: 
2 Projects
1 - .NET Framework 4.8 class library with 2 classes
2 - .NET Framework 4.8 UnitTest Project with 1 class. Using MSTest and MSTest Framewor

Description:
Risk Hotspots tab has no content. Other tabs such as coverage and summary are populated with correct values.

Expected:
Has content similar to below
![image](https://user-images.githubusercontent.com/20275306/111438072-c9e6cb80-873e-11eb-886d-e7bf1fe75faf.png)

Actual:
![image](https://user-images.githubusercontent.com/20275306/111438128-da974180-873e-11eb-865c-13dc1e5594af.png)

What I did to try and resolve the issue:
First, I was using VS 2019 pro. Installed a fresh version of community and opened the same project. Same thing happened.
Updated VS since I was using 16.8.x (I forgot) but problem still persists.
Restarted VS and PC, after clearing cache. Still doesn't work.
I just started using FineCodeCoverage yesterday, I haven't seen the tab populated ever.

Thanks! :D

**Comment by tonyhallett** [comment]
Is your project open source ?

**Comment by tonyhallett** [comment]
How did you get your expected risk hotspots ?

**Comment by tonyhallett** [comment]
Can you post the files project.coverage.xml and Cobertura.xml from YourTestProject/bin/debug/fine-code-coverage/coverage-tool-output
