### ISSUE TITLE
integration with sonarqube

### ISSUE THREAD

**Issue by ChristAguirre** [FortuneN/FineCodeCoverage#119]
HOW CAN I INTEGRATE CODE COVERAGE REPORTS TO SONARQUBE?

**Comment by tonyhallett** [comment]
I wouldn't expect to. Sonarqube is code quality / security. You will have to be more specific with what you want to accomplish.

**Comment by tonyhallett** [comment]
This seems to me a question better suited for StackOverflow assuming that you can rephrase as suggested and prove your have done some research into answering your own question.

If the question is FCC related and not coverage reports in general then ask here https://github.com/FortuneN/FineCodeCoverage/discussions
