### ISSUE TITLE
Find Code Coverage window always opens when trying to view Test Explorer

### ISSUE THREAD

**Issue by bobted** [FortuneN/FineCodeCoverage#12]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 16.7.6

### Description
After opening the Fine Code Coverage window from the View menu, each time the Test Explorer is opened, the FFC window opens automatically. This may only happen once per session of VS - or once per opened solution.

I had the window docked to the bottom pane and had autohide set. When I noticed the window popping open when opening the Test Explorer, which I have docked to the right side with autohide set, I clicked the X to close the FFC window. It did not reopen after that until VS was closed and reopened. Usually the window state and location is saved when closing VS.

### Steps to recreate
1. From the View -> Other Windows menu, select Fine Code Coverage
2. Dock the window to the bottom panel
3. Click the pin to set the autohide of the window
4. Close and reopen Visual Studio
5. Open a solution with test projects
6. Open Test Explorer -----> the FFC window pops open which forces the Test Explorer window to hide.

### Current behavior
As a user, I want to open the Text Explorer window without it auto hiding due to the FFC window taking control.

### Expected behavior
The FFC window does not automatically open with the Text Explorer window is opened.

**Comment by bobted** [comment]
As I was writing this, I realized I had not attempted this with the FFC window undocked (floating).  Even with the FFC window undocked, it still reopens when trying to open the Test Explorer.

**Comment by FortuneN** [comment]
Is it possible to record your screen while you do this and post the video?

**Comment by bobted** [comment]
Hope this helps.

[FFCreportwindowopeningwithTX.zip](https://github.com/FortuneN/FineCodeCoverage/files/5429037/FFCreportwindowopeningwithTX.zip)

**Comment by FortuneN** [comment]
Thank you for the vid.

I defined the current behavior so that it would be easy to discover the output window without having to “View -> Other Windows menu, select Fine Code Coverage”.
I think this makes the window ‘findable’ by first time users.

If I restrict this behavior to happen only on the first launch after installation; would it be better?

**Comment by bobted** [comment]
I think that would be good. It seems like the reports that show in that window do not uncle net core test projects, so I don’t need the window.

**Comment by FortuneN** [comment]
Please rephrase this bit
> It seems like the reports that show in that window do not uncle net core test projects

**Comment by bobted** [comment]
I edited that last comment to fix the typo, which that comment seems to be wrong anyway. Most of the time, the FFC window is blank so I assumed it didn't work with .NET Core 3.1. I just opened two different solutions that I've worked on over the last year where one has a test project which is `net471` and the other has test projects which are `netcoreapp31`. The `net471` project was on a feature branch and `coverlet` kept timing out after 120s, once I put it back to the `develop` branch it worked. The `netcoreapp31` was already on `develop` and worked right away. So you can ignore the part of the comment about the window not including net core test projects.

So all I'm asking is if the FFC window could be set to not automatically open when opening the Text Explorer window.

**Comment by FortuneN** [comment]
Please try the latest version and let me know how it goes

**Comment by bobted** [comment]
I tried to install 1.0.104 through the extension manager in VS, but it gave me a message that it was already installed. So I uninstalled FFC, closed and reopened VS, then installed it new. After re-installing FFC, I opened the same solution from the video. I opened Solution Explorer, then opened Test Explorer; while Test Explorer was loading, the FFC window opened. Since you mentioned you wanted the window to be "findable" for a first time user, I closed the FFC window, then closed VS. I reopened VS with the same solution and repeated the steps -> open Solution Explorer then open Test Explorer; the FFC window opened again on its own.

**Comment by bobted** [comment]
@FortuneN I just went into the extensions manager in VS and it looks like I still have `1.0.90` installed - VS is telling me that `1.0.104` is available but it will not install it. I just went over to the marketplace website and downloaded the `VSIX` and it is also `1.0.90`.

Do you have a `VSIX` for `1.0.104` that I can try?

**Comment by FortuneN** [comment]
No problem.
Find attached ...

[Fine Code Coverage v1.0.104.zip](https://github.com/FortuneN/FineCodeCoverage/files/5475537/Fine.Code.Coverage.v1.0.104.zip)

**Comment by bobted** [comment]
The installer in that zip appears to work. When I open the solution and then open Test Explorer, the FFC window does _not_ automatically pop open. Thanks for taking care of this.

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo

**Comment by Kareem4006** [comment]
Thank you Sir

**Comment by tonyhallett** [comment]
@Kareem4006 
Is this a general thank you or is it related to this issue ?

**Comment by Kareem4006** [comment]
> @Kareem4006 
> 
> Is this a general thank you or is it related to this issue ?

It is related to the issue.

**Comment by Kareem4006** [comment]
not the answer helped me to slove it
