### ISSUE TITLE
Includes Generated Files

### ISSUE THREAD

**Issue by scubakiz** [FortuneN/FineCodeCoverage#121]
There doesn't seem to be any way to exclude files generated in the obj folder and internal service files generated for gRPC.

![image](https://user-images.githubusercontent.com/6867330/112787577-0c998500-9016-11eb-87e4-157d49bd8366.png)

All the "Reflection" files are auto generated but at stuck in my code coverage.

I tried adding the obj folder to the excluded list, but it doesn't do any good.  Here's my "exclude by file" list:

**/Pages/*
**/Protos/*
**/Results/*
**/obj/*
**/bin/*

**Comment by tonyhallett** [comment]
Please you post the output from the FCC Output Window Pane

**Comment by tonyhallett** [comment]
I don't know if you are using the new SDK format which determines if Coverlet or OpenCover is used for coverage.
If it is Coverlet their example from [here](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#source-files)

```
Source Files
You can also ignore specific source files from code coverage using the ExcludeByFile property

Use single or multiple paths (separate by comma)
Use file path or directory path with globbing (e.g dir1/*.cs)
dotnet test /p:CollectCoverage=true /p:ExcludeByFile=\"**/dir1/class1.cs,**/dir2/*.cs,**/dir3/**/*.cs\"
```

**Comment by tonyhallett** [comment]
@scubakiz 
Did you resolve this problem ?

**Comment by tonyhallett** [comment]
Closing as no response and not obviously an issue with Fine Code Coverage.  Does not appear to have configured correctly
