### ISSUE TITLE
NUnit "Explicit" tests run by default

### ISSUE THREAD

**Issue by neoaisac** [FortuneN/FineCodeCoverage#122]
### Installed product versions
- Visual Studio: 2019 Professional 16.9.2
- This extension: 1.1.141

### Description
When running all tests (using the "All Tests In View" button from "Test Explorer" window) with NUnit, the engine will generally avoid running tests marked with the `ExplicitAttribute` attribute. However, when running this with Fine Code Coverage the tests do run.

Since sometimes these tests require some extra configuration or are meant to run on certain environments, they sometimes are expected to fail in a local development environment, so ideally, Fine Code Coverage should not override the default behavior of the engine and run these tests when they shouldn't.

### Steps to recreate
1. Install Fine Code Coverage in Visual Studio 2019
2. Open the "Test Explorer" window and the "Fine Code Coverage" window
3. Create a NUnit test that fails and mark it as `Explicit`
4. Click on "All Tests In View"

### Current behavior
When all tests are run, you'll notice that the explicit test was run (when it normally should not have) and it is marked as failed.

### Expected behavior
The tests marked as `Explicit` should not be run unless explicitly included.

**Comment by tonyhallett** [comment]
I am getting different behaviour.
Albeit with visual studio 2019 community 16.9.1

> The engine will generally avoid running tests marked with the ExplicitAttribute attribute

Given a .NET Core test project
```
public class Tests
    {
        [Test]
        public void Test1()
        {
            new Class1().Test1();
        }

        [Test, Explicit]
        public void ExplicitTest()
        {
            new Class1().Test2();
        }
    }
``
When I click All Tests In View both tests run.
Above is not important to the discussion though.

Importantly is the code coverage I get from FCC
![image](https://user-images.githubusercontent.com/11292998/113135268-d593c100-9219-11eb-97fb-d4ac6b7bd8dc.png)

Running dotnet test from the command line provides the same coverage.

Is your project an SDK style project ?
What versions do you have of these ?
```
<PackageReference Include="NUnit" Version="3.13.1" />
<PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.1" />
```

Note that fine code coverage does not have access to the tests that have been chosen in the UI and calls dotnet test or vstest.  What FCC does not provide and perhaps should is the facility to specify a [test filter](https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest).
Before adding a `<TestFilter>` element to the proj file and FCC adding to the command argument --filter for sdk style or --testcasefilter for old style, lets determine why Explicit is being run for you.

**Comment by tonyhallett** [comment]
@neoaisac 
Does adding ExplicitAttribute to the ExcludeByAttribute list resolve your problem ?

**Comment by tonyhallett** [comment]
Let's start again.

Whether the Explicit attribute is ignored when clicking all tests in view depends on the version of NUnit3TestAdapter and it is inconsistent when it is ignored, see https://github.com/nunit/nunit3-vs-adapter/issues/658 and https://github.com/nunit/nunit3-vs-adapter/issues/784.

The behaviour you see in visual studio is not the behaviour you get from fine code coverage and the underlying coverage tool.
With a .NET Core project the Explicit attribute is respected and I expect this will be the same behaviour for a .NET Framework project too.

From the images below you can see that 
From the test explorer - visual studio ran the explicit test.
From the gutter and fine code coverage table - the explicit test was not run ( and neither Test2 )

![image](https://user-images.githubusercontent.com/11292998/118355421-dbdec200-b567-11eb-89e4-e0eca7995652.png)
![image](https://user-images.githubusercontent.com/11292998/118355364-8efaeb80-b567-11eb-865a-9c7acf90d5b8.png)
![image](https://user-images.githubusercontent.com/11292998/118355381-9d490780-b567-11eb-83bd-1f715819c814.png)

From FCC Output Window Pane
Fine Code Coverage : Coverlet Run (TestProject1)
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Users\tonyh\Source\Repos\TestExcludeAttribute\TestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\diagnostics.log
A total of 1 test files matched the specified pattern.
  Skipped ExplicitTest [4 ms]
Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 286 ms - TestProject1.dll (netcoreapp3.1)

**Comment by tonyhallett** [comment]
Closing as does not appear to be a Fine Code Coverage issue.
