### ISSUE TITLE
Exceptions Thrown after if statement not being detected as covered

### ISSUE THREAD

**Issue by chaughawout** [FortuneN/FineCodeCoverage#124]
### Installed product versions
- Visual Studio: Community 2019 v16.9.2
- This extension: v1.1.141

### Description
Displaying code is not covered even though it is. This only occurs when a method branches due to exceptions being thrown after an if statement. Seemingly doesn't happen all the time, I have two methods that are very similar and are executed by the same code, both covered by tests, but one shows red, the other green. I have a feeling this is a PEBKAC situation, but not sure.

### Steps to recreate
1. Make a method with an if statement.
2. After body of if statement, `throw new Exception()`
3. Make unit test that asserts method throws the exception.
4. Look at file gutter and notice red on line with `throw new Exception()`

### Current behavior
It's red.

### Expected behavior
It should be green.

### Side Notes
![image](https://user-images.githubusercontent.com/5073778/113955549-8fbe9600-97e1-11eb-8350-9348974373eb.png)
![image](https://user-images.githubusercontent.com/5073778/113955716-e4621100-97e1-11eb-8321-933648911e41.png)
![image](https://user-images.githubusercontent.com/5073778/113955625-ba105380-97e1-11eb-8eae-dacb087c8742.png)

**Comment by tonyhallett** [comment]
First test, no orders - exception in CalcOrderWaitTime, CalcCourierWaitTime not called ( no exception )
Second test - there is an order - no exception in CalcCourierWaitTime
Third test - there is no order - exception in CalcOrderWaitTime, CalcCourierWaitTime not called ( no exception )

The exception line is not hit - the coverage is correct.

Next time debug your tests

**Comment by FortuneN** [comment]
@chaughawout @tonyhallett 

I had to google PEBKAC

 :laughing: :laughing: :laughing:

You are killing me gentlemen
