### ISSUE TITLE
Tasks for Fortune to move to github actions

### ISSUE THREAD

**Issue by tonyhallett** [FortuneN/FineCodeCoverage#125]
@FortuneN 

Two secrets need to be created for the repository
A) VSIX_PUBLISHER - this is the personal access token for the marketplace
B) PAT - [github personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) 
![image](https://user-images.githubusercontent.com/11292998/115116617-6ac0e480-9f92-11eb-9a22-156298882158.png)

C) Add the publish manifest json file and asset files ( e.g overview.md ) to the solution and to github.

Once this has been done I will create a release to match the marketplace version ( as this is used for auto incrementing versions on push ( and pull ) ) and add the workflow files that have been tested on a dummy visual studio extension repository.

Future pull requests will run tests and build the vsix and add a comment containing a link to the vsix ( zip file ) to all linked issues.
When merge ( keep the default commit message e.g Merge pull request #... from ... ) a github release will be created containing the vsix in case there is a need to rollback to a previous version.  The vsix will be published to the marketplace and a comment will be added to all linked issues.

You can link to an issue in the normal manner with a commit message e.g fix #... or by naming the branch e.g fix-issue-123

Versioning can be controlled with commit message.
To bump major version the commit message needs to contain (MAJOR)
To bump minor version the commit message needs to contain (MINOR)
Without (MAJOR) or (MINOR) the patch will be bumped.

The marketplace version will include an automatic build number as well.

**Comment by FortuneN** [comment]
@tonyhallett 

A) FCC_VS_MARKET_PLACE_PUBLISH_TOKEN
B) GITHUB_TOKEN (https://docs.github.com/en/actions/reference/authentication-in-a-workflow)
C) Added 2 files to the repo; vs-market-place-manifest.json and vs-market-place-overview.md. (You may have to remove comments from vs-market-place-manifest.json)

**Comment by tonyhallett** [comment]
B) The token that is supplied in actions is not sufficient for repository dispatch https://octokit.github.io/rest.js/v18
