### ISSUE TITLE
Feature - Add option to show only added and modified files or hide files with 100% coverage

### ISSUE THREAD

**Issue by Khoosham** [FortuneN/FineCodeCoverage#130]
- Visual Studio: [2019 Professional]
- This extension: [example 1.1.141]

### Description
Feature - Add option to show only added and modified files or hide files with 100% coverage

### Side Notes
- Having the control whether to show added or modified files will be great since we don't have to scroll over all the files in the coverage window.
- Or an option to hide files which are already covered at 100% sound more appropriate.

**Comment by tonyhallett** [comment]
Please install the latest version - will hide a row where line coverage is 100% and there are no branches or there is 100% branch coverage.
To use you need turn on the extension option.

( Currently this is performed with a MutationObserver that is added to the html report generated by ReportGenerator.  At a later date we will create our own report and it will not be necessary.)
