### ISSUE TITLE
Only the built-in Dark theme is supported for report

### ISSUE THREAD

**Issue by jonathanpoulin** [FortuneN/FineCodeCoverage#135]
### Installed product versions
- Visual Studio: Community 2019
- This extension: 1.1.141

### Description
Only the built-in Dark theme is supported for report

### Steps to recreate
1. Install the extension [Color Themes for Visual Studio](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.ColorThemesforVisualStudio)
2. In Tools > Options > Environment > General, select any dark theme, like by example 'Plain Dark' or 'Bigface'
3. Make FCC generate a report by starting a tests run

### Current behavior
FCC generates its report as light theme ignoring the custom dark theme currently set

### Expected behavior
Should generate the report as dark theme by detecting it somehow

### Side Notes
- Everything it working fine if I use the built-in Visual Studio Dark theme

**Comment by tonyhallett** [comment]
I will be looking at this shortly

**Comment by jonathanpoulin** [comment]
> I will be looking at this shortly

Great!

But I want to say also that for now it's more a nice-to-have. I really like the Fine Code Coverage VS extension!

Cheers! ;-)

**Comment by tonyhallett** [comment]
@jonathanpoulin 

Latest version uses colours from visual studio theme.
