### ISSUE TITLE
Feature - Make output directory configurable

### ISSUE THREAD

**Issue by BOnstwedder** [FortuneN/FineCodeCoverage#136]
### Current behavior
Fine Code Coverage outputs its coverage files in a directory near TestDllFile's location. 
This is not configurable at this moment

### Expected behavior
Fine Code Coverage outputs to a configurable directory

**Comment by tonyhallett** [comment]
Implementation available [here ](https://ci.appveyor.com/api/buildjobs/plebt84aph6t5065/artifacts/FineCodeCoverage.vsix) for testing.  Not yet released.

Add the AllProjectsCoverageOutputFolder property to any of the test project proj files.

```
  <PropertyGroup>
    <AllProjectsCoverageOutputFolder>../CoverageOutput</AllProjectsCoverageOutputFolder>
  </PropertyGroup>
```

Path can be absolute or relative but do not use msbuild properties to construct the path.

**Comment by BOnstwedder** [comment]
This configuration option seems to work. 

However I do have a question regarding the fine-code-coverage/build-output folders. 
Is it absolutely necessary for fine code coverage to not use the projects build output folder? 
Some of out unit tests are integration tests and fail to run properly when they run from a different directory.

Last I was wondering if it were possible to set the target for opencover, as it would be nice to set this to our locally installed nunit3console exe

**Comment by tonyhallett** [comment]
@BOnstwedder 

> This configuration option seems to work.

We decided method for configuring this output directory.  It did not feel correct for a project to identifier this directory that applies for all test projects.  So this has been replaced with.

> Both of the methods below look for a directory containing a .sln file in an ascendant directory of the directory containing the 
first test project file.  If such a solution directory is found then the logic applies.
If the solution directory has a sub directory fcc-output then it will automatically be used.
Alternatively, if you supply FCCSolutionOutputDirectoryName in options the directory will be created if necessary and used.

> I was wondering if it were possible to set the target for opencover, as it would be nice to set this to our locally installed nunit3console exe

This is doable for sure.  An additional vs option to the exe file that you could also set on a project basis if desired.

> Is it absolutely necessary for fine code coverage to not use the projects build output directory?
Some of out unit tests are integration tests and fail to run properly when they run from a different directory.

I am sure there was a good reason for doing so but off the top of my head I cannot remember what it was.  Perhaps @FortuneN can help on that.

**Comment by tonyhallett** [comment]
[Latest vsix](https://ci.appveyor.com/api/buildjobs/7gj3lhnjlbh8e2l2/artifacts/FineCodeCoverage.vsix) that will be released to marketplace shortly.

**Comment by tonyhallett** [comment]
> it would be nice to set this to our locally installed nunit3console exe

Would you be looking to add additional [nunit console options](https://docs.nunit.org/articles/nunit/running-tests/Console-Command-Line.html#options) ?

> Some of out unit tests are integration tests and fail to run properly when they run from a different directory.

If you could tell us why they don't work then perhaps we could help ?

**Comment by BOnstwedder** [comment]
> Would you be looking to add additional nunit console options ?
For now just setting the target testing framwork for opencover would be enough. This is the target parameter for the opencover command.

> If you could tell us why they don't work then perhaps we could help ?
These tests make use of external files not part of the solution. For instance a directory filled with a testing database, configuration files etc. 
Some of the older unit tests look for these files and since the output of FineCodeCoverage is at least 2 directories deep in a different location it fails to locate these files. Copying the files necessary to run these unit tests would not be optimal for us.

**Comment by tonyhallett** [comment]
Could we provide an NUnit Console test parameter that you could use to adjust your paths ?

**Comment by tonyhallett** [comment]
I think the reason we copied the build output was due to file locking issues

**Comment by tonyhallett** [comment]
The latest version has an option AdjacentBuildOutput that should keep relative paths in tests working.

I will open a new issue with regards to changing the target.
