### ISSUE TITLE
Unable to exclude static class from code coverage

### ISSUE THREAD

**Issue by squire40** [FortuneN/FineCodeCoverage#137]
### Installed product versions
- Visual Studio: [2019 Professional]
- This extension: [16.9.0]

### Description
Lines in a static class are being reported as uncovered. I excluded the class with the [ExcludeFromCodeCoverage] attribute, as well as in the extension options.

### Steps to recreate
1. Create static class
2. Decorate class with [ExcludeFromCodeCoverage] attribute
3. Run all tests in solution

### Current behavior
Extension is reporting the class as uncovered.

### Expected behavior
Extension would skip all classes with [ExcludeFromCodeCoverage] attribute,

**Comment by tonyhallett** [comment]
Can you provide the log from the FCC output window pane

**Comment by squire40** [comment]
The issue has stopped happening for some reason. It's possible restarting Visual Studio refreshed the extension and made it honor the Exclude attribute. This is yet another good use case for refresh, but we can close this issue for now.

**Comment by tonyhallett** [comment]
> The issue has stopped happening for some reason.  It's possible restarting Visual Studio refreshed the extension and made it honor the Exclude attribute. 

I think it is highly unlikely that the extension was the cause of the issue that you were encountering.  I added a static class to a .Net Core and .Net Framework project and run tests from test explorer.  They were not excluded.  I added the attribute and re-run the tests and they were excluded.  I removed the attribute and re-run the tests and they were excluded.

> This is yet another good use case for refresh

If you had just run the tests again after correctly applying the ExcludeFromCodeCoverage then the ui would change to reflect this.

**Comment by tonyhallett** [comment]
> This is yet another good use case for refresh

The refresh button would only have cleared the ui.  It would not have shown that ExcludeFromCodeCoverage attribute was working.  You would have had to re-run tests to see that the static class was excluded and your other classes were included.
