### ISSUE TITLE
An option to freeze header row in coverage table

### ISSUE THREAD

**Issue by AkshanshDwivedi-V36107** [FortuneN/FineCodeCoverage#144]
Visual studio 2019 with latest version of extension.

I wanted to freeze the top row where the column lablels are placed just like excel.

Because if i scroll to bottom and i have a lot of projects i will not be able to see what columns values mean what like COvered, uncovered, coverable, etc.

**Comment by tonyhallett** [comment]
Do you mean to fix a row ?

**Comment by AkshanshDwivedi-V36107** [comment]
Updated the description. aplogies for all the placholder content

**Comment by AkshanshDwivedi-V36107** [comment]
Updated the description. aplogies for all the placholder content

**Comment by tonyhallett** [comment]
I am still none the wiser

**Comment by AkshanshDwivedi-V36107** [comment]
I wanted to freeze the top row where the column lablels are placed just like excel.

Because if i scroll to bottom and i have a lot of projects i will not be able to see what columns values mean what like Covered, uncovered, coverable, etc.

**Comment by tonyhallett** [comment]
Available in new release.  You need to explicitly turn it on in visual studio options for now.
