### ISSUE TITLE
My class went from 9% code coverage to 0% after making tests for to untested methods?

### ISSUE THREAD

**Issue by MathiasBoi6** [FortuneN/FineCodeCoverage#152]
I'm confused and don't understand why this is the case, i think it has something to do with the tests themselves having 0% code coverage, which i don't know what means, the tests clearly run and give the expected results.

What is making it so that my tested methods have 0% code coverage?
Why does code coverage of a test affect the coverage of the system under testing?

**Comment by tonyhallett** [comment]
Please can you provide the log from the FCC Output pane.

It will be even better if you can post some code or create a minimal reproducable example.

> tests themselves having 0% code coverage, which i don't know what means, the tests clearly run and give the expected results.

The tests may be running from the Test Explorer but that does not mean they are neessarily running with code coverage.  For instance you could have attributes applied to the test.

**Comment by tonyhallett** [comment]
Are you using NUnit ExplicitAttribute ?

**Comment by tonyhallett** [comment]
@MathiasBoi6 can you provide the requested information ?
