### ISSUE TITLE
Not cover the integration test

### ISSUE THREAD

**Issue by shanjee** [FortuneN/FineCodeCoverage#153]
### Installed product versions
- Visual Studio: [example 2019 Professional]
- This extension: latest version

### Description
The code coverage not covering the integration test even the test cases are passing and the debug break points are go through the same expected actual business logic.

### Steps to recreate
Just run the newly created test cases

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Report shows the same % even when i cover the new functional area. 

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
Are you using NUnit ExplicitAttribute or something similar ?

Please post the output from the FCC Output window pane.

**Comment by shanjee** [comment]
![image](https://user-images.githubusercontent.com/13603545/121114668-b759cb00-c831-11eb-83f3-0337390b11b0.png)

**Comment by tonyhallett** [comment]
> Are you using NUnit ExplicitAttribute or something similar ?
> 
> Please post the output from the FCC Output window pane.

**Comment by tonyhallett** [comment]
If your project is open source I will have a look.
Are you sure that the path has not already been taken ?

**Comment by tonyhallett** [comment]
@shanjee do you still believe this is an issue ?

**Comment by shanjee** [comment]
yes, issue remain same, i covered the unit tests for individual functions and shows them in green, also i wrote a test to cover the bigger logic which internally calls the smaller function, still the bigger function shows in red color as not covered.

**Comment by tonyhallett** [comment]
You need to provide some details otherwise it is impossible to help.
At the moment I have no idea of the coverage tool being used or its configuration.

Please post the output from the FCC Output window pane.

If you can provide access to your project I could look at it.

If this is not possible then a minimal reproducible may be necessary.

**Comment by shanjee** [comment]
![image](https://user-images.githubusercontent.com/13603545/121520685-d1053900-ca10-11eb-9e8c-cd4ea18d41e0.png)
this is what it shows in the FCC, i cannot even find any logs while running the test cases!!!

**Comment by tonyhallett** [comment]
I need you to go to the Output window. There is an FCC entry in the drop down

**Comment by tonyhallett** [comment]
Can I get access to your project. It would be much easier

**Comment by tonyhallett** [comment]
@shanjee are you going to help determine the cause of your issue ?
