### ISSUE TITLE
This is a nice piece of work! I do wish that i could output the report. I need to do this for management.

### ISSUE THREAD

**Issue by lewisbass-q** [FortuneN/FineCodeCoverage#155]
### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.21]

### Description
Replace this text with a short description

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Explain what it should be doing after it's fixed.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
You can use the vsix from [here](https://www.vsixgallery.com/extension/fcc-f339fe606-9d51-4fca-895c-d50375137b62) which has yet to be released to the marketplace.

> FCC Output
FCC outputs, by default, inside each test project's Debug folder. If you prefer you can specify a folder to contain the files output internally and used by FCC. Both of the methods below look for a directory containing a .sln file in an ascendant directory of the directory containing the first test project file. If such a solution directory is found then the logic applies.

If the solution directory has a sub directory fcc-output then it will automatically be used.

Alternatively, if you supply FCCSolutionOutputDirectoryName in options the directory will be created if necessary and used.

**Comment by lewisbass-q** [comment]
Thank you. That will work
