### ISSUE TITLE
Uninstalling does not delete all configuration data.

### ISSUE THREAD

**Issue by kkohler2** [FortuneN/FineCodeCoverage#156]
If you install, run Visual Studio, go to Tools\Options\Fine Code Coverage, then change something.
Uninstall
Re-install

It appears that the settings  have been preserved across uninstall and new install. How to you get ride of all old settings?
I've deleted C:\Users\yourname\AppData\Local\FineCodeCoverage\
This doesn't accomplish the goal.

My major issue is that code coverage just doesn't work.  It used to, then it stopped working.

**Comment by tonyhallett** [comment]
Can you be specific with the issue you are encountering

**Comment by tonyhallett** [comment]
@kkohler2 are you still having issues ?
