### ISSUE TITLE
Fonts and table layout are not adjusted per display settings for some environments

### ISSUE THREAD

**Issue by smhbhdr** [FortuneN/FineCodeCoverage#158]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.141

### Description
Fonts and display are not adjusted when moving between screens that has different resolutions.

### Steps to recreate
1. Make sure you have at least two different monitors.
2. Set the resolution of the main screen to 3840x2160 and scaling to 250%.
3. Set the resolution of the second screen to 1920x1080 and scaling to 100%.
4. Open Visual Studio with extension enabled.
5. Open Fine Code Coverage tab on main screen and see it is displayed according to the settings.
6. Move Visual Studio window to the second screen.

### Current behavior
Fonts and table layout on extension tab is shown much bigger than the rest of visual studio screen.

### Expected behavior
Fonts and table layout in extension tab must be adjusted when the window is moved to a different display that has different resolution settings.

**Comment by tonyhallett** [comment]
@smhbhdr 

Please can you try one of these vsix.  Is the issue resolved ?

[vsix zipped 2019](https://github.com/FortuneN/FineCodeCoverage/suites/5279799680/artifacts/163408586)
[vsix zipped 2022](https://github.com/FortuneN/FineCodeCoverage/suites/5279799680/artifacts/163408587)

**Comment by tonyhallett** [comment]
@smhbhdr has this issue been resolved ?

**Comment by FortuneN** [comment]
Unfortunately no.
I don't have multiple monitors.
