### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by Amitpnk** [FortuneN/FineCodeCoverage#159]
### Installed product versions
- Visual Studio: [2019]
- This extension: [example 1.1.141]

### Description
Not able to install extension , getting below error

![image](https://user-images.githubusercontent.com/24720047/124357697-899e5100-dc3a-11eb-86ba-0f6824f8df6e.png)

Regards,
Amit Naik

**Comment by tonyhallett** [comment]
Please post the log

**Comment by tonyhallett** [comment]
@Amitpnk 
Did your issue rectify itself ?

**Comment by Amitpnk** [comment]
@tonyhallett ,

Still facing same issue with latest version of extension, attaching log file 

[dd_VSIXInstaller_20210705233719_1764.log](https://github.com/FortuneN/FineCodeCoverage/files/6765821/dd_VSIXInstaller_20210705233719_1764.log)

**Comment by tonyhallett** [comment]
Can you successfully install other extensions ?

**Comment by Amitpnk** [comment]
Updated my visual studio and it is working fine.. thank you so much
