### ISSUE TITLE
Unable to update from 1.0.90 to 1.0.104 in VS2019CE 

### ISSUE THREAD

**Issue by rabanti-github** [FortuneN/FineCodeCoverage#16]
### Installed product versions
- Visual Studio: 2019 Community (v16.7.7)
- Additional VS installation: Visual Studio: 2017Enterprise (v15.9.28) -> Fine Code Coverage is not installed here
- This extension: 1.0.90

### Description
The VSIX package cannot be updated in Visual Studio 2019 (community edition) from 1.0.90 to 1.0.104, even if completely uninstalled and reinstalled. It looks, like a re-installation fetches again 1.0.90. 
When trying to update, a error message occurs "This extension is already installed to all applicable products". After a restart of VS, the extension manager shows again, that Fine Code Coverage is ready to be updated from 1.0.90 to 1.0.104

I'am sorry to provide not more information about that. Is there any possibility to enable logging, or can you tell where I find useful information about the failed installation?

### Steps to recreate
1. Start VS2019 with an arbitrary project
2. Select menu item "Extensions" -> "Manage Extensions"
3. Go to the tab "Updates"
3b. Fine Code Coverage should be available to be updated here
4. Click on "Update"
5. Close VS
5b. The VSIX istaller starts and shows the error
![2020-11-03 01_49_17-VSIX Installer](https://user-images.githubusercontent.com/6697127/97935243-47a1d000-1d78-11eb-9238-fe463e5ac88f.png)
6. Restart VS
7. The Extension is again showed to be updated
![2020-11-03 01_50_07-PicoXLSX3 - Microsoft Visual Studio](https://user-images.githubusercontent.com/6697127/97935246-48d2fd00-1d78-11eb-8024-bcad9598eb15.png)

### Current behavior
The installer seems to have trouble with the configuration of the available VS installations and refuses to update

### Expected behavior
The extension should be updated after triggering the update and closing VS

**Comment by FortuneN** [comment]
I have raised the version into the 1.1.xx range.
Please try again and let me know

**Comment by rabanti-github** [comment]
Yes, looks good.
The installation was now successful. The extension has now the expected version 1.1.1
Thank you for the quick fix.

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
