### ISSUE TITLE
No data on the Risk Hotspots tab.

### ISSUE THREAD

**Issue by jwdonahue** [FortuneN/FineCodeCoverage#160]
### Installed product versions
- Visual Studio: 2019 Pro
- This extension: 1.1.141

### Description
Risk Hotspots tab is empty.

### Steps to recreate
1. Run tests
2. Check Coverage tab (slow, but it's there).
3. Check Summary tab (looks good).
4. Check Risk Hotspots (empty!)

### Current behavior
It's not displaying anything.

### Expected behavior
There should be some data showing risk hotspots.

### Side Notes
[coverage-tool-output.zip](https://github.com/FortuneN/FineCodeCoverage/files/6768025/coverage-tool-output.zip)

**Comment by tonyhallett** [comment]
ReportGenerator has thresholds for risk hotspots
https://github.com/danielpalme/ReportGenerator/blob/e1c7bc5e6c5e532f70fd69713e99026ad8b5114e/src/ReportGenerator.Core/CodeAnalysis/RiskHotspotsAnalyzer.cs#L74

These are determined here
https://github.com/danielpalme/ReportGenerator/blob/e1c7bc5e6c5e532f70fd69713e99026ad8b5114e/src/ReportGenerator.Core/Generator.cs#L52

Although the property for cyclomatic complexity defaults to 15
https://github.com/danielpalme/ReportGenerator/blob/e1c7bc5e6c5e532f70fd69713e99026ad8b5114e/src/ReportGenerator.Core/CodeAnalysis/RiskHotspotsAnalysisThresholds.cs#L11

The appsettings.json defines the value as 30
```
{
  "riskHotspotsAnalysisThresholds": {
    "metricThresholdForCyclomaticComplexity": 30,
    "metricThresholdForCrapScore": 15,
    "metricThresholdForNPathComplexity": 200
  },
```

None of your methods have complexity that exceed that value.

You can change appsettings.json if you desire.  On my machine.

C:\Users\tonyh\AppData\Local\FineCodeCoverage\reportGenerator\4.7.1\.store\dotnet-reportgenerator-globaltool\4.7.1\dotnet-reportgenerator-globaltool\4.7.1\tools\netcoreapp3.0\any

**Comment by jwdonahue** [comment]
Those limits are way too high.  A CC > 10 should be a very rare occurrence.  Are crap score and npath complexity documented anywhere?

**Comment by tonyhallett** [comment]
https://github.com/danielpalme/ReportGenerator/wiki/Settings

Npath and crap score are not available for Coverlet if I remember correctly.

I will add something to the FCC documentation re Report Generator.

FCC does not provide settings for Report Generator currently.  If you feel that we should allow spwecification of command line arguments then please open a separate feature request issue.

**Comment by tonyhallett** [comment]
For comparison visual studio analyzer has CC as 25
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1502

**Comment by jwdonahue** [comment]
I would never put a Microsoft default setting up as the gold standard for anything.  I set mine to 1. I like to see just how hot my entire project is at a glance. I start eyeing functions/methods with a CC of 5 or more and refactor most, but not all code above 10. Out of ~10K lines of code in one of my more complex, experimental projects, I have 4 methods that exceed 10 and only one that exceeds 20. None are 25 or greater. Most of those will be reduced or removed in a planned refactor, prior to release.

In 30 years, I have released maybe 3 or 4 functions that exceed 25, they were all unavoidable giant switch statements and all fully reduced to a single function call per case statement. All were written before we had good optimizing compilers for their target platforms (mostly embedded).

Thanks for the clues btw!

**Comment by tonyhallett** [comment]
> I would never put a Microsoft default setting up as the gold standard for anything

I wasn't.

**Comment by jwdonahue** [comment]
I think an empty tab view is a UI design fail. It should at least at least provide some indication that it's not broken. Perhaps a message along the lines of:

`Complexity levels do not exceed thresholds set in <path/appsettings.json>`

**Comment by tonyhallett** [comment]
Latest [vsix](https://ci.appveyor.com/api/buildjobs/tvofd4a5gn1y9vfa/artifacts/FineCodeCoverage.vsix) ( not yet released to marketplace ) has the following changes 

Setting thresholds in appsettings.json is not suppoted.  Instead you can set these values in vs options.

When there are no risk hotspots there is now a message stating so that includes the values of the thresholds set in visual studio.

**Comment by jwdonahue** [comment]
Wow that was a quick turn-around.

Tested. Seems to be working well. Thank you!
