### ISSUE TITLE
Coverage is not updated the Resharper Test Explorer is used

### ISSUE THREAD

**Issue by StuartHemming** [FortuneN/FineCodeCoverage#166]
### Installed product versions
- Visual Studio: 2019 Professional
- FineCodeCoverage: 1.1.141

### Description
Coverage is not updated the Resharper Test Explorer is used.

### Steps to reproduce
1. Install resharper
2. Extensions | Resharper | Unit Tests | Unit Tests | Run Unit Tests
3. View Fine Code Coverage window and nothing updates

If I run the same tests from the VS Test Explorer, it FineCodeCoverage window updates

**Comment by tonyhallett** [comment]
FCC uses the api of the Visual Studio Test Explorer.  So it is not possible to get the exact same functionality.
If Resharper can generate a code coverage report ( e.g from runsettings ) the best we can do ( unless there is an api ) is to watch for the generated cobertura file and then use that to generate the report and the coloured margin indicators.

Can Resharper generate code coverage ?

**Comment by tonyhallett** [comment]
Resharper does have a plugin system. The docs are incomplete though for unit testing. 

This page https://www.jetbrains.com/help/resharper/sdk/DotNetCore.html#mapping-net-core-tests-to-resharper-elements mentions that they invoke dotnet test so if a plugin is able to intercept and add arguments then a coverage file could be generated. Of course this seems unlikely given the additional licensing.

If a developer shows that this is possible then FCC will look at again.

**Comment by tonyhallett** [comment]
If FCC worked with the runsettings you provided but Resharper threw an exception then your support request is  the appropriate action. Unfortunately I cannot view this request. Please keep FCC with the narrative.

**Comment by tonyhallett** [comment]
@Prodigio 
Did you get a response ?

**Comment by tonyhallett** [comment]
Did you try runsettings configured for ms code coverage ?
If you set RunMsCodeCoverage to Yes then FCC will generate a runsettings specific to ms code coverage, when you run tests from Test Explorer.  You could then provide these runsettings to Resharper.

from https://resharper-support.jetbrains.com/hc/en-us/community/posts/360010414739-Runsettings-ignored-when-using-VS-NUnit-Resharper-test-runner

![image](https://user-images.githubusercontent.com/11292998/191961118-0319766d-c6e6-49e2-a6f0-b7005f2f16f1.png)

Look for `\YourTest\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output`
YourTest-fcc-mscodecoverage-generated.runsettings

**Comment by StuartHemming** [comment]
Sorry, I'm out if rhe country at the moment, but, at the ladt time of checking, no

**Comment by tonyhallett** [comment]
@Prodigio
