### ISSUE TITLE
Unable to run tests that require 64bit OpenCover profiler

### ISSUE THREAD

**Issue by SiarheiMachel** [FortuneN/FineCodeCoverage#167]
### Installed product versions
- Visual Studio: 2019 Professional (16.10.0)
- This extension: 1.1.141

### Description
I have couple tests that take values from registry. Thus, they require 64bit process to be run. Can I somehow override default OpenCover settings that FCC specify?

**Comment by tonyhallett** [comment]
Not currently.
Is it the register switch that you need ? https://github.com/opencover/opencover/wiki/Usage

**Comment by Sergey1209** [comment]
Yes. Strangely, it worked previously, but now started failing with an error that it cannot access registry as a 32 bit process. At the same time, VS test explorer is running fine under 64bit.

**Comment by tonyhallett** [comment]
Do you have an open source project that I can test against ? If not can your create a minimal repro.

**Comment by tonyhallett** [comment]
I created a single test that read sub keys from Registry.Users and had no issue.
I am using Visual Studio Community 2019 Version 16.10.3

**Comment by Sergey1209** [comment]
I'm working on a huge enterprise project, cannot share it, unfortunately. Will try it on test project and report the results here

**Comment by tonyhallett** [comment]
Available in latest version
