### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by trumhemcut** [FortuneN/FineCodeCoverage#169]
Is there statement coverage?

**Comment by tonyhallett** [comment]
Line coverage ( branch coverage is in the xml report but not currently used in the coverage tab report)

![image](https://user-images.githubusercontent.com/11292998/127173382-9332cf6f-f4d7-413c-a465-f6f1cacde475.png)
![image](https://user-images.githubusercontent.com/11292998/127173509-4c0f5989-cf22-499b-bed2-951fddc34c6b.png)

https://github.com/cobertura/cobertura/wiki/Line-Coverage-Explained
