### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fahadabdulaziz** [FortuneN/FineCodeCoverage#17]
### Installed product versions
- Visual Studio: 2019
- This extension: 1.1.4

### Description
After each run of tests VS process consumes more RAM (during the extension processing the result) after many runs the process exceeds the limit then crash.

It would be great to look at what's making the memory leak & and would be better to be out-of-proc extension for future proof.

Many many thanks for the great extension I really like it.

**Comment by FortuneN** [comment]
Please try this version and let me know
[Fine Code Coverage v1.1.5.zip](https://github.com/FortuneN/FineCodeCoverage/files/5503335/Fine.Code.Coverage.v1.1.5.zip)
(This version is not public yet)

**Comment by fahadabdulaziz** [comment]
Thank you, I'll test it right now 👍

**Comment by fahadabdulaziz** [comment]
Yes, The problem is resolved. good job

**Comment by FortuneN** [comment]
Please post a review

https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo

**Comment by fahadabdulaziz** [comment]
Already stared, and just posted a review .

**Comment by FortuneN** [comment]
Thank you
