### ISSUE TITLE
No Code coverage

### ISSUE THREAD

**Issue by MichaelInsberg** [FortuneN/FineCodeCoverage#170]
### Installed product versions
- Visual Studio: 2019 Professional Version 16.10.4
- ![Packages](https://user-images.githubusercontent.com/78546805/128465958-979577dd-458d-4aed-a9f8-bb98354175a6.PNG)

### Description
When I run the Nunit tests  with the VS Test Explorer I get no Code Coverage. The Code Coverage XML file is empty also the HTML files

### Steps to recreate
1. Run Tests
2. Go to FCC output 
3. All page are empty

### Current behavior
No Code Coverage

### Expected behavior
See the Code Coverage

##Project file
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netcoreapp3.1</TargetFramework>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<PlatformTarget>AnyCPU</PlatformTarget>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
		<PackageReference Include="NUnit" Version="3.13.1" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
		<PackageReference Include="SonarAnalyzer.CSharp" Version="8.26.0.34506">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>

### FCC Output
Fine Code Coverage : 
Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (IEquatableExample)

Fine Code Coverage : Coverlet Run (IEquatableExample) Arguments 
"C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\IEquatableExample.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
--output "C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\IEquatableExample.coverage.xml"
--targetargs "test  ""C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\IEquatableExample.dll"" --nologo --blame --settings ""C:\Projekte\Framework4.0\Misc\IEquatableExample\\Jet.Framework.runsettings"" --results-directory ""C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"" --diag ""C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output/diagnostics.log""  "

Fine Code Coverage : Coverlet Run (IEquatableExample)
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\diagnostics.log
A total of 1 test files matched the specified pattern.
Passed!  - Failed:     0, Passed:     9, Skipped:     0, Total:     9, Duration: 23 ms - IEquatableExample.dll (netcoreapp3.1)

Calculating coverage result...
  Generating report 'C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\IEquatableExample.coverage.xml'
+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 100% | 100%   | 100%   |
+---------+------+--------+--------+
| Average | NaN% | NaN%   | NaN%   |
+---------+------+--------+--------+

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"
"-reports:C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\IEquatableExample.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
2021-08-06T08:29:45: Arguments
2021-08-06T08:29:45:  -targetdir:C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output
2021-08-06T08:29:45:  -reports:C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\IEquatableExample.coverage.xml
2021-08-06T08:29:45:  -reporttypes:Cobertura
2021-08-06T08:29:45: Writing report file 'C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2021-08-06T08:29:45: Report generation took 0,1 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"
"-reports:C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:C:\USERS\MINSBERG\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_55084D54\EXTENSIONS\0XZI4KSW.OSU\ReportGeneratorPlugins.dll"
"-reporttypes:FccLight"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2021-08-06T08:29:45: Arguments
2021-08-06T08:29:45:  -targetdir:C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output
2021-08-06T08:29:45:  -reports:C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\Cobertura.xml
2021-08-06T08:29:45:  -plugins:C:\USERS\MINSBERG\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_55084D54\EXTENSIONS\0XZI4KSW.OSU\ReportGeneratorPlugins.dll
2021-08-06T08:29:45:  -reporttypes:FccLight
2021-08-06T08:29:45: Writing report file 'C:\Projekte\Framework4.0\Misc\IEquatableExample\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\index.html'
2021-08-06T08:29:45: Report generation took 0,3 seconds

Fine Code Coverage : ================================== DONE ==================================

[fine-code-coverage.zip](https://github.com/FortuneN/FineCodeCoverage/files/6943454/fine-code-coverage.zip)

**Comment by tonyhallett** [comment]
can you share your solution with me

**Comment by tonyhallett** [comment]
Your sut is in the same dll as your tests and as you have not included the test assembly there will be no results.

![image](https://user-images.githubusercontent.com/11292998/128481083-8de8c6c9-aefb-4edf-97f2-e505c74ade5b.png)

![image](https://user-images.githubusercontent.com/11292998/128481166-703dc66a-07c9-4ece-97e1-474561fb5e12.png)

**Comment by MichaelInsberg** [comment]
Thanks Tony
