### ISSUE TITLE
How to excluded referenced project in solution

### ISSUE THREAD

**Issue by sweideh** [FortuneN/FineCodeCoverage#171]
### Installed product versions
- Visual Studio: [example 2019 Professional]
- This extension: [example 1.1.141]

### Description
I want to excluded my referenced projects in my solution A without adding the excluded tag to the referenced project csproj itself.

### Reason
The excluding projects have their own tests which are not shown in the solution A. So the coverage would always be zero.

### Steps to recreate
1. Add project B
2. Add project B to new solution B
3. Create project A
4. Add project A to new solution A
5. Add class to project A
6. Add test for class
7. Reference project B

### Current behavior
project b is shown in the code coverage results.

### Expected behavior
Project b shouldn't be shown in the code coverage results

**Comment by tonyhallett** [comment]
Exclude from the test project

**Comment by sweideh** [comment]
Thanks, that worked.
