### ISSUE TITLE
Hi Fortune !

### ISSUE THREAD

**Issue by tonyhallett** [FortuneN/FineCodeCoverage#175]
@FortuneN 
I have added the workflows for github actions and deleted the appveyor file.

Slight issue - the PAT has expired.
https://github.com/FortuneN/FineCodeCoverage/runs/3353450015?check_suite_focus=true

> VSSDK: error VsixPub0031 : An error occurred while attempting to authenticate: Access Denied: The Personal Access Token used has expired.

If you can rectify this I can then merge a fake pull request to check that the functionality works as expected.

Thanks

**Comment by FortuneN** [comment]
Hey Tony,

- I've updated the access token. It's good for 1 year (they won't allow me to go further than that)
- I ran the action and the issue no longer an access one https://github.com/FortuneN/FineCodeCoverage/runs/3354890722?check_suite_focus=true

Good luck

**Comment by tonyhallett** [comment]
Thanks for updating and rerunning the action. The manifest needs less fields. I will update tomorrow. I will describe the workflows in the contributor guide.
