### ISSUE TITLE
Enhancement: Be able to ignore generated code (e.g. protobuf classes)

### ISSUE THREAD

**Issue by Smurf-IV** [FortuneN/FineCodeCoverage#18]
- It just makes the complexity view really confusing
- Could use some config file that is stored at solution level
- this config could then be used to ignore certain "test util" / Demo / etc. projects as well.

**Comment by Smurf-IV** [comment]
Seems like this is now documented.. I missed that !

**Comment by FortuneN** [comment]
Please post a review 

https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
