### ISSUE TITLE
Any plan for VS 2022?

### ISSUE THREAD

**Issue by YBAZAN** [FortuneN/FineCodeCoverage#184]
All is in the question : is is planned to release this wonderful extension to Visual Studio 2022?

**Comment by Retrodad0001** [comment]
I hope so :)

**Comment by FortuneN** [comment]
Yep. There is

**Comment by steve09014098** [comment]
VS2022 was released yesterday, Any plans to release this for 2022 soon?

**Comment by FortuneN** [comment]
@tonyhallett 
I think this is going to be one of our most important updates so far.
I'll dive as well; We can compare notes.

**Comment by tonyhallett** [comment]
@FortuneN 
I have also done reports that use visual studio themes.  More mangling of the generated report.  At some point I will do it properly with or without ReportGenerator.
After we have visual studio 2022 done I will get the code in.

**Comment by tonyhallett** [comment]
@FortuneN 

The code here demonstrates what I have been doing with report theming
https://github.com/tonyhallett/ReportGenerator

There are two windows Report and Settings
The Report updates from the Settings window
Each section of the report has a row on the settings page.
Click one and a combo will show.  These are named colours that a visual studio Theme can provide.
You change the combo and the report will reflect.

The settings as they are should work well with all of the visual studio themes.
You can see what each section looks like for each Theme by selecting from the Settings/Themes menu.

e.g 
Aletheia
![image](https://user-images.githubusercontent.com/11292998/140975866-e28c6d61-e83e-4aa4-a3e4-b92cc7e5f6b0.png)

Blue
![image](https://user-images.githubusercontent.com/11292998/140975973-b312c54e-b4dc-44b7-bf25-163b4fdd25c7.png)

Solarized Light
![image](https://user-images.githubusercontent.com/11292998/140976107-f3b55fd7-f7a4-4e86-b132-954deb8528ba.png)

Feel free to find a better choice !

The code changes that I have made upon the back of this also take into account windows contrast settings too.

**Comment by tonyhallett** [comment]
@FortuneN 

I followed the [advice](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022) and converted to a shared project etc.

Unfortunately when debugging 2019 vs 2022 there is different behaviour.
2019 appears to be working.  I say appears because the behaviour was inconsistent.  After resetting the experimental instance it does seem ok.

![image](https://user-images.githubusercontent.com/11292998/141167799-2a949c81-28e8-4483-8c06-a835635bfff2.png)

2022 on the other hand ! 
Best for you to make your own conclusions on this 
https://github.com/tonyhallett/FineCodeCoverage/tree/vs2022

I will not be spending any more time on this for the foreseeable future.

Your thoughts on the theming from the comment above will be appreciated.

**Comment by tonyhallett** [comment]
@FortuneN 
I created a new VSIX 2022 only project with an exported ITestContainerDiscoverer.  It was not constructed when the test explorer loaded.  Major issue.

From https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter
![image](https://user-images.githubusercontent.com/11292998/141308137-2642c410-3a07-4b74-b308-61f1f6c9509d.png)

**Comment by tonyhallett** [comment]
Ignore that for now.

**Comment by tonyhallett** [comment]
@FortuneN 
I have successfully converted so there is a 2022 version and a pre 2022 version.  The github actions need to change to generate two vsix.  Hopefully by the end of the day we can release for vs 2022.

**Comment by tonyhallett** [comment]
Please download [vsix for 2022](https://github.com/FortuneN/FineCodeCoverage/releases/download/v1.1.145/FineCodeCoverage2022.vsix)

This is not currently on the marketplace as the github action failed ( passed for 2019 ).
Working on that now

**Comment by tonyhallett** [comment]
Both available on the marketplace now
https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage
https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage2022

**Comment by IFYates** [comment]
Amazing work, @tonyhallett 
Just installed it and worked perfectly.
