### ISSUE TITLE
Where is the 'FCC Clear UI' button

### ISSUE THREAD

**Issue by Jerther** [FortuneN/FineCodeCoverage#187]
### Installed product versions
- Visual Studio: 2019 community
- This extension: 1.1.141

### Description
I have pretty much this issue: https://github.com/FortuneN/FineCodeCoverage/issues/132 . The results take up to a minute to update after I run all tests, and this is very, very, **very** misleading. So I looked for the clear button as stated in the readme file:

> When the coverage becomes outdated, you can click the 'FCC Clear UI' button in Tools or run coverage again.

But this button or menu is nowhere to be found. Or I'm blind or something ;P

### Steps to recreate
1. Run all tests
2. Wait for the coverage results to show.
3. Do some modifications and run the tests again
4. Wait for the results to update and try to guess when that actually happens.

### Current behavior
There is no _'FCC Clear UI' button in Tools_ or menu item to clear the results between runs.

![image](https://user-images.githubusercontent.com/5856745/136042323-2c50787b-83f7-47d1-8549-c1e481d29f9f.png)

![image](https://user-images.githubusercontent.com/5856745/136042469-6232de18-1bbf-4c52-a953-ec321e4753aa.png)

### Expected behavior
There is a button to clear the results between runs.

### Side Notes
Or even better, the results should automatically be cleared between runs.

**Comment by tonyhallett** [comment]
I have an outstanding issue with the vsix marketplace and as such the marketplace is not reflecting the current state of the repository.

In the mean time you can install [this vsix](https://github.com/FortuneN/FineCodeCoverage/releases/download/v1.1.144/FineCodeCoverage.vsix).

I have other projects that I am concentrating on for the next couple of weeks but after that I will get the current release to be on the marketplace.

**Comment by Jerther** [comment]
Excellent! The links to an updated vsix are dead on the issue I linked. Thanks for the updated link!
