### ISSUE TITLE
Report only includes test assembly

### ISSUE THREAD

**Issue by MaQy** [FortuneN/FineCodeCoverage#188]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.141

### Description
The generated report is only including coverage for the test assembly, none of the referenced projects are shown. I also included the property `UseDataCollector` just in case but nothing changed.

### Side Notes
I'm using xunit.

![imagen](https://user-images.githubusercontent.com/1781660/137166356-1b3fcac8-c515-427e-b4bf-144c911e96ea.png)

This is the output from FCC:

```Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (Loc.Cms.UnitTests)

Fine Code Coverage : Coverlet Collector Run (Loc.Cms.UnitTests) Arguments 
"E:\git\LocCMS\api\source\Loc.Cms.UnitTests\bin\Debug\net5.0\fine-code-coverage\build-output\Loc.Cms.UnitTests.dll" --blame --nologo --diag "E:\git\LocCMS\api\source\Loc.Cms.UnitTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output/diagnostics.log" --settings "E:\git\LocCMS\api\source\Loc.Cms.UnitTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output/FCC.runsettings" --results-directory "E:\git\LocCMS\api\source\Loc.Cms.UnitTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output"

Fine Code Coverage : Coverlet Collector Run (Loc.Cms.UnitTests)
Starting test execution, please wait...
Logging Vstest Diagnostics in file: E:\git\LocCMS\api\source\Loc.Cms.UnitTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\diagnostics.log
A total of 1 test files matched the specified pattern.

Attachments:
  E:\git\LocCMS\api\source\Loc.Cms.UnitTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\9c4e3aee-85bd-45e0-8775-31ebb9159b7b\coverage.cobertura.xml
Passed!  - Failed:     0, Passed:  4950, Skipped:     5, Total:  4955, Duration: 1 m 29 s - Loc.Cms.UnitTests.dll (net5.0)

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:E:\git\LocCMS\api\source\Loc.Cms.UnitTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output"
"-reports:E:\git\LocCMS\api\source\Loc.Cms.UnitTests\bin\Debug\net5.0\fine-code-coverage\coverage-tool-output\Loc.Cms.UnitTests.coverage.xml"
"-reporttypes:Cobertura"
```

Could you please point out what I'm doing wrong?

Thanks!

**Comment by tonyhallett** [comment]
Are you using run settings ?

Is your solution open source so I can look at it ?

Otherwise you will need to create minimal reproducible solution so that I can look at that.

**Comment by tonyhallett** [comment]
Also, in the diagnostics do you see "Unable to instrument module...." ?

Could this [coverlet  issue](https://github.com/coverlet-coverage/coverlet/issues/1215) possibly describe this issue.

This [coverlet issue](https://github.com/coverlet-coverage/coverlet/issues/1164) mentions source generators.

**Comment by JosefNemec** [comment]
I had the same issue (only test project being covered) when using NUnit. What fixed it for me was switching from NUnit's VS extension test adapter to NUnit test adapter nuget package.

**Comment by marbel82** [comment]
@MaQy You can bypass coverlet bug.

When Fine Code Coverage print that some assembly (or class) is missing
> Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces,...

You can manually copy missing assemblies to `...\bin\Debug\net5.0\`, and then run tests.

In my case Fine Code Coverage began working.

**Comment by tonyhallett** [comment]
@marbel82 
I cannot find any coverlet issue mentioning Microsoft.Bcl.AsyncInterfaces.
Is it a package reference issue instead ?

**Comment by marbel82** [comment]
@tonyhallett I write only example. @MaQy wrote above that in the diagnostics log he has `Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces,...`

In my case Fine Code Coverage (more precisely coverlet) had a problem with:
>Unable to instrument module: c:\SomeProject\Tests\Module.Tests\bin\Debug\net5.0-windows\Module.dll because : AssemblyResolutionException for 'PresentationFramework, Version=5.0.0.0,...

See https://github.com/coverlet-coverage/coverlet/issues/1221#issuecomment-957739708

**Comment by tonyhallett** [comment]
@marbel82 thanks for your work around.

@MaQy Is visual studio giving any warnings about AsyncInterfaces ?

**Comment by tonyhallett** [comment]
@MaQy 
Have you tried the workaround suggested.
If you cannot provide any further information I will have to close.
