### ISSUE TITLE
With the Extension installed visual studio throws a "Dictionary element not found exception"

### ISSUE THREAD

**Issue by Smurf-IV** [FortuneN/FineCodeCoverage#19]
### Installed product versions
- Visual Studio: 16.7.# Pro
- This extension: Latest and previous

### Description
In the title

### Steps to recreate
- Just compiling away etc.
- Yellow bar pop's up at the top
- clicking on the "Open log" does nothing
- uninstall extension and the problems goes away (For days)
- re-install and it will be back on the same day

**Comment by FortuneN** [comment]
Please try this version and let me know
[Fine Code Coverage v1.1.5.zip](https://github.com/FortuneN/FineCodeCoverage/files/5503345/Fine.Code.Coverage.v1.1.5.zip)
(This version is not public yet)

**Comment by FortuneN** [comment]
Please provide update; I don't have the ability to reproduce and test on my side

**Comment by FortuneN** [comment]
Please try the latest version (1.1.11+) version and let me know

**Comment by FortuneN** [comment]
**Long short (based on time and effort that you can invest in this)**
- Clone the repo, run it and maybe see in debug mode where/how this blows up.
- Post results

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/99251229-e3195300-2804-11eb-88c6-83ee9a640f00.png)

**Comment by FortuneN** [comment]
I cannot reproduce this issue.
I'm afraid a must close
