### ISSUE TITLE
Code Coverage is 0% , Visited Classes,Methods,Points,Branches etc is 0

### ISSUE THREAD

**Issue by adityajaiswal123** [FortuneN/FineCodeCoverage#191]
Installed product versions
- Visual Studio:  2019 Professional
- extension:  1.1.10

Description

We are having a VB.Net Application where we have unit test projects. When we try to run fine code coverage tool to get the unit test coverage we are getting it as 0%. See Screenshot Below.

![image](https://user-images.githubusercontent.com/92977989/138445944-c2ded978-689a-4bde-9a3d-1ba6f717f85e.png)

Attached is the output file for FCC
[FCC.txt](https://github.com/FortuneN/FineCodeCoverage/files/7396734/FCC.txt)

**Comment by adityajaiswal123** [comment]
No, Our test is not reliant on fixed path.

Here result after running Opencover.

`Microsoft Windows [Version 10.0.18363.1556]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\openCover\4.7.922\tools>OpenCover.Console " -target: D:\DOXIM\DEV_2022April\crm\DoximLOSUnitTest\bin\Debug\DoximLOSUnitTest.dll"
Executing: D:\DOXIM\DEV_2022April\crm\DoximLOSUnitTest\bin\Debug\DoximLOSUnitTest.dll
Failed to execute the following command ' D:\DOXIM\DEV_2022April\crm\DoximLOSUnitTest\bin\Debug\DoximLOSUnitTest.dll '
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
`

**Comment by tonyhallett** [comment]
You need to supply the same arguments as FCC, look in the FCC Output Pane, except you supply the path to the actual test dll and not to the copy.
![image](https://user-images.githubusercontent.com/11292998/141117989-614daf72-db7b-4ddb-a4c2-c621c4e5bb5a.png)

The target is the vstest console and targetargs is your test dll.

**Comment by tonyhallett** [comment]
What are you using Castle.Core for ?
Are you using a code generator ?

Does removing OpenCover from your package references make any difference ?

**Comment by adityajaiswal123** [comment]
Microsoft Windows [Version 10.0.18363.1556]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\openCover\4.7.922\tools>opencover.console -mergebyhash -hideskipped:all -register:path32 "-target:C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "-excludebyfile:**/Migrations/*" "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" "-targetargs:\"D:\DOXIM\DEV\crm\DoximLOSUnitTest\bin\Debug\fine-code-coverage\build-output\DoximLOSUnitTest.dll\" " "-output:D:\DOXIM\DEV\crm\DoximLOSUnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\DoximLOSTest.coverage.xml"
Output folder does not exist; please create it and make sure appropriate permissions are set.

C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\openCover\4.7.922\tools>opencover.console -mergebyhash -hideskipped:all -register:path32 "-target:C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "-excludebyfile:**/Migrations/*" "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" "-targetargs:\"D:\DOXIM\DEV\crm\DoximLOSUnitTest\bin\Debug\fine-code-coverage\build-output\DoximLOSUnitTest.dll\" "
Executing: C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 16.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

The test source file "D:\DOXIM\DEV\crm\DoximLOSUnitTest\bin\Debug\fine-code-coverage\build-output\DoximLOSUnitTest.dll" provided was not found.
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\openCover\4.7.922\tools>opencover.console -mergebyhash -hideskipped:all -register:path32 "-target:C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "-excludebyfile:**/Migrations/*" "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" "-targetargs:\"D:\DOXIM\DEV\crm\DoximLOSUnitTest\obj\debug\DoximLOSUnitTest.dll\" " "-output:D:\DOXIM\DEV\crm\DoximLOSUnitTest\bin\Debug\fine-code-coverage\coverage-tool-output\DoximLOSTest.coverage.xml"
Output folder does not exist; please create it and make sure appropriate permissions are set.

C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\openCover\4.7.922\tools>opencover.console -mergebyhash -hideskipped:all -register:path32 "-target:C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "-excludebyfile:**/Migrations/*" "-excludebyattribute:(*.ExcludeFromCodeCoverage)|(*.ExcludeFromCodeCoverageAttribute)|(*.ExcludeFromCoverage)|(*.ExcludeFromCoverageAttribute)|(*.GeneratedCode)|(*.GeneratedCodeAttribute)" "-targetargs:\"D:\DOXIM\DEV\crm\DoximLOSUnitTest\obj\debug\DoximLOSUnitTest.dll\" "
Executing: C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\msTestPlatform\16.9.1\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 16.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

The test source file "D:\DOXIM\DEV\crm\DoximLOSUnitTest\obj\debug\DoximLOSUnitTest.dll" provided was not found.
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

C:\Users\aditya.jaiswal\AppData\Local\FineCodeCoverage\openCover\4.7.922\tools>

**Comment by adityajaiswal123** [comment]
Removing opencover reference makes no difference , Also removed castle core still no difference.

**Comment by tonyhallett** [comment]
and the dll exists no doubt ?

**Comment by adityajaiswal123** [comment]
yes dll exist

**Comment by tonyhallett** [comment]
pdbs present no doubt ?
Which suggests 2)

> 2) the profiler may not be registered correctly, please refer to the Usage
guide and the -register switch.

from https://github.com/OpenCover/opencover/wiki/Usage
```
-register[:user] - Use this switch to register and de-register the code coverage profiler. Alternatively use the optional user argument to do per-user registration where the user account does not have administrative permissions. Alternatively use an administrative account to register the profilers using the regsvr32 utility. If you do not want to use the registry entries, use -register[:Path32] or -register[:Path64]to let OpenCover select the profiler for you. Depending on your choice it selects the <OpenCoverAssemblyLocation>/x86/OpenCover.Profiler.dll or <OpenCoverAssemblyLocation>/x64/OpenCover.Profiler.dll.

You should also consider using path32 and path64 options when profiling .net core targeted applications and .net 4.8 framework.
```

Does this suggest that FCC is providing the incorrect value ?

**Comment by tonyhallett** [comment]
Did you try user ?

Given that coverage is not occuring without FCC all I can suggest is that you post an issue with OpenCover.  Please link back to this so we can follow.

**Comment by BeanYa** [comment]
I ever made a similar extension for code coverage, I met this familiar scenario and tried `-register:path64`  to fix it which success.

I tried `Find Code Coverage` and it only showed the Assembly of current UnitTest.

The project like:

- Code
    * Code.cs
- Code.UnitTest
    * CodeUnitTest.cs

The Find Code Coverage only shows the coverage of `Code.UnitTest` but the really target assembly is `Code`

The FCC output:

`Fine Code Coverage : OpenCover Run (**) Arguments 
 -mergebyhash 
 -hideskipped:all 
 -register:path32 `

I wanna know how can I edit this argument to test my scenario ?

**Comment by tonyhallett** [comment]
@BeanYa 
> I wanna know how can I edit this argument to test my scenario ?

Currently you cannot.  Can you run directly against the coverage tool like https://github.com/FortuneN/FineCodeCoverage/issues/191#issuecomment-965241097.
Provide the real dll initially.  
If coverage changes I will add an option for this argument

**Comment by BeanYa** [comment]
For some policy limits, I cannot provide the dll.

I solved a similar problem in my code coverage extension by edit the default arguments of `Open Cover` which is `-register:path64`.

But that was a highly customized extension, I am trying to use `Find Code Coverage` to replace that.

This is my open cover arguments:

`const string OpencoverArgFormat = "-target:\"{0}\" -targetargs:\"{1} --work={2}\" -output:\"{3}\" \"-searchdirs:{4}\" -register:path64 -filter:\"+[*]* -[nunit*]* -[Autofac*]* \"";`

If there is no option to specify this arguments, I would continue to use my extension.

Thanks.

**Comment by tonyhallett** [comment]
@adityajaiswal123 
Did you get FCC working ?

**Comment by adityajaiswal123** [comment]
@tonyhallett yes FCC is working now , need to add OpenCover path in OpneCoverCustomPath.
