### ISSUE TITLE
Group files by namespace

### ISSUE THREAD

**Issue by AndrewBater** [FortuneN/FineCodeCoverage#192]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.141

### Description
Would it be possible to group files by namespace or directory the same way (or similar) to how the files appear in the VS Test Explorer window? Vewing the output from this extension on a project with hundreds of files can make it quite hard to differentiate similar files, or even hard to find certain files having to scroll through a massive list. If the files could be grouped by either directory or namespace that would be a fantastic upgrade.

### Current behavior
Each file is listed alphabetically in a long list, making it harder to find files in large projects.

### Expected behavior
Files should be grouped together either by directory or namespace.

**Comment by tonyhallett** [comment]
Note to self.
Showing the grouping slider is not sufficient as it does not work in the web browser control
```
coverage-info div.customizebox div:nth-child(2) {{ opacity:0;font-size:1px;height:1px;padding:0;border:0;margin:0 }}
					coverage-info div.customizebox div:nth-child(2) * {{ opacity:0;font-size:1px;height:1px;padding:0;border:0;margin:0 }}
```

**Comment by tonyhallett** [comment]
@FortuneN 
This functionality can be provided with the current report ( given that ReportGenerator provides this functionality ).
This does change the sort behaviour of the name column to sorting on namespace rather than class name.  This also makes the name column wider.  I assume you removed this functionality due to either/both of these reasons.

```
// simplify name
var lastIndexOfDotInName = className.LastIndexOf('.');
if (lastIndexOfDotInName != -1) @class["name"] = className.Substring(lastIndexOfDotInName).Trim('.');
```
```
coverage-info div.customizebox div:nth-child(2) {{ opacity:0;font-size:1px;height:1px;padding:0;border:0;margin:0 }}
coverage-info div.customizebox div:nth-child(2) * {{ opacity:0;font-size:1px;height:1px;padding:0;border:0;margin:0 }}
```

How do you want to proceed ?
a) Revert
b) Add an option
c) Wait until we have a custom report where we have control of the display and the sorting

**Comment by FortuneN** [comment]
I removed to simplify.
You can remove that code.

**Comment by tonyhallett** [comment]
Latest release has grouping by namespace.  This can be turned off with option NamespacedClasses.

Note that in some themes the range input is not legible ( blue or light ? ).  This will be updated tomorrow.
