### ISSUE TITLE
IF condition is marked with green color even when it's covered partially

### ISSUE THREAD

**Issue by smigielns** [FortuneN/FineCodeCoverage#194]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 1.1.141

### Description
`if` condition is marked with green color even when it's covered partially only.
The problem occurs only when the condition is always `true`.
When the condition is always `false` then it's marked with orange color.

### Steps to recreate
Test code
``` csharp
[TestCase(true, 1)]
public void IF_checker(bool condition, int expected)
{
    var result = _mapper.Test(condition);

    result.Should().Be(expected);
}
```

Implementation
``` csharp
public int Test(bool condition)
{
    var result = 0;
    if (condition)
    {
        result = 1;
    }
    return result;
}
```

### Current behavior
![obraz](https://user-images.githubusercontent.com/16755569/140339419-882a047a-ba63-4608-b30d-0ee43219fa16.png)

### Expected behavior
The line that contains `if` statement should be marked with orange color.

**Comment by tonyhallett** [comment]
Related to https://github.com/coverlet-coverage/coverlet/issues/1028 ?

**Comment by tonyhallett** [comment]
Is this a .Net Framework project ?

**Comment by smigielns** [comment]
It is a .NET Core 3.1 project.

**Comment by tonyhallett** [comment]
Then this is coverlet behaviour I have created an issue for.  Perhaps you can add to that issue.
