### ISSUE TITLE
Excluding test projects and specific files is not working as expected

### ISSUE THREAD

**Issue by burgerm** [FortuneN/FineCodeCoverage#195]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.141

### Description
When I try to exclude test coverage of files from a project by adding the example below to the .csproj file, they are NOT excluded.

```
<PropertyGroup Label="FineCodeCoverage">
    <ExcludeByFile>
      Context/AnalysisOriented/*.cs
      Context/PatientOriented/*.cs
      **/LmsAnalysisDbContext.cs
      **/LmsPatientDbContext.cs
    </ExcludeByFile>
</PropertyGroup>
```

Since the files are generated by Entity Framework  they make a mess of the coverage stats.
I expect the files to be excluded from coverage analysis.

Besides that I have the global option 'IncludeTestAssembly' set on False. But it still shows 2 test projects.
Even when I add the below example to the test project file.

```
<PropertyGroup Label="FineCodeCoverage">
    <Enabled>False</Enabled>
</PropertyGroup>
```

I expect the test project to be excluded from the coverage analysis.

Edit: I managed to exclude the testprojects by adding the below example to the project files:

```
<PropertyGroup>
    <FCCExcludeFromCodeCoverage/>
</PropertyGroup>
```

But I prefer NOT to apply the [ExcludeFromCodeCoverage] to all the generated files, since that is a lot of work and it doesn't feel right to include attributes for testcoverage to productioncode.

### Sidenote
The tool has a lot of potential, but the configuration of what to include/exclude could perhaps be a bit more monkey proof ;)

Keep up the good job!

**Comment by tonyhallett** [comment]
On the same simple .Net Core solution ExcludeByFile does work if `**/fileToExclude.cs`

I do not know how coverlet works in this regards.  Note that fine code coverage copies your dlls into a sub folder so this may have a bearing ?

![image](https://user-images.githubusercontent.com/11292998/140946794-aab6da25-ecdf-4240-9e43-ae821543da8b.png)

**Comment by tonyhallett** [comment]
This is how I think coverlet ( which will be used if .NET Core ) works, it excludes methods from instrumentation based on source file info.

ExcludedFiles becomes ExcludedSourceFiles
https://github.com/coverlet-coverage/coverlet/blob/32c57d61a278d6099e7984e96f589b79a91448dc/src/coverlet.core/Instrumentation/Instrumenter.cs#L65
```
// Instrumenter ctor
_excludedFilesHelper = new ExcludedFilesHelper(parameters.ExcludedSourceFiles, logger);
```
https://github.com/coverlet-coverage/coverlet/blob/32c57d61a278d6099e7984e96f589b79a91448dc/src/coverlet.core/Instrumentation/Instrumenter.cs#L503
```
        private void InstrumentMethod(MethodDefinition method)
        {
            var sourceFile = method.DebugInformation.SequencePoints.Select(s => _sourceRootTranslator.ResolveFilePath(s.Document.Url)).FirstOrDefault();
            if (!string.IsNullOrEmpty(sourceFile) && _excludedFilesHelper.Exclude(sourceFile))
            {
                if (!(_excludedSourceFiles ??= new List<string>()).Contains(sourceFile))
                {
                    _excludedSourceFiles.Add(sourceFile);
                }
                return;
            }
            //...................
        }
```
FCC copies the pdb and a file called CoverletSourceRootsMapping used by the [_sourceRootTranslator](https://github.com/coverlet-coverage/coverlet/blob/32c57d61a278d6099e7984e96f589b79a91448dc/src/coverlet.core/Helpers/SourceRootTranslator.cs#L75) so the original information is retained regardless of the copying to a sub folder.

```
    internal class ExcludedFilesHelper
    {
        Matcher _matcher;

        public ExcludedFilesHelper(string[] excludes, ILogger logger)
        {
            if (excludes != null && excludes.Length > 0)
            {
                _matcher = new Matcher();
                foreach (var excludeRule in excludes)
                {
                    if (excludeRule is null)
                    {
                        continue;
                    }
                    _matcher.AddInclude(Path.IsPathRooted(excludeRule) ? excludeRule.Substring(Path.GetPathRoot(excludeRule).Length) : excludeRule);
                }
            }
        }

        public bool Exclude(string sourceFile)
        {
            if (_matcher is null || sourceFile is null)
                return false;

            // We strip out drive because it doesn't work with globbing
            return _matcher.Match(Path.IsPathRooted(sourceFile) ? sourceFile.Substring(Path.GetPathRoot(sourceFile).Length) : sourceFile).HasMatches;
        }
    }
```

[Matcher](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing.matcher?view=dotnet-plat-ext-5.0)

If you prefix each of your soure file exclusions with ** then you should be ok ?

Perhaps there are some .g.cs files that you also need to exclude ?

**Comment by burgerm** [comment]
@tonyhallett : Thank you very much for your feedback. 
The configuration for excluding entire projects works great by adding:
```
<PropertyGroup>
    <FCCExcludeFromCodeCoverage/>
</PropertyGroup>
```
So that issue is solved.

I tried adding ** for all the paths of files I want to exclude, but the results stay the same. It seems the specific files are not picked up for exlusion.
I added screenshots of the files I try to exclude:
![image](https://user-images.githubusercontent.com/2082421/141083160-f89478aa-90d3-4179-aa9b-4c3549907fe8.png)

![image](https://user-images.githubusercontent.com/2082421/141086689-d689f266-6ba6-4e85-8bed-1ad3fcb49793.png)
  
As you see the files to exclude are not picked up.

Looking at the code you provided (and triple checking of the provided filepaths) I guess 'excludes' is null or empty so there is no new _matcher initiated? 

I did notice this code fragment:
```
var strValueArr = strValue.Split('\n', '\r').Where(x => !string.IsNullOrWhiteSpace(x)).Select(x => x.Trim()).ToArray();

if (!strValue.Any())
{
    continue;
}
```

Shouldn't this be:
```
if (!strValueArr.Any())
{
    continue;
}
```

**Comment by tonyhallett** [comment]
ExcludeByFile needs to go in your test project not the sut.
In a similar manner so too does
```
<PropertyGroup Label="FineCodeCoverage">
    <Enabled>False</Enabled>
</PropertyGroup>

```

**Comment by tonyhallett** [comment]
> Shouldn't this be:
```
if (!strValueArr.Any())
{
    continue;
}

```
I think that the existing code is unnecessary and so to would be your suggestion given the whitespace check.
```
if (string.IsNullOrWhiteSpace(strValue))
{
    continue;
}
```

**Comment by burgerm** [comment]
```
if (string.IsNullOrWhiteSpace(strValue))
{
    continue;
}
```
I agree!


> ExcludeByFile needs to go in your test project not the sut.

This doesn't make sense to me. I already excluded the test projects themselves. 
I need to have files excluded from the productioncode which are generated by Entity Framework. 
They don't end on *.g.cs. So unfortunately I can't use that oneliner.
If there is no other solution I can contact my productowner to see if we can make changes to generate these files this way in the future. But tinkering with EFCore is pretty tricky, so I'm not really a fan of that idea.

But .... I noticed that when I include the excludes in the option menu it works!
![image](https://user-images.githubusercontent.com/2082421/141109088-5a5559c5-3f86-442a-aac7-440e800f5b7f.png)

So that's nice. But the disadvantage is is that those settings aren't added to the solution so every developer has to mimic these settings and update them if the situation changes.

i.m.o. It would be very usefull if we can add a .FCCignore file to a solution in the way .gitignore works.

BTW. Is there a way to refresh Fine Code Coverage to get an updated result table after I made changes to project files?
At the moment if I change a file I notice some background processes start. But I only get definitive changes in Fine Code Coverage if I rerun all my tests and wait until alle background processes are completed (~ 5-10 minutes ...).

Thank you very much for the help!

**Comment by tonyhallett** [comment]
> ExcludeByFile needs to go in your test project not the sut.

> This doesn't make sense to me.

So are you saying that you think that this test specific instruction should be in the project file of your production code ? This is something that you were against earlier

> But I prefer NOT to apply the [ExcludeFromCodeCoverage] to all the generated files, since that is a lot of work and it doesn't feel right to include attributes for testcoverage to productioncode.


> I already excluded the test projects themselves.

Not sure what you mean by that.  There is not showing coverage of your test code and not running coverage for a test project that you run tests for in test explorer.

> I need to have files excluded from the productioncode which are generated by Entity Framework.

Perhaps you could provide details of how and what is being generated by Entity Framework.

> i.m.o. It would be very usefull if we can add a .FCCignore file to a solution in the way .gitignore works.

Agree with that.

> BTW. Is there a way to refresh Fine Code Coverage to get an updated result table after I made changes to project files?
At the moment if I change a file I notice some background processes start. But I only get definitive changes in Fine Code Coverage if I rerun all my tests and wait until alle background processes are completed (~ 5-10 minutes ...).

FCC does not do anything until your run tests.  If you make changes to your production code then tests have to be rerun.  Are you suggesting that FCC watch your solution and try to determine which test projects are effected by the code change and immediately rerun them and merge the results with the existing results ?

**Comment by burgerm** [comment]
> So are you saying that you think that this test specific instruction should be in the project file of your production code ? This is something that you were against earlier

The project already exists, so changes to the project file (.csproj) is no problem. But we use a database first approach and use Entity Framework for scaffolding of the database which leads to a lot of generated files within the existing project. We do this pretty frequently. So if we have to add the [ExcludeFromCodeCoverage] attribute to every generated file this is quite tedious. 
The output of the scaffolding is always in the same folderstructure.
Simply adding the below node to the .csproj file would be very nice since then it's automatically shared by all developers, since the .csproj is part of the solution in our git repository. But this doesn't seem to work on my sytem.

```
<PropertyGroup Label="FineCodeCoverage">
    <ExcludeByFile>
      Context/AnalysisOriented/*.cs
      Context/PatientOriented/*.cs
      **/LmsAnalysisDbContext.cs
      **/LmsPatientDbContext.cs
    </ExcludeByFile>
</PropertyGroup>
```
Or even better  the addition of a .FCCignore file to a solution in the way .gitignore works so it's shared by all developers as well.

> Not sure what you mean by that. There is not showing coverage of your test code and not running coverage for a test project that you run tests for in test explorer.

Because I already excluded those projects with the proper flag in the test project files:
```
<PropertyGroup>
    <FCCExcludeFromCodeCoverage/>
</PropertyGroup>
```
So this is no issue anymore (for me atleast).


> FCC does not do anything until your run tests. If you make changes to your production code then tests have to be rerun. Are you suggesting that FCC watch your solution and try to determine which test projects are effected by the code change and immediately rerun them and merge the results with the existing results ?

I ment a refresh option which uses the last testrun output which could be usefull if you were tinkering with the configuration of FCC, just like I'm doing now ;) There are no code changes only configuration changes.

What you are suggestion would be supercool but I think most VS users won't like to wait even longer on the background processes of intellisense and running analyzers to complete :-)

But ... all of my issues are pretty much solved. For now I'll give instructions to my fellow developers how to configure FCC options in VS and I'll wait for the 'Read excluded files from .FCCignore file' feature =D

Thank you very much for the support of this nice VS extension !

**Comment by tonyhallett** [comment]
> this doesn't seem to work on my sytem.

Because it needs to go in the test project ! 

If you have multiple test projects that reference the same project that you want to ignore some files from then this would need to be duplicated.

> I ment a refresh option which uses the last testrun output which could be usefull if you were tinkering with the configuration of FCC, just like I'm doing now ;) There are no code changes only configuration changes.

Let me get this right.  
a) You run tests and get test results / editor highlighting
b) Configure FCC, re-run tests and get test results / editor highlighting
c) You don't like what you just did
d) Press a button and revert to a ?

**Comment by burgerm** [comment]
> If you have multiple test projects that reference the same project that you want to ignore some files from then this would need to be duplicated.

Ahhh, tnx, that makes sense. I only tried it by adding it to the one test project. I'll give feedback on your suggestion soon. 

> Let me get this right.
> a) You run tests and get test results / editor highlighting
> b) Configure FCC, re-run tests and get test results / editor highlighting
> c) You don't like what you just did
> d) Press a button and revert to a ?

I ment:
a) You run tests and get test results / editor highlighting
b) Configure FCC, press 'Refresh' and get test results / editor highlighting based on the performed last run tests.

**Comment by tonyhallett** [comment]
> b) Configure FCC, press 'Refresh' and get test results / editor highlighting based on the performed last run tests.

You mean run the same tests again but with the latest configuration ?

**Comment by burgerm** [comment]
> You mean run the same tests again but with the latest configuration ?

No, I prefer NOT to run the tests again but use the last runned tests when I press on a refresh button in the FCC extension. So I can quickly see what the effect is  when I changed the configuration of FCC (preverably only within solution bound files -> .csproj files). 

> > If you have multiple test projects that reference the same project that you want to ignore some files from then this would need to be duplicated.
> 
> Ahhh, tnx, that makes sense. I only tried it by adding it to the one test project. I'll give feedback on your suggestion soon.

This seems to work. Great! Thank you!

**Comment by tonyhallett** [comment]
a) You run tests and get test results / editor highlighting
b) Configure FCC, press Refresh - coverage process runs based upon the the last test projects that were used ?

Note that there is this option

> RunInParallel					   By default tests run and then coverage is performed.  Set to true to run coverage immediately

**Comment by burgerm** [comment]
Thank you. I'm glad it now works as I would like it to work.

Good luck with the development and support!
