### ISSUE TITLE
Support branch coverage

### ISSUE THREAD

**Issue by dozer75** [FortuneN/FineCodeCoverage#2]
### Installed product versions
- Visual Studio: 2019 Community 16.7.2
- This extension: 1.0.39

### Description
Please use branch coverage instead of line coverage to indicate the code coverage.

While line coverage is a start, it's also important to show if a line is only partial covered (branch coverage). This is especially important in multi-conditional statements where it may be difficult to see if all parts of a statement is covered.

For example, using https://github.com/danielpalme/ReportGenerator it shows like this:
![image](https://user-images.githubusercontent.com/7486163/92304519-01e6a800-ef7f-11ea-89b8-3bb004a13189.png)

I don't expect the green/red combination indicator, but at least the tag should be yellow (see expected behaviour).

I like the intention of this tool having it integrated like this in Visual Studio, but this is a quite big limitation to actual code coverage due to this.

### Steps to recreate

1. Clone the https://github.com/dozer75/BranchCoverageDemo repo.
2. Open it in Visual Studio and run tests

### Current behavior
After recreating the issue, verify that Config.cs:12 is marked green

### Expected behavior
The Config.cs:12 should have been marked yellow to indicate that it is partially covered (It would have been nice to know exactly how many of the branches that was covered (tool tip on the color?). Se screen dump from the report generator for example from that code coverage generator.

**Comment by dozer75** [comment]
The coloring works, nice.. I see in the commits, that there is added a tooltip, but I can't get any tooltip. But the coloring helps a lot :)

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
