### ISSUE TITLE
FineCodeCoverage: exception when generating report

### ISSUE THREAD

**Issue by basilfx** [FortuneN/FineCodeCoverage#20]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.10

### Description
Replace this text with a short description

### Steps to recreate
1. Install extension
2. Run on a .NET Core 3.1 project
3. Observe that it does not work.

### Current behavior
FineCodeCoverage does not work, and throws an exception.

```
Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Ensure Work Folder Exists (Redacted.Converter.IntegrationTests)

Fine Code Coverage : Synchronize Output Files To Work Folder (Redacted.Converter.IntegrationTests)

Fine Code Coverage : Run Coverage Tool (Redacted.Converter.IntegrationTests)

Fine Code Coverage : Coverlet Run (Redacted.Converter.IntegrationTests) Arguments 
"Z:\Projects\Redacted.Converter.IntegrationTests\bin\Debug\fine-code-coverage\Redacted.Converter.IntegrationTests.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--include-test-assembly
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
--output "Z:\Projects\Redacted.Converter.IntegrationTests\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml"
--targetargs "test  ""Z:\Projects\Redacted.Converter.IntegrationTests\bin\Debug\fine-code-coverage\Redacted.Converter.IntegrationTests.dll"" --nologo --blame --results-directory ""Z:\Projects\Redacted.Converter.IntegrationTests\bin\Debug\fine-code-coverage\_outputfolder"" --diag ""Z:\Projects\Redacted.Converter.IntegrationTests\bin\Debug\fine-code-coverage\_outputfolder/diagnostics.log""  "

Fine Code Coverage : Coverlet Run (Redacted.Converter.IntegrationTests)

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:Z:\Projects\Redacted.Converter.IntegrationTests\bin\Debug\fine-code-coverage\_outputfolder"
"-reports:Z:\Projects\Redacted.Converter.IntegrationTests\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : Error
System.Exception
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<RunReportGenerator>g__run|22_1(String outputReportType, String inputReports, <>c__DisplayClass22_0& ) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 217
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.RunReportGenerator(IEnumerable`1 coverOutputFiles, Boolean darkMode, String& unifiedHtmlFile, String& unifiedXmlFile, Boolean throwError) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 228
   at FineCodeCoverage.Engine.FCCEngine.ReloadCoverage(IEnumerable`1 projects, Boolean darkMode) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 453
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<>c__DisplayClass21_0.<OperationState_StateChanged>b__0() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscoverer.cs:line 156

Fine Code Coverage : ================================== ERROR ==================================
```

### Expected behavior
FineCodeCoverage works.

### Side Notes
I tried to create a demonstration project from a project where FineCodeCoverage did not work, but after removing some source code and projects, it suddenly works. Unfortunately, I cannot share the original project, but I did start investigating.

Two things I observe:
* The output folder is empty ('bin\Debug\fine-code-coverage\_outputfolder')
* I don't see a Coverlet results table in the debug log.

I tried to run Coverlet.Console directly with the exact same arguments, and I see that it crashes:

```
The library 'hostpolicy.dll' required to execute the application was not found in ...
```

I'll investigate further, but it seems that FineCodeCoverage doesn't detect that target is crashing.

**Comment by basilfx** [comment]
Seems to be a similar error as Abubakar Mehmood reported [here](https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#qna).

**Comment by FortuneN** [comment]
I agree, it seems to be the same issue.
Thanks for the side notes; it's a start.

Please attach a repro when you can successfully isolate the problem (i will try do the same on my end).
I would like to resolve this ASAP.

**Comment by FortuneN** [comment]
Any luck?

**Comment by basilfx** [comment]
Yes and no.

The project I initially tested FineCodeCoverage on now works. I don't recall my steps exactly, but I am 90% sure it had to do with the target framework settings and/or output type. It's a solution that contains two projects, of which project A build a NuGet packages out of the published binaries of project B. That caused some problems with binaries, runtimes and missing *.runtime.json files (https://stackoverflow.com/questions/38085430/the-library-hostpolicy-dll-was-not-found, https://stackoverflow.com/questions/62721921/how-to-generate-runtimeconfig-json-for-dependency-with-dotnet-publish)

I don't think that the above problem is the reason for the exception. My hypothesis is that this exception occurs whenever Coverlet is unable to run, therefore not generating a coverage report, and FineCodeCoverage crashes because the report isn't there. That hypothesis is supported by the fact that I don't see a Coverlat coverage table in the console logging, and that the output directory is empty.

I'll keep an eye open for this problem, but currently I don't have the time to dive into this deeper.

**Comment by FortuneN** [comment]
Please try this and let me know
[Fine Code Coverage v1.1.14.zip](https://github.com/FortuneN/FineCodeCoverage/files/5549762/Fine.Code.Coverage.v1.1.14.zip)
-> This is not a public release

**Comment by FortuneN** [comment]
I have release the update.
Please try latest and let me know.

**Comment by FortuneN** [comment]
Closed for lack of activity
