### ISSUE TITLE
how can I see which metod has been covered buy unit test or uncovered in .cs file ?

### ISSUE THREAD

**Issue by nsentuna** [FortuneN/FineCodeCoverage#21]
### Installed product versions
- Visual Studio: [2019 Professional]

### Description
how can I see which metod has been covered buy unit test or uncovered in .cs file ?

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Explain what it should be doing after it's fixed.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- [Please consider giving this project a star and become one of the stagazers](https://github.com/FortuneN/FineCodeCoverage/stargazers) 
- [Please consider buying me a beer](https://paypal.me/FortuneNgwenya)

**Comment by FortuneN** [comment]
At the moment, the output view shows Assemblies and Classes.
Opening the class (.cs) file shows coverage line by line (See Image below).
Are you asking for methods t be shown in the output view?

![simple guide](https://user-images.githubusercontent.com/5636175/98804078-5cd4c980-241e-11eb-9fd2-388ef88b9dc3.png)

**Comment by nsentuna** [comment]
thanks a lot, I saw it now. 👍🙏

**Comment by nsentuna** [comment]
thanks a lot, I saw it now. 👍🙏

**Comment by FortuneN** [comment]
Please post a review

https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo

**Comment by jyotint** [comment]
Hi, 

"Opening the class (.cs) file shows coverage line by line (See Image below)." - Excerpt from thread by FortuneN commented on Nov 11, 2020.

This feature does not work most of the time for my setup. I restarted Visual Studio (v16.8.5), tried various themes, rerun the unit tests, rebooted system after FCC extension (v1.1.116) installation, but no effect.

Could you please suggest the way forward to resolve this?

Regards,
Jyotindra.
