### ISSUE TITLE
Integrate with Visual Studio 2022

### ISSUE THREAD

**Issue by lindsay-spencer** [FortuneN/FineCodeCoverage#218]
### Installed product versions
- Visual Studio: 2022 (all)
- This extension: any

### Description
I would like to use this extension with VS 2022

**Comment by tonyhallett** [comment]
Are you having trouble with [this](https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage2022) then ?

**Comment by lindsay-spencer** [comment]
Nope, I'm not having trouble with it, I just couldn't find it. Thanks for
the link.
