### ISSUE TITLE
about [ExcludeFromCodeCoverage] 

### ISSUE THREAD

**Issue by nsentuna** [FortuneN/FineCodeCoverage#22]
despite the class has attribute [ExcludeFromCodeCoverage]

the fine code coverage calculated that class as uncoverage. I tried to add screen shot below I 'm not sure.

![image](https://user-images.githubusercontent.com/21196564/98803460-d2906380-2425-11eb-9fc4-1958ccd6c74b.png)
![fineCodeCoverage](https://user-images.githubusercontent.com/21196564/98803522-f5227c80-2425-11eb-8b06-18d58d3bdbbe.png)

**Comment by nsentuna** [comment]
how about this my issues about [ExcludeFromCodeCoverage]

**Comment by FortuneN** [comment]
Your project is .net framework, correct?
(As opposed to .net core)

**Comment by nsentuna** [comment]
Yes sir .net framework 4.6.1

**Comment by FortuneN** [comment]
Please try the latest version (1.1.11+) version and let me know

Thanks for posting the issue

**Comment by nsentuna** [comment]
thanks a lot it is perfect, after installed version 1.1.11 , removed all class has  [ExcludeFromCodeCoverage] attribute.

**Comment by FortuneN** [comment]
Please post a review

https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
