### ISSUE TITLE
No coverage information when running unit tests for enumerations

### ISSUE THREAD

**Issue by xstrahl-mrankl** [FortuneN/FineCodeCoverage#220]
### Installed product versions
- Visual Studio: VS 2022 (64-bit)
- This extension: 1.1.154

### Description
I am working on software as medical product. Unit tests are an essential key element. Your tool is great.
However, it does not recognize testing of enumerations. It even does not detect a class that holds only enumerations.

`
    Public NotInheritable Class XSTP2_Enumerations

        Public Enum AutoRunInstruction

            <XmlEnum("0")>
            NoDontRun = 0

            <XmlEnum("1")>
            YesRun = 1

        End Enum
 
   End Class
`

I can successfully run unit tests for the Enum.
But FCC does not show any result/coverage for that class. There are no green/red lines indicating coverage.

![image](https://user-images.githubusercontent.com/44357151/149166331-c2fe155e-1817-4d9b-b686-db8b9951e8a3.png)

**Comment by tonyhallett** [comment]
> However, it does not recognize testing of enumerations. It even does not detect a class that holds only enumerations.

FCC runs and reports coverage from OpenCover or Coverlet.  

> OpenCover is a code coverage tool for .NET 2 and above (Windows OSs only - no MONO)*, with support for 32 and 64 processes and covers both branch and sequence points.

> Before Tests Run
Locates the unit test assembly and selects all the referenced assemblies that have PDBs.
Instruments the selected assemblies by inserting code to record sequence point hits to a temporary file.

Enumerations are definitions and are not coverable lines.  Even as a class definition with just an inner enumeration there are zero coverable lines.
