### ISSUE TITLE
User completely fails to install NUnit Test Adapter

### ISSUE THREAD

**Issue by paul-t-keyser** [FortuneN/FineCodeCoverage#221]
### Installed product versions
- Visual Studio: Studio Professional 2019, Version 16.4.7

- This extension: 1.1.154

### Description
Attempted install from the marketplace web-page (https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage) and then (after uninstall) from the Extension-Manager within DevStudio. 

### Steps to recreate
1. Install "Fine"
2. Run NUnit tests
3. See no annotations

### Current behavior
No coverage annotations after running NUnit tests

### Expected behavior
Coverage annotations on various files that I know are called by the NUnit tests

### Side Notes
- It helps to attach a repro solution so I can test the fix --> can you post a .SLN file and associated code-files that I could import to DevStudio and see them working? This would at least prove that my install of DevStudio is not broken.

- Attached screen shot of options dialog, which is radically different from the one in your video.
<img width="400" alt="FineCodeCover -- defective dialog" src="https://user-images.githubusercontent.com/88453960/150608575-00c07dd6-f82e-4a2b-b668-dc2b2250d0fd.png">

- Attached screen shot of the "References" of the unit tests "Test.FI"
<img width="173" alt="dotCover -- references under test in Test FI" src="https://user-images.githubusercontent.com/88453960/150608740-5266f781-b8f0-4603-ab1e-56826d6c947a.png">

- It helps to attach the log  --> two files attached:
[FineCodeCoverage -- Test.FI -- Build.log](https://github.com/FortuneN/FineCodeCoverage/files/7916956/FineCodeCoverage.--.Test.FI.--.Build.log)
[FineCodeCoverage -- Test.FI -- Test.log](https://github.com/FortuneN/FineCodeCoverage/files/7916957/FineCodeCoverage.--.Test.FI.--.Test.log)

**Comment by tonyhallett** [comment]
> Attached screen shot of options dialog, which is radically different from the one in your video.

That is not the options for Fine Code Coverage.

![image](https://user-images.githubusercontent.com/11292998/150632079-b62b62a0-eea6-481a-8bb3-acc975495e63.png)

The Test.log file informs you of the problem

> Test project Test.FI does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.

**Comment by tonyhallett** [comment]
Perhaps you are using the NUnit Test Adapter extension which is unsupported.

You may also need to update your version of visual studio.
