### ISSUE TITLE
Include a feature to ignore classes generated by the grpc protobuf compiler

### ISSUE THREAD

**Issue by rkreisel** [FortuneN/FineCodeCoverage#223]
### Installed product versions
- Visual Studio: 2022
- This extension: 1.1.154

### Description
Add a feature to ignore the classes generated by the grpc protobuf compiler. (I have tried the "ignore autogenerated" option but it does not work.)

### Steps to recreate
1. Create an application with a grpc Proto file
2. compile the app (note the generated files in obj/debug/net6.0/Proto)
3. add a unit test project and write at least one test
4. execute test(s)
5. note that FCC includes the generated code from the protobuf compiler

### Current behavior
Note the if I add **\obj\Debug\net6.0\Proto\*.* to the "exclude by file "array (via Options|Find Code Coverage|General|ExlcudeByFile, FCC does exclude those files.
I need to be able to exclude those files via the csproj file. (so that it will be checked into ADO)

### Expected behavior
files generated by the protobuf compiler should be excluded

###Side note
I may simply not understand how to specify setting in the csproj file, but nothing I add there seems  to make any difference.

**Comment by jasells** [comment]
Do the auto gen files end in ".g.cs"?  I have dealt with protoBuff generated files, and the .g.cs extension was key to ignoring them in git and style cop.

**Comment by tonyhallett** [comment]
Are you putting your exclusions in the test project in a PropertyGroup with Label FineCodeCoverage ?
