### ISSUE TITLE
tools->options->fcc menu doesn't expand to edit options

### ISSUE THREAD

**Issue by jasells** [FortuneN/FineCodeCoverage#226]
### Installed product versions
- Visual Studio: [ 2019 Professional/Enterprise]
- This extension: [1.1.154]

### Description
Fine Code Coverage options are not accessible via menu tools->options->fcc

### Steps to recreate
1. Run tests (i have > 500 in 3-4 projects, XUnit).  Tests run, results show.
2. navigate tools->options
3. FCC item will not expand (sometimes), gives spinny-circle busy cursor when clicked
4. close all instance of VS to clear this state, or open a new VS instance with no code, and tools->options->fcc menu is accessible in new instance

### Current behavior
gives spinny-circle busy cursor when clicked

### Expected behavior
tools->options->fcc menu is accessible at all times

**Comment by tonyhallett** [comment]
Just in case it is pertinent, please can you provide further information.

FCC has two instantiation paths dependent upon if visual studio is started with the Fine Code Coverage tool window open.

Is your project open source ?

**Comment by tonyhallett** [comment]
Also could you have the FCC Output Window Pane open and provide the progress state when this occurs.

**Comment by jasells** [comment]
> Also could you have the FCC Output Window Pane open and provide the progress state when this occurs.

Sure thing!

**Comment by tonyhallett** [comment]
This might not be anything related to FCC.  I had a busy indicator with Tools / Options for something else - cannot remember which one it was but I think it was built in and not from any extension.

**Comment by tonyhallett** [comment]
> FCC item will not expand (sometimes), gives spinny-circle busy cursor when clicked
close all instance of VS to clear this state,

How long had you been waiting before you closed VS ?

**Comment by jasells** [comment]
> > FCC item will not expand (sometimes), gives spinny-circle busy cursor when clicked
> > close all instance of VS to clear this state,
> 
> How long had you been waiting before you closed VS ?

hours

**Comment by tonyhallett** [comment]
@jasells 
Still ongoing ?

**Comment by jasells** [comment]
I haven't seen the issue after a few restarts post-install of extension, so seems it may have been an install/setup thing, or perhaps loading my large solution (> 20 projects)?  I will check with team and see if any of them have seen it since, I know at least one other member saw it too, but right after install.
