### ISSUE TITLE
Clicking on "Cyclomatic complexity" navigates to wikipedia with no way to go back

### ISSUE THREAD

**Issue by MarNicGit** [FortuneN/FineCodeCoverage#237]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.161

### Description
When clicking on the little (i) symbol next to the column header "Cyclomatic complexity", the extension navigates to the Wikipedia article explaining what it is, but with no way to return to the coverage results. The only way to return to the results is by clearing the entire UI and waiting for the coverage to run again.

### Steps to recreate
1. Open any solution with risk hotspots
2. Go to FCC
3. Navigate to the "Risk Hotspots" tab
4. click this little icon: 
![image](https://user-images.githubusercontent.com/47538428/156001117-9714e22b-2ce1-403a-824f-af68ca32b5e0.png)

### Current behavior
The wikipedia article opens inside of the panel itself and the only way to go back to results is by clearing the UI and waiting for coverage to get re-calculated.

### Expected behavior
The wikipedia opens in an external browser instead.

### Side Notes
A screenshot that shows there is no way to return to the results:
![image](https://user-images.githubusercontent.com/47538428/156001502-a5562e91-7d77-4dee-932e-ba80385658fe.png)

**Comment by tonyhallett** [comment]
[Done ](https://github.com/FortuneN/FineCodeCoverage/pull/238)- marketplace will update shortly
