### ISSUE TITLE
Enabling option crashes Visual Studio

### ISSUE THREAD

**Issue by bstordrup** [FortuneN/FineCodeCoverage#239]
### Installed product versions
- Visual Studio: [2022 Professional (17.1.0)]
- This extension: [1.1.162 (taken from Github)]

### Description
If I set the CoverageColoursFromFontsAndColours to true in the settings, then Visual Studio crashes when I click on the class being tested after running the tests and then look at the coverage in the Coverage View.

### Steps to recreate
1. Set CoverageColoursFromFontsAndColours to true (one time)
2. Run a set of tests
3. Look at the code coverage
4. Activate the window containing a class being tested in the tests
5. Visual Studio becomes unresponsive, and after a while, it crashes silently.

### Current behavior
Visual Studio crashes

### Expected behavior
Should open the class file without crashing

### Side Notes
- Not sure if it is related, but the solution containing the test project, contains 152 projects being a mix of Native C++, VB.Net and C# projects (both .NET 4x, .netstandard2.0, .netcore* and .net*).
- The project containing the classes to test is targeting .netstandard2.0.
- The test project is targeting .net6.
- Tests are implemented with xunit.

**Comment by tonyhallett** [comment]
@bstordrup 
Marketplace will be updated when this github action finished in approximately 5 minutes.
https://github.com/FortuneN/FineCodeCoverage/actions/runs/1921577535

Please let me know if this resolves the issue.

Thanks

**Comment by tonyhallett** [comment]
@bstordrup 
Action failed no internet connection for publishing.
Running again hopefully that will be ok https://github.com/FortuneN/FineCodeCoverage/runs/5389900469?check_suite_focus=true

**Comment by tonyhallett** [comment]
Available now

**Comment by tonyhallett** [comment]
And does not throw on VS 2019

**Comment by tonyhallett** [comment]
https://developercommunity.visualstudio.com/t/fonts-and-colors-coverage-settings-available-in-vs/1683898

Will be fixed shortly.

**Comment by bstordrup** [comment]
Nice :-)

**Comment by bstordrup** [comment]
@tonyhallett, no, I do not have those settings in Fonts and Colors.
