### ISSUE TITLE
Support for 64 bit projects

### ISSUE THREAD

**Issue by NorbertWalasek** [FortuneN/FineCodeCoverage#24]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.10

### Description
For now 64 bit projects are not supported.
I analyzed your code and I found this line:
OpenCoverUtil.RunOpenCover line 162
opencoverSettings.Add($@" -register:path32 ");

It would be nice to distinguish 32bit and 64bit.
To solve it you can add new property to local (project) options.

Do you want to add support for 64bit projects?

**Comment by FortuneN** [comment]
Please try the latest version (1.1.11+) version and let me know

Note: I went the way of detecting the 'bitness' setting the '-register' value automatically; It is my wish to simplify usage as much as possible.

Thanks for posting the issue

**Comment by NorbertWalasek** [comment]
Works great, thanks :)

**Comment by FortuneN** [comment]
Please post a review

https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
