### ISSUE TITLE
EventHandler Leak in FineCodeCoverage.Impl.CoverageLineGlyphTagger 

### ISSUE THREAD

**Issue by calvinhsia** [FortuneN/FineCodeCoverage#248]
I'm on the Visual Studio team and have examined customer memory dumps and found that there seems to be a memory leak  in eventhandlers:

   FineCodeCoverage.Engine.UpdateMarginTagsDelegate  += FineCodeCoverage.Impl.CoverageLineGlyphTagger                                   

MultipleEventHandlers 
The Avg # of subscribers is  913. Some dumps have 2325.

Perhaps this is the code: https://github.com/FortuneN/FineCodeCoverage/blob/9d49f89155ef838693ba1e80643ea33c4a0aec69/SharedProject/Impl/CoverageLineGlyphTagger.cs#L22

**Comment by tonyhallett** [comment]
Thanks. Will look at in coming days.

**Comment by tonyhallett** [comment]
Agreed that that is the code preventing the CoverageLineGlyphTagger from being garbage collected.
I have written the code to rectify this and will commit once I have finished adding the ms code coverage feature - https://github.com/FortuneN/FineCodeCoverage/pull/245
