### ISSUE TITLE
Visual Studio is reporting an exception with the extension

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [FortuneN/FineCodeCoverage#25]
### Installed product versions
- Visual Studio: 2019 16.8.1
- This extension: 1.1.10

### Description
On loading Visual Studio a yellow bar appears beneath toolbar saying `System.Collections.Generic.KeyNotFoundException`

The activity log reports issues like:
```
<source>Editor or Editor Extension</source>
<description>System.Collections.Generic.KeyNotFoundException: key
   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetProperty(Object key)
   at FineCodeCoverage.Impl.Tagger`1.Microsoft.VisualStudio.Text.Tagging.ITagger&lt;T&gt;.GetTags(NormalizedSnapshotSpanCollection spans) in C:\projects\finecodecoverage\FineCodeCoverage\Impl\Tagger.cs:line 39
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__47.MoveNext()
</description>
```

### Steps to recreate
1. Load Visual Studi

### Current behavior
An exception is being thrown

### Expected behavior
No exception

### Side Notes
Attached below is a snippet of relevant parts of the activity log:
[ActivityLog.zip](https://github.com/FortuneN/FineCodeCoverage/files/5532903/ActivityLog.zip)

**Comment by FortuneN** [comment]
Please try the latest version (1.1.11+) version and let me know

Thanks for posting the issue

**Comment by SamuelJohnsonMedia** [comment]
Just tried 1.1.11 and it does the same.

**Comment by FortuneN** [comment]
Paste the output for me (i want to verify line numbers; they'll be different after the last update)

**Comment by SamuelJohnsonMedia** [comment]
```
  <entry>
    <record>703</record>
    <time>2020/11/13 16:26:58.067</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Collections.Generic.KeyNotFoundException: key&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetProperty(Object key)&#x000D;&#x000A;   at FineCodeCoverage.Impl.Tagger`1.Microsoft.VisualStudio.Text.Tagging.ITagger&lt;T&gt;.GetTags(NormalizedSnapshotSpanCollection spans) in C:\projects\finecodecoverage\FineCodeCoverage\Impl\Tagger.cs:line 41&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__47.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
  <entry>
    <record>704</record>
    <time>2020/11/13 16:26:58.123</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Collections.Generic.KeyNotFoundException: key&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.GetProperty(Object key)&#x000D;&#x000A;   at FineCodeCoverage.Impl.Tagger`1.Microsoft.VisualStudio.Text.Tagging.ITagger&lt;T&gt;.GetTags(NormalizedSnapshotSpanCollection spans) in C:\projects\finecodecoverage\FineCodeCoverage\Impl\Tagger.cs:line 41&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__47.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>

```

**Comment by FortuneN** [comment]
I am baffled.

Line 41 right now looks like this.

> try { endLineNumber = span.End.GetContainingLine().LineNumber + 1; } catch { }

There shouldn't an error of any kind coming from there.

Do you have any thoughts/suggestions?

**Comment by SamuelJohnsonMedia** [comment]
Just totally uninstalled and then downloaded and re-installed and same error on same line.

I cant see anything up with the line except perhaps trying to catch the specific `KeyNotFoundException` exception and perhaps move the line around to ensure that I am actually using the same built extension you think I am.

**Comment by FortuneN** [comment]
Fancy a hacking session?
https://meet.google.com/nyg-esjq-tnw?authuser=1&hl=en

**Comment by FortuneN** [comment]
Long short (based on time and effort that you can invest in this)
----------------------------------------------------------------------
- Clone the repo, run it and maybe see in debug mode where/how this blows up.
- Post results

**Comment by leistner** [comment]
I get a similar error with newest version.
Where does this absolute path come from, e.g. "C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs"?

> Fine Code Coverage : Error
> System.Exception
>    at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<RunReportGenerator>g__run|22_1(String outputReportType, String inputReports, <>c__DisplayClass22_0& ) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 217
>    at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.RunReportGenerator(IEnumerable`1 coverOutputFiles, Boolean darkMode, String& unifiedHtmlFile, String& unifiedXmlFile, Boolean throwError) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 228
>    at FineCodeCoverage.Engine.FCCEngine.ReloadCoverage(IEnumerable`1 projects, Boolean darkMode) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 453
>    at FineCodeCoverage.Impl.TestContainerDiscoverer.<>c__DisplayClass21_0.<OperationState_StateChanged>b__0() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscoverer.cs:line 157
> 
> Fine Code Coverage : ================================== ERROR ==================================

**Comment by leistner** [comment]
You find my project with this Fine Code Coverage issue here: [](https://github.com/leistner/Weighing-API)

**Comment by danpetitt** [comment]
@FortuneN how do you run/use it outside of the extension

**Comment by SamuelJohnsonMedia** [comment]
@FortuneN how do you run/use it outside of the extension

**Comment by FortuneN** [comment]
Install this
[Fine Code Coverage v1.1.14.zip](https://github.com/FortuneN/FineCodeCoverage/files/5550200/Fine.Code.Coverage.v1.1.14.zip)
It will print out the full command that i run behind the scenes
-> It's not publicly release yet

**Comment by FortuneN** [comment]
@leistner leistner

That is the source code file (and line) where the issue occurs
The source is in this repo (You can ignore the first part "C:\projects\")

**Comment by SamuelJohnsonMedia** [comment]
@FortuneN typically; the error has gone away for me ... I haven't done anything except a few reboots and win updates.

**Comment by leistner** [comment]
In my case MSBuildSDKsPath in PATH environment was targeting wrong SDK 2.1, changed it to SDK 3.1.
Now it works!

**Comment by FortuneN** [comment]
@leistner @SamuelJohnsonMedia Can i close?

**Comment by SamuelJohnsonMedia** [comment]
Can close as far as I am concerned

**Comment by menees** [comment]
Can you reopen this issue please? I'm still getting this error in VS 2019 16.8.1 using FineCodeCoverage 1.1.15. This error happens every time I open a .razor file in a Blazor WebAssembly project. I just generated a brand-new Blazor WebAssembly project and opened its Index.razor page.

The stack trace reports Impl\Tagger.cs:line 41, but the line number is slightly off due to Release build optimizations. That's a common, normal problem with stack trace line numbers in release builds. The actual error is from the code on line 43. When I open a .razor file, evidently the Tagger class can't get an ITextDocument property. If you change line 43 to use TryGetProperty instead of GetProperty, then you can safely and efficiently skip the rest of the tagger logic if you can't get a document property. For example:

```
if (span.Snapshot.TextBuffer.Properties.TryGetProperty(typeof(ITextDocument), out ITextDocument document))
{
	var coverageLines = FCCEngine.GetLines(document.FilePath, startLineNumber, endLineNumber);

	foreach (var coverageLine in coverageLines)
	{
		var tag = new GlyphTag(coverageLine);
		var tagSpan = new TagSpan<GlyphTag>(span, tag);
		var iTagSpan = tagSpan as ITagSpan<T>;
		result.Add(iTagSpan);
	}
}
```

**Comment by FortuneN** [comment]
@menees Thank you, Thank you, Thank you 👍 

I've made the change and pushed to the marketplace -> Version 1.1.16
https://github.com/FortuneN/FineCodeCoverage/blob/master/FineCodeCoverage/Impl/Tagger.cs

Let me know if we (finally) ready to lay this to rest

**Comment by menees** [comment]
Thank you so much! Version 1.1.16 fixed the problem for me. This issue can be closed. :-)
