### ISSUE TITLE
Request: Summary row containing average coverage percent

### ISSUE THREAD

**Issue by suleimanforever** [FortuneN/FineCodeCoverage#255]
### Installed product versions
- Fine Code Coverage
- 1.1.173

### Feature request
Is it possible to have the average coverage % for all projects that had any coverage (above 0%)?

### Steps to recreate
When reading the coverage report.

### Current behavior
Now it shows lines containing coverage info for each project.,

### Expected behavior
It would be nice if there was a summary row in the bottom of the list showing the averge coverage % for those that had any coverage.

### Side Notes
- Some projects are note supposed to have coverage like the test itself, so the ones that have 0% shouldn't be included when calculating the average coverage %.

**Comment by tonyhallett** [comment]
I believe that you are asking for what is currently "Line coverage" in the Summary table but for assemblies that have has some degree of coverage.

> Some projects are note supposed to have coverage like the test itself, so the ones that have 0% shouldn't be included when calculating the average coverage %.

If you exclude assemblies from coverage then the current "Line Coverage" provides the average value that you require.

( Also if you did exclude on 0% then you could be excluding a project that should have coverage from your results )
