### ISSUE TITLE
Configure -register value

### ISSUE THREAD

**Issue by xitaocrazy** [FortuneN/FineCodeCoverage#26]
### Installed product versions
- Visual Studio: [example 2019 Professional]
- This extension: [example 1.1.10]

### Description
When running in a .netFramework project using OpenCover is always used -register:path32, but sometimes this profiler doesn't works and we got an error like:

No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

### Steps to recreate
1. Create a project .netFramework
2. Set test project with Platform Targe = x64
3. Run the tests
4. Opencover could not generate the report

### Current behavior
The value to Opencover -register parameter is fixed in the code and when the target platform is not x86 or Any CPU the coverage is not reported

### Expected behavior
We should be able to configure the -register parameter (including setting an empty value), as we can do to include or exclude files.

### Side Notes
![image](https://user-images.githubusercontent.com/2092215/99022399-69057780-2541-11eb-8ff6-33eefa51042e.png)

![image](https://user-images.githubusercontent.com/2092215/99022428-7ae71a80-2541-11eb-9ebb-eb3b841a0296.png)

![image](https://user-images.githubusercontent.com/2092215/99022748-ffd23400-2541-11eb-86b6-9aeff5943aef.png)

**Comment by FortuneN** [comment]
Please try the latest version (1.1.11+) version and let me know

Note: I went the way of detecting the 'bitness' setting the '-register' value automatically; It is my wish to simplify usage as mush as possible.

Thanks for posting the issue

**Comment by xitaocrazy** [comment]
Hi @FortuneN , thank you very much for your attention, it was very fast, I'm really happy.

I have updated to the latest version and everything works like a charm,  was used -register:path64 as I wish, and it was automatic. 

Again, thank you very much, I will close the issue.

**Comment by FortuneN** [comment]
Please post a review

https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
