### ISSUE TITLE
Support windows snap layouts

### ISSUE THREAD

**Issue by viceice** [FortuneN/FineCodeCoverage#264]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.173

### Description
I've a  DQHD (5.120 x 1.440) display and I'm using the windows 11 snap layouts (and PowerToys FanzyZones) to arange my app windows.

### Steps to recreate
1. open FCC tool window
2. drag to undock
3. try to dock to a snap / fanzy zone

### Current behavior
I've undocked the FCC tool window, but i can't dock it to a snap / fancy zone.
I can only use the old windows 10 method (drag against left or right display side) to dock as a half with window.

A workaround is to drag one file editor to a new window, drag FCC as new tab to it and then close the file editor.
That window can use snap layouts natively.

### Expected behavior

Allow using normal windows 11 snap layouts.

### Side Notes
- https://docs.microsoft.com/en-us/windows/powertoys/fancyzones

**Comment by tonyhallett** [comment]
This is not FCC specific.  The behaviour is governed by visul studio.

Turn off "Floating tool windows always stay on top of the main window"
<img width="516" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/b93ace36-3e69-402e-aa98-6bdc612b4b06">
