### ISSUE TITLE
Feature Request: show which routes arent covered by a unit test

### ISSUE THREAD

**Issue by nics71** [FortuneN/FineCodeCoverage#265]
### Installed product versions
- Visual Studio: 2022 Professional (17.1.6)
- This extension: 1.1.73

Absolutely love this tool and is helping me achieve more and more code coverage each day. 

Not a bug but a feature request. In a block of code that has multiple conditions within an if block I see that not all routes are covered by a unit test. I add unit tests but still it shows uncovered conditions. Is there a way for the report to drill down into what conditions havent been covered by a unit test?

For instance, if I have 3 of 8 cases covered by unit tests can it show the 5 that havent been covered?

**Comment by tonyhallett** [comment]
So are you then asking that the table in the Coverage tab has additional nested rows.

e.g
Class1
  UncoveredMethod1
    Link to uncovered line 1 ( Display the code on the line )
    Link to uncovered line 2
  UncoveredMethod2
    Link to uncovered line 1

**Comment by nics71** [comment]
not as such. The request is that the table in the Coverage tab has additional nested rows to show the test not covered in case of multiple tests per line.

Take the example block of code
`if (valueA is null || (valueA is not null && classA?.valueB > 0))`

and I have tests that cover valueA but not classA or valueB then I'd like to see that unit tests weren't added for classA or valueB > 0

**Comment by tonyhallett** [comment]
Only in cases where there a multiple conditions on a single line and not all are covered ?

**Comment by tonyhallett** [comment]
If this was highlighted in some way in your code file would you still want it to appear in the report ?

**Comment by nics71** [comment]
either on the report or in some way in the code file. either would be great if at all possible

**Comment by tonyhallett** [comment]
I prefer in the code file.  I will look into it.  Might be a couple of weeks though.

**Comment by tonyhallett** [comment]
This information is not available from all the coverage tools.
Ms code coverage does not, OpenCover does and Coverlet can if you request in OpenCover format.

The real problem though is the mapping of the branch coverage ( IL ) to the source code. 

Given the method below that is only invoked with true.
```
    public class Class1
    {
        public string PartialCover(bool cover)
        {
            return cover ? "covered" : "uncovered";
        }
    }
```

The OpenCover output concerning the PartialCover method coverage
```
            <Method visited="true" cyclomaticComplexity="3" nPathComplexity="2" sequenceCoverage="100" branchCoverage="66.67" crapScore="3" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="3" visitedSequencePoints="3" numBranchPoints="3" visitedBranchPoints="2" sequenceCoverage="100" branchCoverage="66.67" maxCyclomaticComplexity="3" minCyclomaticComplexity="3" maxCrapScore="3" minCrapScore="3" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" />
              <MetadataToken>100663297</MetadataToken>
              <Name>System.String OpenCover.Class1::PartialCover(System.Boolean)</Name>
              <FileRef uid="3" />
              <SequencePoints>
                <SequencePoint vc="1" uspid="5" ordinal="0" offset="0" sl="12" sc="9" el="12" ec="10" bec="0" bev="0" fileid="3" />
                <SequencePoint vc="1" uspid="6" ordinal="1" offset="1" sl="13" sc="13" el="13" ec="52" bec="2" bev="1" fileid="3" />
                <SequencePoint vc="1" uspid="7" ordinal="2" offset="19" sl="14" sc="9" el="14" ec="10" bec="0" bev="0" fileid="3" />
              </SequencePoints>
              <BranchPoints>
                <BranchPoint vc="0" uspid="8" ordinal="0" offset="2" sl="13" path="0" offsetend="4" fileid="3" />
                <BranchPoint vc="1" uspid="9" ordinal="1" offset="2" sl="13" path="1" offsetend="11" fileid="3" />
              </BranchPoints>
              <MethodPoint xsi:type="SequencePoint" vc="1" uspid="5" ordinal="0" offset="0" sl="12" sc="9" el="12" ec="10" bec="0" bev="0" fileid="3" />
            </Method>
```


Il from reflector
[List of CIL instructions](https://en.wikipedia.org/wiki/List_of_CIL_instructions) 
```
.method public hidebysig instance string PartialCover(bool cover) cil managed
{
    .maxstack 1
    .locals init (
        [0] string str)
    L_0000: nop 
    L_0001: ldarg.1 
    L_0002: brtrue.s L_000b        ******************
    L_0004: ldstr "uncovered"      ------------------- 
    L_0009: br.s L_0010
    L_000b: ldstr "covered"
    L_0010: stloc.0 
    L_0011: br.s L_0013            -------------------
    L_0013: ldloc.0 
    L_0014: ret 
}
```

No doubt you can see how difficult / impossible it is to achieve.

The open source ReportGenerator that supplies the current html report you see in the Fine Code Coverage tool window does do nothing more than count this branch information https://github.com/danielpalme/ReportGenerator/blob/0b9e5461dcb168a8ec352b58491f3272785799fc/src/ReportGenerator.Core/Parser/OpenCoverParser.cs#L457

If you use ReportGenerator to show code annotations then you would see

![image](https://user-images.githubusercontent.com/11292998/170695325-f167c20d-de61-49bd-8d82-d377fb146a6c.png)
