### ISSUE TITLE
Code coverage results not visible in HTML 

### ISSUE THREAD

**Issue by astav2** [FortuneN/FineCodeCoverage#272]
### Installed product versions
- Visual Studio: 2019 enterprise
- This extension:latest

### Description
i have run "Analyze code coverage for All tests" in VS and got no output in coverages in FCC window
![image](https://user-images.githubusercontent.com/104415745/174082635-549c0dda-0b6a-45d5-8bc2-86676030e88d.png)
![image](https://user-images.githubusercontent.com/104415745/174082694-055b62f5-0139-4793-8edb-70c500b8062c.png)
![image](https://user-images.githubusercontent.com/104415745/174082720-6bbec722-2e62-47cc-9f6b-5966063fceae.png)

**Comment by tonyhallett** [comment]
That is not how FCC works.  Please read the readme.
