### ISSUE TITLE
Improve visibility on which states line up to which items

### ISSUE THREAD

**Issue by hauntingEcho** [FortuneN/FineCodeCoverage#274]
### Installed product versions

- Visual Studio: Professional 2022 (64-bit) 
- This extension: fcc-f339fe606-9d51-4fca-895c-d50375137b62

### Description

On a wide monitor, it can be nigh-impossible to tell which stats go with which entry:
![image](https://user-images.githubusercontent.com/1661988/174665885-22d45449-3eae-44dd-8f39-d792bcce97d3.png)

### Steps to recreate

1. Get ultrawide monitor
2. run all tests on a solution, to trigger FCC
3. open FCC in the bottom panel

### Current behavior

Difficult to tell what stats go with what entry

### Expected behavior

A bunch of options could make this more readable:

* row highlighting on click, like Visual Studio's error list:
![image](https://user-images.githubusercontent.com/1661988/174666210-345242ed-3231-42dd-b30f-4176b04d55c9.png)
* alternating row background colors, between the highlighted background color and the regular background color
* allow column resizing, to move the stats closer to the names

**Comment by tonyhallett** [comment]
I am currently working on a new report. I will take in to account.

**Comment by tonyhallett** [comment]
Row highlighting has been added
