### ISSUE TITLE
Show line coverage as in vscode

### ISSUE THREAD

**Issue by MrDave1999** [FortuneN/FineCodeCoverage#277]
Is there a way to show line coverage like this [vscode extension](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) does?

![image](https://user-images.githubusercontent.com/43916038/176489604-be98bdf4-2c23-4a55-9617-9256a5e001a2.png)

**Comment by tonyhallett** [comment]
I expect so !

**Comment by FortuneN** [comment]
I we are going to do this, please make it an opt-in.

**Comment by tonyhallett** [comment]
Of course. It is low priority.

**Comment by portajuan08** [comment]
Hi, Is this development still pending? thanks

**Comment by tonyhallett** [comment]
I currently do not have time for adding new features.

Perhaps someone could outline the logic we would use to colour the lines given the infinite number of ways a theme can choose to colour the background and the text color, with different syntax having different text color on the same line.

**Comment by tonyhallett** [comment]
Perhaps a toggle button.  We colour the background in the colors that have been specified for the gutter mark and then use black or white ( as necessary for sufficient contrast ) for all of the text on the line.

**Comment by tonyhallett** [comment]
Done - see readme for video / options
