### ISSUE TITLE
Fine Code Coverage extension isn't loading properly in fully patched VS 2022 x64

### ISSUE THREAD

**Issue by andersborum** [FortuneN/FineCodeCoverage#279]
### Installed product versions
- Visual Studio: 2022 Professional x64 v. 17.2.5 (fully updated as of 20th of July, 2022)
- This extension: [example 1.1.179]

### Description
We've been using Fine Code Coverage (FCC) for a couple of months on our team for .NET Core 6 projects and it's overall been a **great** experience and addition to our toolset, as it gives us code coverage insights without requiring a full enterprise subscription.

Recently FCC simply stopped showing up in the UI of my VS 2022 install and the attached screen shots show the version installed as well as the sub menu where FCC used to be available from. It's quite weird as the install I have at home with exact same version numbers of both VS 2022 and FCC works just fine.

I've tried to reinstall the extension several times without any difference - it's still not showing up.

VS 2022 is started with administrator privileges.

![image](https://user-images.githubusercontent.com/4319727/180076693-9a3f6325-116a-4b0e-b054-0a88bdaa091f.png)
![image](https://user-images.githubusercontent.com/4319727/180076887-1d51f888-b0fc-43cb-9de0-58a0903d73c3.png)
![image](https://user-images.githubusercontent.com/4319727/180078404-572fca31-30ce-4bcf-a791-f43b4a06fd2b.png)

### Current behavior
FCC isn't showing or available in menus when loading VS 2022 and projects.

### Expected behavior
Expecting FCC to be available in VS 2022.

**Comment by tonyhallett** [comment]
Is there a visual studio ActivityLog.xml with details of why FCC is not loading ?

It may be an issue that can be resolved with https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache

**Comment by andersborum** [comment]
It's weird; just applied the latest updates to VS 2022 right now and after a reset FCC actually shows up in the UI as expected. I think the update managed to reset the MEF component cache or similar as it was definitely not working previously across a number of VS 2022 updates.

Regardless, it's working and I'm a happy camper now; also, had completely forgotten about the MEF clear cache extension and will install it in case VS acts up in the future.
