### ISSUE TITLE
Coverage incorrect when doing I/O operations

### ISSUE THREAD

**Issue by SergioPicarra2** [FortuneN/FineCodeCoverage#285]
### Installed product versions
- Visual Studio: VS2019 Community Edition
- This extension: 1.1.180

### Description
Coverage does not seem to be correctly calculated when there is an IO operation taking place. It is correct up to the line of the IO operation and afterwards lines are marked as not covered

### Steps to recreate
1. Create a Unit test
2. Read a file from file system (example var bytes = System.IO.File.ReadAllBytes("path_to_file/file.xlsx");
3. Include any other operations after the file read (example var a = 1 + 2; var b = a + 3;)
4. Notice the lines after the file read are marked as not covered even though the unit test ran fully.

### Current behavior
Lines are being marked as not covered even though they are covered

### Expected behavior
Lines should be marked as covered

![Screenshot 2022-08-22 180705](https://user-images.githubusercontent.com/111773370/185967532-0967bcd5-0963-4f4a-af1d-4f6a76140d94.png)

**Comment by tonyhallett** [comment]
I suspect that what you are encountering is

https://github.com/FortuneN/FineCodeCoverage#old-style-coverage

> Dlls are copied to a sub folder of project output folder which may affect your tests. The alternative is to set the option AdjacentBuildOutput to true

The tests that are passing in test explorer are actually failing when run by FCC.  Please check the FCC Output Window pane for messages.

The other solution is to switch to ms code coverage which does not do any dll copying, although async methods are not properly covered until the next release.

**Comment by SergioPicarra2** [comment]
Hi @tonyhallett , thanks for your quick reply. 
Indeed you are right, setting the AdjacentBuildOutput to true solved the issue. I didn't notice this.
Thank you very much!
