### ISSUE TITLE
Is it planned to upgrade this to work with Visual Studio 2022 Professional?

### ISSUE THREAD

**Issue by ColinCheese** [FortuneN/FineCodeCoverage#290]
### Installed product versions
- Visual Studio: 2022 Professional

### Description
Just wondered if there were plans to upgrade this to work with Visual Studio 2022 Professional?

**Comment by tonyhallett** [comment]
If you search for "Fine" they both appear on the marketplace.  The URL for 2022 is the same as 2019 with a 2022 suffix
