### ISSUE TITLE
Code coverage is not always updated

### ISSUE THREAD

**Issue by dozer75** [FortuneN/FineCodeCoverage#3]
### Installed product versions
- Visual Studio: 2019 Community 16.7.2
- This extension: 1.0.39

### Description

Some times the code coverage isn't updated after a test run. When I go to the output log it indicates that an error occurred (see below). I am actually not quite sure why this happens, but it seems that it always happens when I run tests the first time after changing my code. Running tests the second time and it seems to work.

### Steps to recreate

1. Clone the https://github.com/dozer75/BranchCoverageDemo repo
2. Open it in Visual Studio and run tests
    - Sometimes the error occurs already here
3. Change something in Config.cs (e.g. remove the ? after options)
4. Run tests from test explorer

### Current behavior
Coverage is not updated and the Fine Code Coverage output shows:

2020-09-05 13:50:09 : Updating coverage ...

2020-09-05 13:50:10 : Error during Coverlet -> Run

2020-09-05 13:50:10 : Coverage updated!

### Expected behavior
There should not be any errors and the coverage should be updated.

It would have been nice if the output showed the actual error to, it would have make it easier to find the issue.

**Comment by dozer75** [comment]
Seems to work now! You can close this.

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
