### ISSUE TITLE
Data collector did not generate coverage.cobertura.xml

### ISSUE THREAD

**Issue by rodchenkov** [FortuneN/FineCodeCoverage#301]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.187

### Description
It was an issue with coverlet https://github.com/coverlet-coverage/coverlet/issues/1390 and in version 3.2.0 it is solved
I see that you have dependency on it's previous version and looks like simple update will solve issue with FineCodeCoverage, because now I'm getting same error in Visual Studio, while during CI/CD all works fine

### Steps to recreate
1. Create simple project same as decried here https://github.com/coverlet-coverage/coverlet/issues/1390
2. Use VS 2022 with installed extension
3. Run tests 
4. Tests run successfully while FineCodeCoverage empty and shows error in logs

### Current behavior
Tests run successfully while FineCodeCoverage empty and shows error in logs

### Expected behavior
Tests run successfully and FineCodeCoverage shows coverage report

### Side Notes
I think that we just need to update coverlet.collector lib to latest version (now it is 3.2.0) and everything will be solved.

**Comment by LukeOwlclaw** [comment]
I faced this problem using version 3.2.0:

```
Data collector 'XPlat code coverage' message: [coverlet]System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollection' from assembly 'Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.GetDefaultServiceCollection(TestPlatformEqtTrace eqtTrace, TestPlatformLogger logger, String testModule)
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.OnSessionStart(Object sender, SessionStartEventArgs sessionStartEventArgs) in /_/src/coverlet.collector/DataCollection/CoverletCoverageCollector.cs:line 132.
```

If anyone needs a quick fix:
Add to test project:

    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.1" />

Yes, I mean version 6.0.1 even though nuget manager tells you it does not exist.
