### ISSUE TITLE
All Tests are executed unnoticed in the background (even if only one is started)

### ISSUE THREAD

**Issue by Pak0** [FortuneN/FineCodeCoverage#304]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Enterprise 2022 (64-bit) - Version 17.3.6
- This extension: example 1.1.188

### Description
When you execute 1 Test, FineCodeCoverage executes ALL Tests in background, without showing it to the User.

### Steps to recreate
1. Create X IntegrationTests, that write 1 Row in a DB.
2. Execute ONE of the X Tests.
3. In Test Explorer one test shows up green, the others as "Not Run". But in the DB you will have X+1 Datarows.

### Current behavior
When I have 1000 IntegrationTests that each write to a DB and I only start one of them, in the background all Tests get executed after the one test run, so I end up with a lot of Datarows in the DB. This is not reflected in the IDE, so its unnoticed, and may cost a lot of ressources. 

### Expected behavior
If I execute one test, only one test should run, even if that means, that I only get the test coverage of that one test. 
It should not be, that ALL available test execute after the one started test, especially without indicating it to the user.

### Side Notes
- The behaviour is probably as a result to show the full code coverage, even if just one test is executed.

**Comment by tonyhallett** [comment]
Use ms code coverage option.

**Comment by Pak0** [comment]
Thank you, it works now. I should have read the readme.me more clearly, but thanks for answering.
