### ISSUE TITLE
Request: Button/Link to Open Cobertura.xml File

### ISSUE THREAD

**Issue by PaulFarry** [FortuneN/FineCodeCoverage#308]
### Installed product versions
- Visual Studio: 2022 Community 
- This extension: 1.1.188

### Description
Having a simple button/link to click to open the Coverage results file directly inside VS or in your favourite Text editor would be devine. Rather than needing to have to scroll though the log looking for the file itself.

### Steps to recreate
1. Run code coverage (wait for completion)
2. Look at the Coverage Log
3. Open FCC Output Pane
4. 
5. Find the File that was generated
6. Copy path, go to text editor and Open file

### Side Notes
<PATH> bin\Debug\net6.0\fine-code-coverage\coverage-tool-output\Cobertura.xml

**Comment by tonyhallett** [comment]
Button on toolbar of the fcc tool window
