### ISSUE TITLE
Request: Disable Colors in left hand margin

### ISSUE THREAD

**Issue by turw41th** [FortuneN/FineCodeCoverage#309]
### Installed product versions
- Visual Studio: VisualStudio 2022
- This extension: 1.1.188

### Description
It would be cool if it was possible to not only turn off the colors in right, but also in the left hand margin. I personally don't need to see my coverage all the time but only when specifically checking it.
A neat button to quickly turn it on and off would be cool

Thanks for considering!

**Comment by tonyhallett** [comment]
Done - see readme for video / options for improved editor coloring
