### ISSUE TITLE
RunSettingsFilePath in csproj

### ISSUE THREAD

**Issue by Soundman32** [FortuneN/FineCodeCoverage#312]
### Installed product versions
- Visual Studio: 2022 17.4.2
- This extension: 1.1.189

### Description
Every csproj file gets a local path based RunSettingsFilePath, which ends up getting checked into git and breaks the build.

### Steps to recreate
Open solution, build and run tests.

### Current behavior
This gets added to every csproj:
`<RunSettingsFilePath>C:\dev\MyProjectetc\bin\Debug\net6.0\fine-code-coverage\coverage-tool-output\MyProject.UnitTests-fcc-mscodecoverage-generated.runsettings</RunSettingsFilePath>`

### Expected behavior
csproj files should not be modified when testing.

**Comment by tonyhallett** [comment]
There is a difference between ms and 'old style' though. Ms is immediate and collects from the tests you select. Old style runs all tests after the ones you select finish.

I will look at storing the csproj and overwriting with it instead.

**Comment by UkeHa** [comment]
@tonyhallett, it should use a relative path instead of an absolute one. That way the files can be pushed to git and shared between developers. the autogenerated config should search from the base path of the project with the option to enter an absolute path.

**Comment by tonyhallett** [comment]
@UkeHa 
The generated runsettings entry in the csproj file should be deleted.  If this was occurring then it would be irrelevant.  If someone could specify when it doesn't then I could look at it.  Note that this does not happen every time.


https://github.com/FortuneN/FineCodeCoverage/assets/11292998/3b44c2b5-daf0-460c-85f2-5d0f7c5e45b9



The generated runsettings is generated in your bin folder which is not checked in.

**Comment by adamhearn** [comment]
@tonyhallett I can see that for the most part the csproj amendment is removed at the end of the test run. 

However, I think there must be an edge case somewhere as it does occasionally get left behind - I've seen this a few times across different projects.

As an aside if a test fails (I just threw an exception in there) the setting is not removed (it did get removed once the test passes).
