### ISSUE TITLE
Exception from the extension when saving options is causing VS 2022 to terminate.

### ISSUE THREAD

**Issue by nm515350** [FortuneN/FineCodeCoverage#313]
### Installed product versions
- Visual Studio: 2022 Enterprise Version 17.4.3
- This extension: [1.1.189]

### Description
Exception from the extension when options saved while the Fine Code Coverage tool window is not open.

### Steps to recreate
1. Close Fine Code Coverage tool window 
![image](https://user-images.githubusercontent.com/23666086/208237095-51918b8b-9018-4c39-9876-5dff7b68961b.png)
2. Restart Visual Studio 2022
3. Confirm the Fine Code Coverage window is not open.  
4. Select Tools -> Options
5. Modify any Fine Code Coverage option - I've been toggling the Enabled option.
6. Select OK to save the options.
7. Select Tools -> Options
8. Modify any Fine Code Coverage option - I've been toggling the Enabled option.
9. Select OK to save the options.
10. A wait cursor is displayed and after WERFault.exe has completed, Visual Studio 2022 terminates.

### Current behavior
Exception from the extension when options saved while the Fine Code Coverage tool window is not open.

### Expected behavior
Visual Studio 2022 should not crash when saving options.

### Side Notes
- Debugging the extension, I see that the exception is of type System.NullReferenceException
![image](https://user-images.githubusercontent.com/23666086/208237625-a90e2389-f161-4a61-bd95-95a8e1c70997.png)
- Following the code back to where environmentFontDetails is initialized, it's in ```public OutputToolWindowControl(IEventAggregator eventAggregator)```
- So by opening the Fine Code Coverage tool window, I see environmentFontDetails being initialized and thereafter I can save option changes successfully.

**Comment by tonyhallett** [comment]
Thanks for the detailed explanation. Will resolve in the next couple of days.

**Comment by nm515350** [comment]
@tonyhallett - Thank your for the quick turnaround.
