### ISSUE TITLE
Risk hotspots not run or shown when run multiple or all test projects as once

### ISSUE THREAD

**Issue by hungnguyen-yyc** [FortuneN/FineCodeCoverage#317]
### Installed product versions
- Visual Studio: VS 2022
- This extension: [example 1.1.191]

### Description
As title, when run tests in one project, FCC is able to calculate and render risk hotspots, cyclomatic complexity, etc. But when run multiple test projects as once. FCC is unable to do so.

### Steps to recreate
1. Create multiple test projects
2. Select all test projects
3. Run all tests
### Current behavior
FCC is unable to calculate and render risk hotspots, cyclomatic complexity, etc.

### Expected behavior
FCC should be able to calculate and render risk hotspots, cyclomatic complexity, etc.

**Comment by tonyhallett** [comment]
Please can you provide a solution exhibiting this behaviour as my multiple test project solution is showing risk hotspots.
