### ISSUE TITLE
Red, green and orange bars to the left of the code (line coverage)???

### ISSUE THREAD

**Issue by mwestley61** [FortuneN/FineCodeCoverage#318]
Hi there!  I came across your extension for MS's Visual Studio and thought it looked to be helpful so I installed it (I'm using it in VS 2022).  So far I'm finding it useful having coverage showing right inline with the code.  The only thing I was wondering would be if you could maybe display some more helpful detailed info, something about the particular line being hovered over whenever one hovers over the red, green and orange bars to the left of the code.  I assume that red stands for not covered, green for covered and orange I don't know.  Maybe you could include a legend somewhere that tells what the colors mean too.  Just a thought.

Thanks for your good work on this!

Mike Westley

### Installed product versions
- Visual Studio: [example 2015 Professional]
- This extension: [example 1.1.21]

### Description
Replace this text with a short description

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Explain what it should be doing after it's fixed.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by ooples** [comment]
I would like to request this feature as well

**Comment by tonyhallett** [comment]
@ooples red not covered, orange partially covered, Green covered. Aside from the number of hits there is no further info.

**Comment by ooples** [comment]
How do you define partially covered?

**Comment by tonyhallett** [comment]
We don't define it. 
It means not all branches are executed.
