### ISSUE TITLE
Error 'FineCodeCoverage2022' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading'

### ISSUE THREAD

**Issue by ptletski** [FortuneN/FineCodeCoverage#319]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Professional 2022 (64-bit) Version 17.0.4
- Fine Extension Version:  1.1.191

### Description
Fine Code Coverage window is not presented. Selecting Find Code Coverage in View/Other Windows menu presents error dialog stating that "the 'OutputToolWindowPackage' package did not load correctly."

### Steps to recreate
1. Install Fine Code Coverage from MarketPlace
2. Start VS.
3. Open View/Other Windows menu.
4. Select Fine Code Coverage menu item.

### Current behavior
Log content:
SetSite failed for package [OutputToolWindowPackage]Source: 'FineCodeCoverage2022' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=17.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. `The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Threading, Version=17.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at FineCodeCoverage.Output.OutputToolWindowPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress) at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

### Expected behavior
Fine Code Coverage should be accessible.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
Please update Vs version
