### ISSUE TITLE
Add "Export" option to the Risk Hotspots tab

### ISSUE THREAD

**Issue by russ-goodwin** [FortuneN/FineCodeCoverage#323]
### Explanation
My manager is impressed with the Risk Hotspots report and would like to be able to export it for future tech-debt story creation.
However, there currently does not appear to be a readily available way to export this information.

Can a widget be added to this tab which would export the report as a CSV or the like?

**Comment by tonyhallett** [comment]
There is now a toolbar with a button to open the hotspots as an xml file in visual studio
