### ISSUE TITLE
Runs all the tests after selecting a single test to run

### ISSUE THREAD

**Issue by tomhornyak** [FortuneN/FineCodeCoverage#327]
### Installed product versions
- Visual Studio: [example 2022 Community]
- This extension: [example 1.1.192]

### Description
If I run a single test, for example to verify a fix,, FIneCodeCoverage will start up and run all the tests after the one test is finished,

### Steps to recreate
1. Create a test project with multiple tests in multiple files.
2. Select one test in VS Test Explorer
3.Run the tests

### Current behavior
After the one test is run, all the tests are run by FIneCodeCoverage. I verified this by showing the command line in Task manager,
This wastes a lot of time.,
This was seen with both MSTest and NUnit tests.

### Expected behavior
Only the one test should be run.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
Duplicate issue. 


Set RunMsCodeCoverage to Yes

**Comment by tomhornyak** [comment]
Sorry - that didn't do it. Microsoft Code Coverage is not available in the community edition.
I turned it on and I still have the problem.

**Comment by tonyhallett** [comment]
There is a setting for hiding coverage when fully covered. Perhaps you have set this and your code is fully covered.
