### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by viceice** [FortuneN/FineCodeCoverage#329]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.192
### Description
Replace this text with a short description

### Steps to recreate
1. create a project with ms code coverage
2. enable `RunMsCodeCoverage`
3. run tests and see error in test output window

### Current behavior
Code coverage still works but i get this error
```
Failed to configure settings for runsettings plugin 'Fine Code Coverage MsCodeCoverageRunSettingsService' as it threw following exception:
'The given key was not present in the dictionary.'
Please contact the plugin author.
Starting test discovery for requested test run
```

### Expected behavior
No error

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
Without a repro I cannot investigate.
