### ISSUE TITLE
Remove the namespace name from the class name when NamespacedClasses is enabled.

### ISSUE THREAD

**Issue by DanTravison** [FortuneN/FineCodeCoverage#333]
### Installed product versions
- Visual Studio:  Community Version 17.7.0 Preview 1.0
- This extension: 1.1.192

### Description
Would it be possible to remove the namespace name from the class name when grouping by namespace and allow the Name column to be resized?

I find the organization of the NamespacedClasses option very useful but it adds quite a bit of width to the display causing me to 
resize or scroll horizontally it each time I want to view it.

The view would be much more manageable if it is presented in a manner similar to turning the option off.

+ AssemblyName
+ NamespaceName
class1
class2
...

Then allowing the Name column to be resized would avoid much of the horizontal scrolling.

### Current behavior
The width of the report is too large when using NamespacedClasses requiring constant resizing and/or scrolling.

I've tried floating the pane but even that's only useful when I have dual monitors.  Even then, it requires a full screen to see the data and doesn't avoid horizontal scrolling. 

### Expected behavior
Adds a group node for each namespace and lists the unqualified class names in a manner similar to the class list without the NamespacedClasses option enabled.  Allowing the name column to be resized to handle the case where one or more namespaces require too much horizontal display.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
There is now a visual studio enumeration option NamespaceQualification.  

        FullyQualified,
        AlwaysUnqualified,
        UnqualifiedByNamespace,
        QualifiedByNamespaceLevel

Choose one of the latter 3.
