### ISSUE TITLE
Tests executed by VS run twice

### ISSUE THREAD

**Issue by luca-domenichini** [FortuneN/FineCodeCoverage#339]
### Installed product versions
- Visual Studio: VS 2022 Community - latest at 2023-07-07
- This extension: 1.1.194
- Tests written using XUnit framework

### Description
When running tests inside VS with FCC extension installed, tests run twice.
The problem seems to belong to the fact that FCC extension copies all dlls in a subfolder of the bin directory, and seems to be related to https://developercommunity.visualstudio.com/t/why-does-my-test-run-twice/609172. VS will find the same dll used for the real test twice, and execute them accordingly.
![image](https://github.com/FortuneN/FineCodeCoverage/assets/14213760/4955d5fb-15a6-4c50-9a5e-10150b98729c)

### Steps to recreate
1. Run the test "Run_just_me":
![image](https://github.com/FortuneN/FineCodeCoverage/assets/14213760/5560fb65-1d5f-4007-9aa6-3c4b20874b65)
2. The test should create a new file C:\tmp\_test.txt with a single line "test". If FCC extension is not installed, everything works ok.
3. After installing FCC extension, "Run_just_me" is executed twice, and test "Dont_run_this" is executed as well!
![image](https://github.com/FortuneN/FineCodeCoverage/assets/14213760/3d251dcd-05bb-41e7-865f-05542b5b6f47)

Note that executing the test using CLI does produce the expected correct behaviour:
![image](https://github.com/FortuneN/FineCodeCoverage/assets/14213760/b30f2479-3ae9-4c8b-b55c-a2384a683705)
![image](https://github.com/FortuneN/FineCodeCoverage/assets/14213760/8dddf91d-544c-44e4-9ad0-aac3df9eec79)

### Current behavior
File "C:\tmp\\_test.txt" content have multiple lines, both related to the executing test and to other tests.

### Expected behavior
File "C:\tmp\\_test.txt" content should have just 1 line related to "Run_just_me" test.

[FCCTestProject.zip](https://github.com/FortuneN/FineCodeCoverage/files/11980052/FCCTestProject.zip)

**Comment by tonyhallett** [comment]
This is mentioned on the readme page and there are numerous issues already opened on this matter.
Use ms code coverage instead.

**Comment by luca-domenichini** [comment]
Ok, thank you.
Solved by modifying RunMsCodeCoverage to Yes:
![image](https://github.com/FortuneN/FineCodeCoverage/assets/14213760/d2a47e6a-5f95-48d2-8a19-dd676f66cd83)
