### ISSUE TITLE
Coverage view doesn't navigate to the generic classes

### ISSUE THREAD

**Issue by evilguest** [FortuneN/FineCodeCoverage#34]
### Installed product versions
- Visual Studio: 2019 Community Edition 16.8.1
- This extension: fcc-f339fe606-9d51-4fca-895c-d50375137b62
### Description
When I click the class name in the Coverage view, it works fine for the regular classes, but for the generic ones it doesn't. 

### Steps to recreate
1. Checkout the project https://github.com/evilguest/atropos
2. Open it in VS
3. Run the tests via the Test Explorer
4. Open the Fine Code Coverage view
5. Open the Coverage tab
6. Try clicking on various class names

### Current behavior
For any generic classes it fires up the dialog with error message: Not Found: Atropos_ImmutableDictionary_2 (where the Atropos_ImmutableDictionary_2 refers to the class Atropos.ImmutableDictionary<K, V>)

### Expected behavior
It is expected to open the source file for the class in the Visual Studio Editor

**Comment by FortuneN** [comment]
Try the latest version, let me know

**Comment by evilguest** [comment]
1. After updating to 1.1.25, VS has shown the following exception on startup:


SetSite failed for package [Microsoft.VisualStudio.Editor.Implementation.EditorPackage]Source: 'Microsoft.VisualStudio.Validation' Description: The service "Microsoft.VisualStudio.Shell.OpenDocumentService (1.0)" has already been proffered. Dispose the result of the last proffered factory before proffering another one. System.InvalidOperationException: The service "Microsoft.VisualStudio.Shell.OpenDocumentService (1.0)" has already been proffered. Dispose the result of the last proffered factory before proffering another one.   at Microsoft.Verify.FailOperation(String message, Object[] args)   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.Proffer(IProffered proffered)   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.Proffer(ServiceRpcDescriptor serviceDescriptor, BrokeredServiceFactory factory)   at Microsoft.VisualStudio.Editor.Implementation.EditorPackage.<InitializeAsync>d__39.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskCompleteInternal(Task task, CancellationToken cancel, Int32 ms)   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass100_1.<InternalGetResult>b__1()   at Microsoft.VisualStudio.Services.VsTask.IgnoreObjectDisposedException(Action action)   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass100_0.<InternalGetResult>b__0()   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass108_0.<InvokeWithWaitDialog>b__0()   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog[T](Func`1 function)   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog(Action action)   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)   at Microsoft.VisualStudio.Services.VsTask.GetResult()
--


Once I click through the confirmations and run the tests via Test Explorer, I see the following in the Build Output:
```
Fine Code Coverage : Run Coverage Tool (Atropos.Tests) Failed
System.IO.IOException: The process cannot access the file 'diagnostics.datacollector.20-12-05_19-21-18_44876_4.log' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at FineCodeCoverage.Engine.Coverlet.CoverletUtil.RunCoverlet(CoverageProject project, Boolean throwError) in C:\projects\finecodecoverage\FineCodeCoverage\Core\Coverlet\CoverletUtil.cs:line 155
   at FineCodeCoverage.Engine.FCCEngine.<>c.<ReloadCoverage>b__30_8(CoverageProject project) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 463
   at FineCodeCoverage.Engine.Model.CoverageProject.Step(String stepName, Action`1 action) in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 38
```

**Comment by FortuneN** [comment]
This is to be expected
"The process cannot access the file '' because it is being used by another process"
It goes away when you re-run.

Fine Code Coverage window stays blank until there is a successful run.

Can you navigate to generic classes?

**Comment by evilguest** [comment]
Yes, now I can, thanks.
