### ISSUE TITLE
FCC isn't reporting on one of my two MAUI projects.

### ISSUE THREAD

**Issue by MaCr02** [FortuneN/FineCodeCoverage#347]
Hi

I am trying to get FCC working agian as we are migrating a Xamarin forms solution over to MAUI using .NET 7.

I have added an MSTest project, and a single quick test which passes. One of our projects; Mobile.Core is being picked up for code coverage but the main project isn't.

Thanks

**Comment by tonyhallett** [comment]
I doubt that this is a FCC issue but a limitation of MAUI.
