### ISSUE TITLE
Coverage view doesn't show an item for private nested class

### ISSUE THREAD

**Issue by Serg046** [FortuneN/FineCodeCoverage#35]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.25

### Description
Coverage view doesn't show an item for private nested class, although a coverage xml generated by coverlet has the corresponsing node.

**Comment by FortuneN** [comment]
Please attach a repro

**Comment by Serg046** [comment]
For example, this one class https://github.com/Serg046/AutoFake/blob/master/AutoFake/FakeGenerator.cs#L69

It is covered by the tests and corresponding highlighting is in VS but navigation item is not available.

**Comment by FortuneN** [comment]
From the underlying project 'ReportGenerator'
https://github.com/danielpalme/ReportGenerator/issues/154

"The coverage results of nested classes are merged into the parent class.
You can visualize that by generating the HTML report.
**Nested classes are not listed separately**"

Maybe we can ask the owner of that project to list nested classes separately.
If you create the issue there (and let me know), i will second it

**Comment by Serg046** [comment]
Nope, I am fine if it is intentional, thank you 👍
