### ISSUE TITLE
Highlight rows on hover

### ISSUE THREAD

**Issue by NimaAra** [FortuneN/FineCodeCoverage#353]
This is a great extenion, thank you for making this available.

I am considering switching from dotCover to this extension and the only feature lacking for my use-case is the ability to highlight the rows in the result window. Without the highlihting it becomes difficult to keeping track of the classes specially in solutions with many projects.

It will be great if the table rows are highlighted on mouse hover.

**Comment by tonyhallett** [comment]
This release add themed hover functionality https://github.com/FortuneN/FineCodeCoverage/releases/tag/v1.1.196

@FortuneN another feature that requires releasing to the marketplace

**Comment by NimaAra** [comment]
Has this feature been released as an update yet? The latest version I can see is: _1.1.197_

![image](https://github.com/FortuneN/FineCodeCoverage/assets/16215744/83d1bb81-aaff-4c18-af46-cc43b4ae0c18)
