### ISSUE TITLE
Exclude file patterns and an assembly from CodeCoverage. Can FCC run in a BuildServer?

### ISSUE THREAD

**Issue by aboimpinto** [FortuneN/FineCodeCoverage#354]
### Installed product versions
- Visual Studio: 2022
- This extension: 1.1.94

### Description
I want to exclude from CodeCoverage all the files with the extension *.axaml.cs, and this is my settings.

![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/f3d9da71-102f-4a0f-9da0-0f682501596d)

In the end, the file with that extension is still included.

I want to exclude a whole assembly but need help finding a way.

I know I can use the [ExcludeFromCodeCoverage] tag, but I'm trying to use something other than that because that is too intrusive for the developer. I want to set this on the CodeCoverage settings that can be shared in all developer machines.

Can you also provide a way to export these settings to be consistent in every developer machine?

Is there a way to use this on the build server? It would be excellent for the output report to be generated during the build WorkFlow, and we can check it later.

### Steps to recreate
Try to setup with the settings page.

### Current behavior
I could not find a way to add an exclusion of a pattern or a whole assembly from CodeCoverage.

### Expected behavior
I would expect the file patterns to be excluded, and a project could be excluded, and be able to generate a report from the Build Server

Thanks a lot 
Paulo Aboim Pinto

**Comment by tonyhallett** [comment]
Note that if you switch to ms code coverage then you need to use that method of exclusion - https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#include-or-exclude-assemblies-and-members

> Is there a way to use this on the build server?
FCC only runs from within visual studio, initiated from the test explorer.


> Can you also provide a way to export these settings to be consistent in every developer machine?

I am looking at the ProvideProfileAttribute now.

**Comment by aboimpinto** [comment]
> Note that if you switch to ms code coverage then you need to use that method of exclusion - https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#include-or-exclude-assemblies-and-members

tkx for the answer ...
Can you provide a complete example? I could not put the FCC work with the .runsettings file.

**Comment by aboimpinto** [comment]
For the exclusion of a file name pattern, I try to use the example in this discussion

https://github.com/FortuneN/FineCodeCoverage/discussions/298

and I add this to my csproj
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/83071615-28af-417f-b745-88c0b1e4cbcf)

but the settings in the output still the same from the settings page
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/c5eb2b7e-19a5-4893-b008-0453fc57479e)

how can the settings in the csproj overnight there ones in the settings?

**Comment by tonyhallett** [comment]
> Can you provide a complete example? I could not put the FCC work with the .runsettings file.

Provide in visual studio options / the project file / fcc run settings file.
Visit the link to understand how microsoft does exclusion and inclusion.

**Comment by aboimpinto** [comment]
But this article doesn't discuss excluding one file pattern but a whole DLLs ... which I can do already ... 
Now, I need to know how to exclude the files *.axaml.cs that is inside the DLL

**Comment by tonyhallett** [comment]
> But this article doesn't discuss excluding one file pattern

Yes it does.  Source, for which FCC has SourceExclude and SourceInclude.

**Comment by tonyhallett** [comment]
> how can the settings in the csproj overnight there ones in the settings?

Have you added `<PropertyGroup label="FineCodeCoverage">` in the project file ?

**Comment by aboimpinto** [comment]
> > how can the settings in the csproj overnight there ones in the settings?
> 
> Have you added `<PropertyGroup label="FineCodeCoverage">` in the project file ?

yes ..

![272921286-83071615-28af-417f-b745-88c0b1e4cbcf](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/96c22b27-b2b5-42c1-81d9-0977e99bff48)

**Comment by aboimpinto** [comment]
I still have the .runsettings file and be there or not it's the same ... maybe I need to do something else to make the build use it.
```
<?xml version="1.0" encoding="utf-8"?>

<RunSettings>
	<RunConfiguration>
		
		<TreatTestAdapterErrorsAsWarnings>false</TreatTestAdapterErrorsAsWarnings>
		<ResultsDirectory>.\TestResults</ResultsDirectory>

		<MaxCpuCount>0</MaxCpuCount>

		<TestSessionTimeout>10000</TestSessionTimeout>

		<TreatNoTestsAsError>false</TreatNoTestsAsError>

		<DisableParallelization>false</DisableParallelization>
		<DisableAppDomain>false</DisableAppDomain>
		<CollectSourceInformation>true</CollectSourceInformation>

		<BatchSize>10</BatchSize>

	</RunConfiguration>

	<DataCollectionRunSettings>
		<DataCollectors>
			<DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
				<Configuration>
					<CodeCoverage>

						<!-- Match assembly file paths: -->
						<ModulePaths>
							<Include>
								<ModulePath>.*\.dll$</ModulePath>
								<ModulePath>.*\.exe$</ModulePath>
							</Include>
							
							<Exclude />
						</ModulePaths>

						<!-- Match fully qualified names of functions: -->
						<!-- (Use "\." to delimit namespaces in C# or Visual Basic, "::" in C++.)  -->
						<Functions />

						<!-- Match attributes on any code element: -->
						<Attributes />

						<!-- Match the path of the source files in which each method is defined: -->
						<Sources>
							<Exclude>
								<Source>.*\\*.axaml.cs</Source>
							</Exclude>
						</Sources>

						<!-- Match the company name property in the assembly: -->
						<CompanyNames>
							<Exclude>
								<CompanyName>.*microsoft.*</CompanyName>
							</Exclude>
						</CompanyNames>

						<!-- Match the public key token of a signed assembly: -->
						<PublicKeyTokens />


						<!-- We recommend you do not change the following values: -->
						<UseVerifiableInstrumentation>True</UseVerifiableInstrumentation>
						<AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>
						<CollectFromChildProcesses>True</CollectFromChildProcesses>
						<CollectAspDotNet>False</CollectAspDotNet>

					</CodeCoverage>
				</Configuration>
			</DataCollector>
			
		</DataCollectors>
	</DataCollectionRunSettings>

	<!-- MSTest adapter -->
	<MSTest>
		<MapInconclusiveToFailed>false</MapInconclusiveToFailed>
		<CaptureTraceOutput>true</CaptureTraceOutput>
		<DeleteDeploymentDirectoryAfterTestRunIsComplete>true</DeleteDeploymentDirectoryAfterTestRunIsComplete>
		<DeploymentEnabled>true</DeploymentEnabled>
		<DeployTestSourceDependencies>true</DeployTestSourceDependencies>
		<MapNotRunnableToFailed>false</MapNotRunnableToFailed>
		<EnableBaseClassTestMethodsFromOtherAssemblies>false</EnableBaseClassTestMethodsFromOtherAssemblies>
		
		<ForcedLegacyMode>false</ForcedLegacyMode>
	</MSTest>

</RunSettings>

```

**Comment by tonyhallett** [comment]
> Have you added <PropertyGroup label="FineCodeCoverage"> in the project file ?

Sorry, I meant have you added to the test project file ?

**Comment by tonyhallett** [comment]
I expect not as project file will overwrite that of visual studio options ( unless you specify merge - for an array setting )

**Comment by tonyhallett** [comment]
> I still have the .runsettings file and be there or not it's the same ... maybe I need to do something else to make the build use it.

Yes, if you decide to provide your own then you need to tell visual studio to use it - https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022#specify-a-run-settings-file-in-the-ide

Note that you do not need to provide one as FCC will create a runsettings file per test project using the settings that have been provided in visual studio options / the test project file / finecodecoverage-settings.xml.

**Comment by aboimpinto** [comment]
Well... I don't decide to provide my own ... I wonder if I need one or not ... 
(unfortunately, I'm doing this kind of DevOp work without motivation or knowledge.)

I want to be able to exclude some files inside a project (example *.axmal.cs) and some projects (like the UI Controls project)

Would you like me to have a .runsettings file? I have no idea ... please tell me if  I need it and how I do it because I'm swimming in the mayonnaise here.

Thanks a lot
Paulo Aboim Pinto

**Comment by tonyhallett** [comment]
You do not need to provide one.

You just need to understand the exclusion format of the code coverage provider that you choose to use and decide upon how you would like to tell FCC of your exclusion.

If you do not choose ms code coverage then you need to use glob patterns https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#filters

The ExcludeByFile that you provided is correct ( although the ** at the beginning could be * )
<img width="376" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/40fe4b08-fdc2-48d0-a985-654d0d03ad2d">

The question is then, why did FCC not use this setting.

<img width="413" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/f01f6887-1656-40a6-a9b8-fec9cf0f3b99">

I have asked you if you added this in the test project file.  So did you ?

If you choose to use ms code coverage then it is regular expressions https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#regular-expressions

If you were to use SourcesExclude in either Visual Studio options, finecodecoverage-settings.xml or .csproj with

![image](https://github.com/FortuneN/FineCodeCoverage/assets/11292998/03179d72-ea2a-4997-b3c8-f91bac13bde1)

Then using

> Include and exclude nodes use regular expressions, which aren't the same as wildcards. All matches are case-insensitive. 

> Some examples are:
> 
> .* matches a string of any characters
> 
> \. matches a dot "."
> 
> \( \) matches parentheses "( )"
> 
> \\ matches a file path delimiter "\"
> 
> ^ matches the start of the string
> 
> $ matches the end of the string

The regex matches any string of characters, the file path delimiter, then matches *.axaml.cs which is incorrect. 

Try this instead, if you use ms code coverage, .*\\.*.axaml.cs$

**Comment by tonyhallett** [comment]
> Can you also provide a way to export these settings to be consistent in every developer machine?

I have update the extension but the github action is failing.
@FortuneN 
https://github.com/FortuneN/FineCodeCoverage/actions/runs/6429539943

> The Personal Access Token used has expired.

**Comment by tonyhallett** [comment]
@aboimpinto If you want the exporting of FCC settings then you can use this release https://github.com/FortuneN/FineCodeCoverage/releases/tag/v1.1.195

**Comment by aboimpinto** [comment]
Thanks a lot for all the information ... I already tried to exclude specific files, and I was not adding that PropertyGroup in the Test Project.
It's in now
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/f4a77ce2-ab7c-41a9-aa10-e98869736520)

and it's not been used 
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/8da633b0-976d-4702-905f-8ecd6e5bf6ec)

But, the file *.axaml.cs still appears in the report.
the file
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/d2b60574-e0dc-4bd7-8ec8-d76e8b4cfc42)

the report
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/5ba86f9c-be0f-4ce3-98c9-31ba8fe6c05f)

Maybe the pattern in the PropertyGroup is not right ...

**Comment by aboimpinto** [comment]
I try with the patterns:
- **/*.axaml.cs
- */*.axaml.cs

The file is still shown in the report.

**Comment by aboimpinto** [comment]
in the main page of the project: https://github.com/FortuneN/FineCodeCoverage
there is an example of the PropertyGroup 

![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/d4cbba25-b665-4774-aa07-d6e2087534a8)

and the pattern starts with double star (**)

**Comment by tonyhallett** [comment]
When you click on the link, does the expected file open in visual studio ?

<img width="210" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/354e6438-63d4-4eec-bf2e-7ac0b9bba3bf">

**Comment by aboimpinto** [comment]
yes .. and that is the file I want to exclude

**Comment by tonyhallett** [comment]
If you switch to ms code coverage and use SourcesExclude `.*\\.*.axaml.cs$` do you get the same result ?

**Comment by aboimpinto** [comment]
I have this in the .runsettings file

![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/220bfb8c-c841-4850-803b-be28c29e8c8a)

and the file is in the same level of the sln of the project.
How the coverlet knows that should use this file?

**Comment by tonyhallett** [comment]
I want you to switch to ms code coverage, not coverlet. Do that in the visual studio options.

Do not provide the runsettings for now, let FCC do that. Add SourcesExclude. Do that in Vs options too for now.

**Comment by aboimpinto** [comment]
how I do that!??!?
how to I change to MS Code Coverage?

**Comment by tonyhallett** [comment]
Open Vs options for Fine Code Coverage and set RunMsCodeCoverage to true.  Then add to the SourcesExclude option.

**Comment by aboimpinto** [comment]
ok ...

![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/f17f8f4c-33a1-47e1-a047-82dd226f6ae3)

and 

![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/b941229e-3a81-4b49-826d-4566a5fed17b)

and nothing in the report

**Comment by tonyhallett** [comment]
What does the Output Window FCC pane show ?

**Comment by aboimpinto** [comment]
ahhh the pattern was wrong ... 
I replace with 
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/ddabd64c-127a-4f83-bd57-bc93df3506d8)

![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/ecf82aa1-d605-47c8-b871-e94ef98d0f61)

in the end after many File does not exist

![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/c99ed2e5-3939-4007-bbd6-ff48ed04e69d)

and generates report and the excluded pattern still there
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/dd59811d-0919-4073-a271-0d7eb08a29be)

**Comment by tonyhallett** [comment]
Can you provide a minimal solution with a single avalonia view.

**Comment by aboimpinto** [comment]
yes ... can !!!

**Comment by tonyhallett** [comment]
With a test project please

**Comment by tonyhallett** [comment]
The only other thing that could be possible is that avalonia creates an additional Init2bView file and when we click the link it opens the .axaml.cs file.

**Comment by aboimpinto** [comment]
https://github.com/AboimPinto/BasicAvaloniaProject

I didn't add the FCC it's 100% clean

**Comment by tonyhallett** [comment]
Will have a look

**Comment by aboimpinto** [comment]
> The only other thing that could be possible is that avalonia creates an additional Init2bView file and when we click the link it opens the .axaml.cs file.

Well .. if that is true ... I will have a justification for the "Code Auditors" and I will be able to justify have the tag [ExcludeFromCodeCoverage] in every view of the app

**Comment by tonyhallett** [comment]
It is true

<img width="514" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/20416fcc-c901-4c0e-b8fc-892d8e81f826">

**Comment by tonyhallett** [comment]
Exclude all .g.cs files and you are there

**Comment by tonyhallett** [comment]
in addition to the .axaml.cs files

**Comment by tonyhallett** [comment]
If you give your views in all your projects the same namespace part you could exclude by that instead of by source file extension.

**Comment by aboimpinto** [comment]
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1231687/27c604b2-535c-4c11-a08e-e75da1aeced1)

I had the exclude the .xaml files also ... 

and now
Not there ...  YES!!!

and now ... the next step ... export this configuration in order to be used in all developer machines the same way!!

**Comment by tonyhallett** [comment]
Hide Moq and your test framework while you are there too !

**Comment by tonyhallett** [comment]
Just note that there are differences between ms code coverage and coverlet/opencover.  
Ms code coverage only provides coverage for what you run in test explorer.
The others run all tests and work by copying dlls and running tests again after the test explorer has. 

Instead of exporting the vs settings you might be able to use finecodecoverage-settings.xml files

https://github.com/FortuneN/FineCodeCoverage#project-configuration

> These are found by walking up the directory structure from the project directory. By applying the attribute topLevel='true' to the root element the walk stops.

These override ( or possibly merge ) visual studio options.

**Comment by aboimpinto** [comment]
I updated to the new version of FCC as you proposed.

Where should be the finecodecoverage-settings.xml file? At the root of the project?

**Comment by tonyhallett** [comment]
You can place it in a test project directory or above.  
So you can add to a solution directory to be applicable to the solution.

If you had a repo directory with all your solutions you can place in there or an ascendant directory to apply to all solutions.

**Comment by aboimpinto** [comment]
I could add the finecodecoverage-settings.xml and now I could remove all the settings in FCC Settings Page and use the parameters I specified in the file.

You cracked this when you found that I had to exclude the *.g.cs. 
Thanks a lot ... I was around this for a long time with no solution ...

once again 
Thanks a lot ... you have been a great help 
Paulo Aboim Pinto
