### ISSUE TITLE
Unable to configure coverlet with DoesNotReturnAttribute option

### ISSUE THREAD

**Issue by DwayneNeed** [FortuneN/FineCodeCoverage#358]
### Installed product versions
- Visual Studio: 2022 Enterprise
- This extension: 1.1.194

### Description
Unable to configure coverlet with DoesNotReturnAttribute option

### Steps to recreate
1. Set DoesNotReturnAttribute setting in .runsettings according to https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md
2. run unit tests
3. observe the generated FCC.runsettings generated file is missing the setting

### Current behavior
The DoesNotReturnAttribute setting is not included in the generated FCC.runsettings file.

### Expected behavior
Ideally, the FCC UX would allow setting this option directly.  It should also allow it to be specified in the .runsettings file and include it in the generated FCC.runsettings file.  

I tried to use a template to force the setting to be included, but I was not able to make that work.  I looked for examples of the template and didn't find anything.

**Comment by tonyhallett** [comment]
The runsettings template is for ms code coverage only. Does ms code coverage take into account the DoesNotReturnAttribute ?

**Comment by DwayneNeed** [comment]
No, ms code coverage does not seem to respect the DoesNotReturn attribute.  I've raised an issue with them internally too.  It looks like coverlet is the only coverage tool that supports it right now.

**Comment by tonyhallett** [comment]
It is possible that ms code coverage does - FCC uses version 17.1.  It is now at 17.7.2.

I believe that this is their [issues](https://github.com/microsoft/codecoverage/issues)

**Comment by DwayneNeed** [comment]
I didn't see it in their issue list, so I added it:
https://github.com/microsoft/codecoverage/issues/58

**Comment by tonyhallett** [comment]
If you want to use DoesNotReturnAttribute setting then you can

> Fine Code Coverage will use the Data Collector driver under two circumstances :

> You are testing with runsettings that contains the coverlet collector ( and not disabled)

**Comment by tonyhallett** [comment]
I will check if we are using the correct version of coverlet

**Comment by tonyhallett** [comment]
Appears so https://github.com/coverlet-coverage/coverlet/blame/3ec85e7a331c4393a38a62d3c099ea71bfc20297/src/coverlet.collector/DataCollection/CoverletSettingsParser.cs
