### ISSUE TITLE
Not working after uninstall/reinstall

### ISSUE THREAD

**Issue by Mike-Johns** [FortuneN/FineCodeCoverage#359]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.194

### Description
I was really enjoying this extension, and then I had to uninstall/reinstall and now when I open my solution in Visual Studio, I see lots of error messages from FCC starting with

Fine Code Coverage 11/2/2023 2:11:25 PM: Failed to load 'Exclude' setting
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at FineCodeCoverage.Options.JsonConvertService.DeserializeObject(String value, Type propertyType)
   at FineCodeCoverage.Options.AppOptionsProvider.LoadSettingsFromStorage(IAppOptions instance) in D:\a\FineCodeCoverage\FineCodeCoverage\SharedProject\Options\AppOptionsProvider.cs:line 94

### Steps to recreate
1. Have FCC working
2. Uninstall FCC
3. Install FCC

### Current behavior
FCC won't start up.

### Expected behavior
FCC should start.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by Mike-Johns** [comment]
I got FCC working again by deleting the x64\Debug directory in my solution's output (it contained a fine-code-coverage directory that I'm guessing didn't do well through uninstall/reinstall).  After that, FCC seems to be working again, but I still see those same errors on initialization.

**Comment by Muhammad-Uzair-Ghaffar** [comment]
I also faced the issue FCC not working.
Coverage logs showed me "coverage not collected as FCC disabled". I wasn't able to find proper solution. 
I think there are no proper documentation of general settings (what every function in settings is for?)
I was also not getting the coverage but by chance turned on Run MS Coverage (It worked for me).

**Comment by tonyhallett** [comment]
@Muhammad-Uzair-Ghaffar 
Not the same issue - looks like in your case FCC is working but you had no coverage as you had disabled it.

**Comment by tonyhallett** [comment]
@Mike-Johns 
What other extensions do you have installed ?

**Comment by tonyhallett** [comment]
Note that Newtonsoft.Json was added 28/3/2022
