### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by NickBarton** [FortuneN/FineCodeCoverage#360]
### Installed product versions
- Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.7.6- 
This extension: 1,1.194

### Description
An export to spreadsheet format would be very useful for tracking progress on a legacy product.

### Steps to recreate
NA

### Current behavior
NA

### Expected behavior
NA

### Side Notes
NA

**Comment by tonyhallett** [comment]
What do you want exported ? The cobertura file is available - this is XML.

**Comment by tonyhallett** [comment]
There is now a button to open the Cobertura file.
