### ISSUE TITLE
Reports it won't run as it is disabled, but it isn't

### ISSUE THREAD

**Issue by bhaeussermann** [FortuneN/FineCodeCoverage#361]
### Installed product versions
- Visual Studio: Enterprise 2022 (17.7.7)
- This extension: 1.1.194

### Description
Whenever I run tests no results are shown in the "Fine Code Coverage" window. In the FCC Output I see `Coverage not collected as FCC disabled.`

When I check Manage Extensions I can see that the Fine Code Coverage extension is enabled.

I already tried uninstalling the extension, then deleting the _...AppData\Local\FineCodeCoverage_ folder, then installing the extension again. The symptoms remain the same.

### Steps to recreate
1. Install the extension & restart Visual Studio.
2. Create a new NUnit test project.
3. Run the test.

### Current behavior
No results are shown in the Fine Code Coverage window and in the output it says `Coverage not collected as FCC disabled.`

### Expected behavior
Code coverage results should show up in the Fine Code Coverage window after running tests.

**Comment by tonyhallett** [comment]
Perhaps it is reporting that FCC is disabled because you have disabled it ?

<img width="517" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/b7403704-77f9-412a-95e0-7941d7aa81f1">

**Comment by bhaeussermann** [comment]
Ah! That's what it was 🤦‍♂️.
Thanks! 😊
