### ISSUE TITLE
Setting 'Enabled=True' in settings file doesn't enable FCC coverage when 'Enabled=False' in global Visual Studio settings

### ISSUE THREAD

**Issue by CNBoland** [FortuneN/FineCodeCoverage#362]
### Installed product versions
- Visual Studio: 2022 Professional (v17.8.1)
- This extension: 1.1.197

### Description
Setting `Enabled=True` in settings file (finecodecoverage-settings.xml at project or solution level, MSBuild properties in .csproj file) doesn't enable FCC coverage when `Enabled=False` in global Visual Studio settings.

The converse is true, however: `Enabled=False` in settings file disables FCC coverage when `Enabled=True` in global Visual Studio settings, though FCC UI indicates this differently by displaying a different message on _Coverage log_ tab: _(FCCEnabledSettingIssue) Failed. See the FCC Output Pane_. Viewing the FCC Output Pane shows log entries:
```
Fine Code Coverage 12/8/2023 2:10:23 PM: ================================== START ==================================
Fine Code Coverage 12/8/2023 2:10:23 PM: (FCCEnabledSettingIssue) Failed.
Disabled
Fine Code Coverage 12/8/2023 2:10:23 PM: ================================== DONE ==================================
```

### Steps to recreate
1. Install FCC add-in.
2. Display the FCC UI in Visual Studio.
3. Open Visual Studio Settings, navigate to _Fine Code Coverage > Run (Common)_ and set: `Enabled = False`.
4. Create a new file at the solution level named _finecodecoverage-settings.xml_ with the following contents:
```
<FineCodeCoverage>
  <Enabled>
    True
  </Enabled>
</FineCodeCoverage>
```
5. Run a unit test.

### Current behavior
On the FCC UI, _Coverage log_ tab, is displayed: _Coverage not collected as FCC is disabled._

### Expected behavior
The `Enabled=True` setting in _finecodecoverage-settings.xml_ should override global `Enabled=False`, code coverage should be collected, and FCC display the results.

Attached repro solution: [FCCEnabledSettingIssue.zip](https://github.com/FortuneN/FineCodeCoverage/files/13620507/FCCEnabledSettingIssue.zip)

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
The VS Enabled option set to false prevented code coverage running.  There is now an additional option DisabledNoCoverage that you can set to false to prevent this from occurring.
