### ISSUE TITLE
Coverage mechanism could auto-detect Microsoft Test Framework or XUnit test methods and exclude them

### ISSUE THREAD

**Issue by humbertomoreno** [FortuneN/FineCodeCoverage#365]
### Installed product versions
- Visual Studio: [example 2022 Professional]

### Description
First of all, a big THANK YOU for such a wonderful tool.
I only have just a couple of suggestions:
1. Coverage mechanism could auto-detect Microsoft Test Framework or XUnit test methods from code analysis. Most of the Test projects show in the analysis list and they are measured the same way as the rest of the code.
2. If you could incorporate a Button in the main interface, to push a manual scan, instead of this being automatic. This would be great.

### Side Notes
- FCC is a great product. Keep up the good work, guys!

**Comment by tonyhallett** [comment]
> Coverage mechanism could auto-detect Microsoft Test Framework or XUnit test methods from code analysis. Most of the Test projects show in the analysis list and they are measured the same way as the rest of the code.

Are you saying that you would like to exclude your test assemblies from coverage ? If so there is an IncludeTestAssembly option which defaults to true and can be set to false.

> If you could incorporate a Button in the main interface, to push a manual scan, instead of this being automatic. This would be great.

Just turn off FCC with the vs option Enabled and turn it back on when required.

**Comment by humbertomoreno** [comment]
Thanks!

________________________________

**Comment by tonyhallett** [comment]
Good to close then ?

**Comment by humbertomoreno** [comment]
Yes! Thanks a lot.

You guys have an excellent tool.

________________________________
