### ISSUE TITLE
Filter projects/files with 100% or 0% coverage

### ISSUE THREAD

**Issue by FF-Brown** [FortuneN/FineCodeCoverage#367]
### Installed product versions
- Visual Studio: 2022
- This extension: 1.1.197

### Description
Love this extension! It's been incredibly helpful so far.
It would be awesome if I could filter the coverage report to exclude either projects/files with 100% coverage or 0% coverage. I'm working with a large solution and it would be nice to completely ignore the sections of code I haven't gotten to UT yet.
See screenshot. I'd like to be able to ignore the crossed-out items. Even better would be the ability to do this for files.
![image](https://github.com/FortuneN/FineCodeCoverage/assets/54860453/e73dbe2a-506f-40d3-8e23-089f415d89a6)

If I get some extra time and if this is a feature you'd be willing to include, I'd be happy to work on this change.

**Comment by tonyhallett** [comment]
There is an option HideFullyCovered. As for hiding what you have not unit tested. You can exclude everything then include what you are working on

**Comment by FF-Brown** [comment]
@tonyhallett Thanks for pointing out that setting! I wasn't aware of it.
What I was trying to do is compare two branches and determine whether there was any difference in coverage between them. This was difficult to do because there were so many 0% covered files. So the process WOULD have been expedited if I'd thought to make a list of files with >0% coverage on one branch and only include those files on the other branch.

I still maintain that it would be nice to be able to exclude files with 0% coverage. It would be nice to ignore areas of code that aren't a concern

**Comment by tonyhallett** [comment]
Added option Hide0Coverage that you need to set to true.  There is also Hide0Coverable that defaults to true - this gets rid of coverage for nunit and similar.

**Comment by tonyhallett** [comment]
available on marketplace now.

**Comment by FF-Brown** [comment]
Eons later...
Been using this feature and really enjoying it, thanks a bunch for implementing it! It's made it a lot easier to scroll through the report and see the chunks I actually care about. Thought I had replied here forever ago but apparently not.
