### ISSUE TITLE
Organize coverage report by namespace/folder

### ISSUE THREAD

**Issue by FF-Brown** [FortuneN/FineCodeCoverage#368]
### Installed product versions
- Visual Studio: 2022
- This extension: 1.1.197

### Description
Currently, the Coverage report can be collapsed for each project. It would be awesome if we could also have it organized by folder or namespace.
So, currently the report looks something like this:
![image](https://github.com/FortuneN/FineCodeCoverage/assets/54860453/5fd2977c-6527-4dc4-98a0-9f7fe8829e9f)

But I'd like to have the +/- (Expand/Collapse) options for Folder and Subfolder (in this example screenshot) as well.

This is a great extension! If I get some free time and if this is a feature you'd consider, I'd be happy to work on this change.

**Comment by tonyhallett** [comment]
You can organize by namespace.  The grouping slider has "By Namespace"

**Comment by FF-Brown** [comment]
@tonyhallett Oh that's awesome! I hadn't noticed that slider. Thank you!
