### ISSUE TITLE
Search for file

### ISSUE THREAD

**Issue by muradexQ2** [FortuneN/FineCodeCoverage#369]
### Installed product versions
- Visual Studio: [example 2022 Professional]
- This extension: [example 1.1.21]

### Description
Make it easier to locate a class on the Coverage tab.

### Current behavior
After running unit tests (we use Xunit) the list of classes on the Coverage tab is renewed, and I have to locate the coverage for the class I am currently working on again from top of the list. It is quite inconvenient. 

### Expected behavior
Provide the means to make a quick search functionality on the Coverage tab to locate a project class in it. Something like like ^F on Coverage tab.

**Comment by tonyhallett** [comment]
There is a Filter text box on the coverage tab
