### ISSUE TITLE
Single Page Application (SPA) Mvc project has not be calculated by fine code coverage.

### ISSUE THREAD

**Issue by nsentuna** [FortuneN/FineCodeCoverage#37]
### Installed product versions
- Visual Studio: [Microsoft Visual Studio Professional 2019
Version 16.8.3]
- This extension: [1.1.25]

### Description
I have two diffrent project, one of them VS. ASPX and others is Single Page Application (SPA) Mvc.
I have no problem with ASPX 

but other project has not be calculated by fine converaged I attached screen shoot like below.
![Ekran görüntüsü 2020-12-10 155053](https://user-images.githubusercontent.com/21196564/101775815-177ce800-3b01-11eb-847a-95c35cab04ad.png)

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Explain what it should be doing after it's fixed.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by FortuneN** [comment]
Please attach a repro; i'll have a look

**Comment by nsentuna** [comment]
where can I find the repro ? I found a file that named codecoverage.runsettings I attached it.  is it repro ?

[CodeCoverage.runsettings.txt](https://github.com/FortuneN/FineCodeCoverage/files/5677286/CodeCoverage.runsettings.txt)

**Comment by FortuneN** [comment]
It's easier to get started on the problem if i can reproduce it on my local machine and observe closely.
A 'repro' is a **_small_** sample project/solution that reproduces the problem (something i can run to see the problem).

**Comment by nsentuna** [comment]
Can you check my this issue ? you said me you reproduce on your local machine.

**Comment by FortuneN** [comment]
Please create a small sample solution that shows the problem.
It's not easy to solve what i cannot run in my debugger.

I will deal with this as soon a you provide that sample solution.

**Comment by tonyhallett** [comment]
@FortuneN given that that @nsentuna has mentioned runsettings. Could be related to https://github.com/FortuneN/FineCodeCoverage/issues/55

**Comment by FortuneN** [comment]
@tonyhallett Could be

@nsentuna Try the latest version (1.1.52 at the time of this reply)

**Comment by nsentuna** [comment]
dear @tonyhallett  @FortuneN 

thanks a lot , My problems has been resolved with last version 1.1.52,  Fine code covared has run well anymore with my either aspx and spa (mvc) projects. 

Have a nice cristmes and new years, keep with healthly

Best regards.
