### ISSUE TITLE
No coverage results displayed

### ISSUE THREAD

**Issue by millele3** [FortuneN/FineCodeCoverage#390]
### Installed product versions
- Visual Studio: 2022 Professional (Version 17.8.5)
- This extension: 1.1.209

### Description
After running unit tests, not coverage results show up

### Steps to recreate
1. Run unit tests
2. Look at Fine Code Coverage window 

### Current behavior
This happened to me in the past, but would correct itself after restarting VS or rebooting, or cleaning solution and re-running tests
Now, it never corrects itself, and never shows results.
I uninstalled, and re-installed extension. Not improvement.

### Expected behavior
I expect to see coverage results after running tests

### Side Notes
![image](https://github.com/FortuneN/FineCodeCoverage/assets/21366039/1c7a14ec-5627-4c87-87ba-7137a939d977)

**Comment by tonyhallett** [comment]
What does the log show

**Comment by millele3** [comment]
Where can I find the log?

**Comment by tonyhallett** [comment]
I think that there is a bug where you run tests without any code file open.

**Comment by millele3** [comment]
Ah, yes I seem to see results in the output window if I have a code file open. However, I still don't see the red/green tick marks that show covered and uncovered code. That was a great feature.

![image](https://github.com/FortuneN/FineCodeCoverage/assets/21366039/1ab4d3f3-1082-4855-84a6-e9574648b1f5)

**Comment by millele3** [comment]
It didn't seem to be working. Then when I got on my laptop today, I see the taggers. I may have some sort of performance issue where it is taking a very, very long time to see coverage results and taggers.
I seem to have noticed performance problems in VS since the last VS update.
