### ISSUE TITLE
Shows Not Covered For Private Method Called by Tested Public Method

### ISSUE THREAD

**Issue by pharris-emerson** [FortuneN/FineCodeCoverage#392]
### Installed product versions
- Visual Studio 2022 Enterprise
- Fine Code Coverage 1.1.209

### Description
When viewing a file that has unit tests written for it, it shows private methods not being covered but which are called by public methods that are covered.

### Expected behavior
I expect the coverage shown to include the private method that is called by a covered public method.

**Comment by tonyhallett** [comment]
Want to show an example

**Comment by tonyhallett** [comment]
It is possible that you are running the old style coverage which copies dlls to a new location.  This can effect tests where you are using file paths.  If this is the case then see if the Ms Code Coverage option gives expected results.
Closing as I cannot assist if you do not provide anything to work with.
