### ISSUE TITLE
Are you planning to update the version of microsoft.codecoverage?

### ISSUE THREAD

**Issue by tYoshiyuki** [FortuneN/FineCodeCoverage#393]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.209

### Description
I have always found Fine Code Coverage very useful.

As per the subject line, do you have any plans to update the version of `microsoft.codecoverage`,
the library used inside Fine Code Coverage?

I am using Fine Code Coverage in a huge C# (ASP.NET Core) project. We have more than 10,000 test cases.
(I am sorry, but due to business reasons, I am not able to share the solution files.)
I am using Fine Code Coverage in `RunMsCodeCoverage` mode.
We are not using our own runsettings and are using the default behavior of Fine Code Coverage.

As a workaround, we were able to resolve the situation
by updating the version of `microsoft.codecoverage` from `17.1.0` to `17.9.0`

- This is a provisional fix, but we forced the contents of `C:\Users\{UserName}\AppData\Local\FineCodeCoverage` to be overwritten
- Corrected the path of `Microsoft.VisualStudio.CodeCoverage.Shim.dll` as it had changed. `build\netstandard1.0\CodeCoverage\coreclr` => `build\netstandard2.0\CodeCoverage\coreclr`

By upgrading `microsoft.codecoverage`, OutOfMemoryException no longer occurs,
so we believe that Fine Code Coverage itself is not the problem and `microsoft.codecoverage` is the cause.
Currently, the problem is not a problem at all.
I have looked for an issue of `microsoft.codecoverage`, but have not been able to identify the direct cause. I am sorry.

Currently, the above workaround has solved the problem,
but it would be helpful if you could update the version of the library as the tool itself.

**Comment by tonyhallett** [comment]
I will update after I have released what I am currently working on.  Be a day or two

**Comment by tYoshiyuki** [comment]
Thanks for the reply!
We would be very happy to respond to your update.

**Comment by tonyhallett** [comment]
Done.  Thanks for the information.
