### ISSUE TITLE
Feature Request: Group by Traits

### ISSUE THREAD

**Issue by moberberger** [FortuneN/FineCodeCoverage#394]
### Installed product versions
- Visual Studio: [2022 community]
- This extension: [example 1.1.209]

### Description
Please add Grouping by Traits

### Current behavior
You can group by numerous things except for traits

### Expected behavior
I would like to group results by test traits e.g. using attribute [TestCategory( "My Test Category" )]

### Side Notes
Not a bug- clearly a feature request
May not be possible / reasonable as there may be no way to understand a unit test from any other execution of the code (i.e. not from a unit test)

**Comment by tonyhallett** [comment]
> May not be possible / reasonable as there may be no way to understand a unit test from any other execution of the code (i.e. not from a unit test)

There is no connection between the coverage results and the test / tests that result in the coverage line being hit.
