### ISSUE TITLE
Any way to exclude assemblies with a wildcard ?

### ISSUE THREAD

**Issue by lde-net2** [FortuneN/FineCodeCoverage#396]
### Installed product versions
- Visual Studio: 2022 17.8.7
- This extension: latest version

### Description
In a big solution, we have few dozens of tests projects
All named like their parent project, suffixed with "Tests"..
eg: Company.Project.Tests  => assembly Company.Project.Tests.dll

is there a way to exclude them all in the assemblies exclude config with *.Tests  ??

### Steps to recreate
added config "Tests", "*.Tests" in FCC options
refreshed the UI

### Current behavior
coverage is still generated for any Tests project

### Expected behavior
projects excluded by wildcard in name.

**Comment by tonyhallett** [comment]
https://github.com/FortuneN/FineCodeCoverage?tab=readme-ov-file#exclusions-and-inclusions

**Comment by lde-net2** [comment]
Thanks !! Sorry i missed it in the doc.
