### ISSUE TITLE
FCC causes conflicts in project file if it is open in the editor window when running tests (MS Coverage)

### ISSUE THREAD

**Issue by damirarh** [FortuneN/FineCodeCoverage#402]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.9.2
- This extension: 1.1.209

### Description
With MsCodeCoverage enabled, the extension causes VS to generate backup copies of `.csproj` file because of conflicts if that project file is opened in the editor window.

### Steps to recreate
1. Enable MsCodeCoverage mode for the extension.
2. Open a project with some tests.
3. Open the `.csproj` file of the project in the editor window.
4. Run the tests at least twice

### Current behavior
During the second test run VS show a warning because of a conflict in the project file and creates a backup file in the folder.
![image](https://github.com/FortuneN/FineCodeCoverage/assets/1292060/7cc0fce5-586a-40f1-bd7c-24eeb27b8fec)

### Expected behavior
The extension should work as it does when the `.csproj` file is not open in the editor window, i.e. no conflicts in the project file should happen.

### Side Notes
- Screen recording of current behavior:

![devenv_6hGVPc47k1](https://github.com/FortuneN/FineCodeCoverage/assets/1292060/be4d4dda-8e6f-4e5d-b8c4-54f8f02dc323)

- Link to a repository with the code used in the screen recording above: https://github.com/DamirsCorner/20240322-dotnet-extension-method

- Contents of the Output window for FCC for the screen recording above: [FCC.log](https://github.com/FortuneN/FineCodeCoverage/files/14547138/FCC.log)

**Comment by tonyhallett** [comment]
It is necesary to write to the project file.  If you do not like this functionality you can create your own runsettings file or do not use ms code coverage if that is suitable.

**Comment by damirarh** [comment]
I'm perfectly fine with this functionality. My only issue are the conflicts which happen if I have the project file accidentally open when running the tests. It took me a while to figure out what was causing the conflicts all of a sudden and how to prevent them. Now that I know, it's more or less a non-issue for me. I still prefer MS Coverage to the old style which [comes with its own set of potential issues](https://www.damirscorner.com/blog/posts/20240301-FineCodeCoverageRunsTestsOnItsOwn.html).

I was hoping the conflicts were caused by some kind of race condition with the editor window, causing it to think that it contains unsaved changes. And could therefore be circumvented. If not, it might be a good idea to document the behavior in a troubleshooting section. It's likely that others will encounter it as well.

**Comment by tonyhallett** [comment]
I will add to the readme that FCC writes to the project file and mention the warning you encountered.
Although I do not get any warning when running tests with the test project file open.

**Comment by tonyhallett** [comment]
Updated readme.
