### ISSUE TITLE
Report File is invalid even though it exists

### ISSUE THREAD

**Issue by tkalp** [FortuneN/FineCodeCoverage#406]
### Installed product versions
- Visual Studio: 2022 Professional
- Version 1.1.213

### Description
I am trying to get a code coverage report after my tests are run. I can see that the coverage is being correctly outputted in the FCC output window but when it tries to fetch the .xml coverage data, it is showing that `The report file ....` is not found. When I copy the path and paste it to my terminal I am able to see the .xml file and it exists

### Steps to recreate
- Unsure how to create it other than by running the tool

**Comment by tonyhallett** [comment]
Can you show the full output from the FCC Output window pane. Are you providing a runsettings ? Are you using ms code coverage. Can you show your project ? If not can you reproduce in one that you can.

**Comment by tonyhallett** [comment]
The issue title says ... Invalid.  Is it invalid or not found ?

**Comment by tonyhallett** [comment]
Can you provide some further information otherwise will have no choice but to close this.
