### ISSUE TITLE
Coverage and Summary tabs not updating when tests run, remaining empty. Margins not displaying coverage either

### ISSUE THREAD

**Issue by MythosPantheon** [FortuneN/FineCodeCoverage#409]
### Installed product versions
- Visual Studio: 2022 Professional, 2022 Community
- This extension: 1.1.214, 1.1.194

### Description
FCC successfully generates the report when tests are run, but coverage and summary tabs are left empty, with Inline representation not showing either

### Steps to recreate
1. Create a project (tried with both .net 7.0 and framework 4.8)
2. Create a method and a test (MSTest or XUnit)
3. Run the test
4. Coverage and Summary tabs remain empty, log does update

### Current behavior
Coverage tab is completely empty while all rows in the Summary have a value of 0 (except line coverage which is empty). Inline representation is not showing either

### Expected behavior
Coverage should display the line and branch coverage, summary should have values other than 0 and margins should be green, yellow or red

### Side Notes
- This has been seen on 2 different machines, with slight differences in the settings, including the version. The most up to date machine was fine on 08/03/2024, with this issue noticed on 12/03/2024
- Changing settings and reinstalling had no effect
- Changing repo branch and back again occasionally causes it to display the coverage and summary tabs correctly, and on one occasion the margin also worked
- File attached is the FCC output for a project with a single unit test that exhibited this issue, images are of the Coverage log, summary and coverage tabs after test is run
[CodeCoverageOutput.txt](https://github.com/FortuneN/FineCodeCoverage/files/14745908/CodeCoverageOutput.txt)
![image](https://github.com/FortuneN/FineCodeCoverage/assets/36916908/8dc3175b-663f-49c6-bdeb-e70968406b9a)
![image](https://github.com/FortuneN/FineCodeCoverage/assets/36916908/d5bdd73a-9570-4d20-a750-37f674277f72)
![image](https://github.com/FortuneN/FineCodeCoverage/assets/36916908/fc61e175-02b8-4af1-8416-b051dfc512e2)

**Comment by WyrmUK** [comment]
I have a similar issue with Visual Studio Enterprise 2022 (64-bit) 17.9.4 and FCC 1.1.214.
The margins don't show the coverage at all.
The coverage and summary tabs seem to work for me.

**Comment by tonyhallett** [comment]
@MythosPantheon 
Please can you share the solution with the project with a single unit test. 

@WyrmUK I am going to need more to go on.  
Have you turned it off by chance ?
<img width="445" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/f9167dfc-ea16-42e8-9606-a036f70e459c">

**Comment by MythosPantheon** [comment]
[Sandbox.zip](https://github.com/FortuneN/FineCodeCoverage/files/14775136/Sandbox.zip)

I have checked the settings and mine match the image you have shared

**Comment by tonyhallett** [comment]
@MythosPantheon You have not included the test project

**Comment by MythosPantheon** [comment]
Apologies

[TestProject1.zip](https://github.com/FortuneN/FineCodeCoverage/files/14775316/TestProject1.zip)

**Comment by tonyhallett** [comment]
@MythosPantheon 

Perhaps you have set ShowCoverageInGlyphMargin false.

![image](https://github.com/FortuneN/FineCodeCoverage/assets/11292998/4bcdfb50-47c6-4626-89e8-b5117daf4f2d)

**Comment by MythosPantheon** [comment]
ShowCoverageInGlyphMargin is set to true, and doesn't explain why the coverage and summary tabs are not showing

**Comment by MythosPantheon** [comment]
Settings are as shown

![image](https://github.com/FortuneN/FineCodeCoverage/assets/36916908/d3580812-6b13-448a-93e9-6c94802c4f3d)
![image](https://github.com/FortuneN/FineCodeCoverage/assets/36916908/dc3ccc51-11bc-4631-b8b5-28cb4ec8d226)

**Comment by WyrmUK** [comment]
I'm using the same settings as MythosPantheon except:
IncludeTestAssembly: True
RunMsCodeCoverage: No

Looking closer, the margin glyphs are actually showing, but very faintly (I had to change display settings on the monitor). I suspect that might be because I am not using Dark mode.
![image](https://github.com/FortuneN/FineCodeCoverage/assets/10153741/10777eed-198e-4399-8cfd-037629877be4)

**Comment by tonyhallett** [comment]
@WyrmUK 
> Looking closer, the margin glyphs are actually showing, but very faintly (I had to change display settings on the monitor). I suspect that might be because I am not using Dark mode (will raise in a separate issue).

You control the colours yourself in Fonts and Colors.
<img width="710" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/c79c9002-6dab-4df2-8b49-a4d5458c0f9a">

**Comment by tonyhallett** [comment]
@MythosPantheon 

The project you provided has launchSettings.json
`
{
  "profiles": {
    "WSL": {
      "commandName": "WSL2",
      "distributionName": ""
    }
  }
}
`

Could this be causing the problem ?

From the FCC Output Window Pane can you check again that there are no errors and that the coverage.xml, Cobertura.xml
and index.html files have been generated.  Perhaps diagnostics.log has some information.

**Comment by MythosPantheon** [comment]
Unfortunately it isn't responsible, I am seeing this issue across multiple solutions, most of which don't have that file.

The FCC Output Window is not showing any errors and the 3 files are being generated correctly

**Comment by tonyhallett** [comment]
Can you switch to RunMsCodeCoverage Yes and see if that makes any difference.

**Comment by MythosPantheon** [comment]
Switching RunMsCodeCoverage to Yes has not made a difference

**Comment by tonyhallett** [comment]
Can you open the index.html file in the browser

**Comment by MythosPantheon** [comment]
There are 2 versions of index.html in coverage-tool-output, both open fine and appear identical

![image](https://github.com/FortuneN/FineCodeCoverage/assets/36916908/2d6d6bb1-b7e1-470c-bf36-a3a19b3c7539)

**Comment by tonyhallett** [comment]
I am afraid I cannot help any further without debugging FCC on your machine.

> Visual Studio: 2022 Professional, 2022 Community
This extension: 1.1.214, 1.1.194

Is this occuring for both 1.1.214 and 1.1.194 ?

> This has been seen on 2 different machines, with slight differences in the settings, including the version. The most up to date machine was fine on 08/03/2024, with this issue noticed on 12/03/2024

I cannot see how the code that I merged in from the 8-12 of March could have had an impact.

Is there anything unusual about the machines you are running ?  Has there been any other change at your end ?

**Comment by MythosPantheon** [comment]
I have experienced the issue on 2 machines, one with 2022Professional, with 1.1.214, and the other with 2022 community with 1.1.194. The latter when trying to replicate the issue.

I was using FCC without issue on the 8th, but came back on the 12th to find this issue. There is no change that I am aware of that happened on both machines in that time frame

**Comment by tonyhallett** [comment]
Are you using the same machine for both Professional and Community ?

**Comment by MythosPantheon** [comment]
No Professional is on one machine, community on the other

**Comment by tonyhallett** [comment]
Is Community working still ?

**Comment by MythosPantheon** [comment]
No, both versions have this issue

**Comment by tonyhallett** [comment]
If you are getting the same result ( lack of ) with different versions of FCC ( 1.1.194 was released Jul 2 2023) that is strange. 

FCC uses tools that are installed in C:\Users\tonyh\AppData\Local\FineCodeCoverage.  Do the machines map to the same path ?

**Comment by uLinck** [comment]
i'm with the same problem and I can't resolve :/

**Comment by tonyhallett** [comment]
@uLinck Exact same problem ?

**Comment by uLinck** [comment]
> @uLinck Exact same problem ?

yes, same config too
only the summary and coverage tabs are not updated

**Comment by tonyhallett** [comment]
@uLinck Have you been using VS Professional and Community with the same FCC versions as Mythos ?

**Comment by uLinck** [comment]
Community 17.9.5
I already managed to solve it, just uninstall the plugin and install it again.

**Comment by MythosPantheon** [comment]
I have also fortunately solved the issue. I had tried reinstalling the extension, without success. However after updating visual studio it is now working as expected
