### ISSUE TITLE
Margin Glyphs seem exceptionally faint in Blue theme

### ISSUE THREAD

**Issue by WyrmUK** [FortuneN/FineCodeCoverage#410]
### Installed product versions
- Visual Studio: 2022 Enterprise 17.9.4
- This extension: 1.1.214

### Description
The margin glyphs to show line coverage are exceptionally faint. I'm using Blue theme.

### Steps to recreate
Switch to Blue theme.

### Current behavior
The glyphs are too faint to make out properly.

### Expected behavior
The glyphs should be brighter and more noticeable.

### Side Notes
![image](https://github.com/FortuneN/FineCodeCoverage/assets/10153741/5d107f4c-374c-4d90-886c-d2490d70f0e2)

**Comment by WyrmUK** [comment]
With reference to an answer in #409 I've noticed that either another Code Coverage tool may be taking precedence, or FCC is using other settings for glyph colours. Whereas Coverage Touched Area FCC is green, the glyph colour is actually the Coverage Touched Area setting.

![image](https://github.com/FortuneN/FineCodeCoverage/assets/10153741/55727dc4-0691-459c-9909-e2bda130657e)

**Comment by tonyhallett** [comment]
From the readme

> For versions that supply the items below FCC will use these by default over the equivalent FCC items so that colours defined in themes can be used. If you wish to be consistent for the 5 available items you can set UseEnterpriseFontsAndColors to false.

> Coverage Not Touched Area
> 
> Coverage Partially Touched Area
> 
> Coverage Touched Area

**Comment by WyrmUK** [comment]
Thanks.
The confusing thing was that up to recently, the colours were fine.
I don't know if an update of FCC has changed the UseEnterpriseFontsAndColors setting to True or the way the enterprise colours are used; OR if an update to Visual Studio has added the non FCC colour settings.
However, setting UseEnterpriseFontsAndColors to False solved the issue.
