### ISSUE TITLE
No Code Coverage if the "CommunityToolkit.Maui" package is referenced

### ISSUE THREAD

**Issue by pauldavis-dwe** [FortuneN/FineCodeCoverage#413]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.214

### Description
If a project includes the "CommunityToolkit.Maui" nuget package then no code coverage results are generated

### Steps to recreate
1. Make a class library, with a class containing a public method
2. Make a test project with a test for that public method
3. Run the test and see code coverage results
4. Add the "CommunityToolkit.Maui" package to the class library
5. Run the test and see NO code coverage results

### Current behavior
No code coverage results are shown

### Expected behavior
Code coverage results should be shown

Cobertura XML: [Cobertura.xml.txt](https://github.com/FortuneN/FineCodeCoverage/files/14854205/Cobertura.xml.txt)

**Comment by tonyhallett** [comment]
Please can you post the contents of the FCC Output Window Pane.

**Comment by tonyhallett** [comment]
Also are you using ms code coverage ?

**Comment by pauldavis-dwe** [comment]
Coverage tab:
![image](https://github.com/FortuneN/FineCodeCoverage/assets/96231736/cd4d9d03-dd4e-4f74-8c1b-945cc48a19d1)

Coverage Log:
![image](https://github.com/FortuneN/FineCodeCoverage/assets/96231736/0cb045f5-1ac6-4be3-b227-4609fd9f805a)

No, I'm not using MS Code Coverage

**Comment by tonyhallett** [comment]
Please can you post the contents of the FCC Output Window Pane.

<img width="335" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/22e210af-6f59-4729-a96c-b6fdc900fa14">

**Comment by tonyhallett** [comment]
I think you'll find that this is not an issue with FCC but a limitation with MAUI

**Comment by pauldavis-dwe** [comment]
Created a repo to demonstrate: https://github.com/pauldavis-dwe/FccBugRepro.git

**Comment by tonyhallett** [comment]
Can you set RunMsCodeCoverage Yes and see if you get the same result

**Comment by pauldavis-dwe** [comment]
I thought for a moment that worked, but no. It DOES now shows coverage for the UnitTests project but not for the Core project:
![image](https://github.com/FortuneN/FineCodeCoverage/assets/96231736/5a31a336-1c27-4590-8d69-55702702d5b8)

**Comment by tonyhallett** [comment]
Does the cobertura agree with what you now see ?

**Comment by pauldavis-dwe** [comment]
The Cobertura.xml file now has lots more in it for the Dwellant.ResidentApp.Core.UnitTests "package" but nothing for Dwellant.ResidentApp.Core which is the assembly I am testing

**Comment by tonyhallett** [comment]
I have installed the Maui components and run coverage on your https://github.com/pauldavis-dwe/FccBugRepro.git
With the package reference and RunMsCodeCoverage Yes  code coverage is collected.

<img width="1175" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/319256b8-8e9e-4de9-99dd-fe2a3b81282d">

Although with coverlet it is not.  It looks like FCC will need to update the version of Coverlet that it uses to 
https://github.com/coverlet-coverage/coverlet/releases/tag/v6.0.0

Can you show the FCC Output Window Pane output just for the MS Code Coverage Run.

**Comment by tonyhallett** [comment]
Until I update coverlet you can do the following.

1. Download the package - https://www.nuget.org/api/v2/package/coverlet.collector/6.0.2
2. Change the file extension to zip
3. Extract the zip
4. Provide this directory to FCC
<img width="691" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/c3c56598-2536-4e26-931f-7a0ac7b7a02c">

--

But can you still show the FCC Output Window Pane output just for the MS Code Coverage Run.

**Comment by pauldavis-dwe** [comment]
> But can you still show the FCC Output Window Pane output just for the MS Code Coverage Run.

Sure: https://pastebin.com/Mq3UbiEF

**Comment by pauldavis-dwe** [comment]
Have tried the coverlet suggestion but still no coverage

**Comment by tonyhallett** [comment]
Sorry forget to mention that you need to add UseDataCollector project property to your test projects.

**Comment by tonyhallett** [comment]
Can you show the TestProject1-fcc-mscodecoverage-generated.runsettings in the bin directory.

**Comment by pauldavis-dwe** [comment]
Fantastic! Including UseDataCollector means I get my coverage:
![image](https://github.com/FortuneN/FineCodeCoverage/assets/96231736/3d98efb7-d53a-4fe7-bf82-ec4927dd77ba)

Here's TestProject1-fcc-mscodecoverage-generated.runsettings: 
[TestProject1-fcc-mscodecoverage-generated.runsettings.txt](https://github.com/FortuneN/FineCodeCoverage/files/14864602/TestProject1-fcc-mscodecoverage-generated.runsettings.txt)

**Comment by tonyhallett** [comment]
I recognized that when I received ms coverage I hadn't included the test project so I ran again.  Bizarrely, I cannot get any coverage today with any configuration.

Anyway, at least you can proceed with Coverlet.
