### ISSUE TITLE
Issue : FCC Always Failing to generate Report and Showing Coverage Lines when the test runs fine 

### ISSUE THREAD

**Issue by Khareem23** [FortuneN/FineCodeCoverage#416]
[FFC Log.txt](https://github.com/FortuneN/FineCodeCoverage/files/14935083/FFC.Log.txt)
### Installed product versions
- Visual Studio: [Visual Studio Professional 2022 (64-bit)  Version 17.9.5
- This extension: [FFC Version 1.1.214]
- .Net core 3.1 Unit Test Project 

### Description
It shows 0 all through in the table until i manually copy all the build files into the FFC build Ouput folder , then it shows the test coverage table in the log but not on the Coverage Report and it doesn't show line Covered as well . The attached is the log . 

The issue is failure to generate the Report 

"..coverage.xml is invalid.  File does not exist netcoreapp3.1\fine-code-coverage\coverage-tool-output\scoring.dyslexia.testresponse.resolver.UnitTests.coverage.xml' 
No report files specified. "

This file actually do exist in the stated location.

The attached fine contains the full log 

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Explain what it should be doing after it's fixed.

**Comment by tonyhallett** [comment]
Can you share the solution ?

Have you tried with ms code coverage instead ?

**Comment by tonyhallett** [comment]
Is your file system preventing FCC creating directories ?

**Comment by Khareem23** [comment]
![image](https://github.com/FortuneN/FineCodeCoverage/assets/45461899/0ca91148-4b98-4333-84dd-47a5e5f34288)
![image](https://github.com/FortuneN/FineCodeCoverage/assets/45461899/66d949da-131b-4ebe-94d4-368cd4f3a903)
![image](https://github.com/FortuneN/FineCodeCoverage/assets/45461899/0d5ca04c-b760-4f92-a9a6-05d3e913431b)
Here are the screenshots

**Comment by tonyhallett** [comment]
You can use ms code coverage with FCC. RunMsCodeCoverage Yes

**Comment by tonyhallett** [comment]
If the cobertura file does exist can you post it

**Comment by Khareem23** [comment]
> You can use ms code coverage with FCC. RunMsCodeCoverage Yes

This is the result when i did this 
![image](https://github.com/FortuneN/FineCodeCoverage/assets/45461899/a30b203f-6513-48fd-b13e-f9d052f9799f)

**Comment by Khareem23** [comment]
> cobertura file
The xml file in the coverage too output is attached below , i had to zip it so it can go through 
[SCORIN~1.ZIP](https://github.com/FortuneN/FineCodeCoverage/files/14936483/SCORIN.1.ZIP)

**Comment by tonyhallett** [comment]
I will check the zip when I am at my laptop. 

With both methods of collecting coverage there is the same issue. Perhaps we have hit windows file path length limitations. https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by Khareem23** [comment]
> I will check the zip when I am at my laptop.
> 
> With both methods of collecting coverage there is the same issue. Perhaps we have hit windows file path length limitations. https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

This didn't work 
![image](https://github.com/FortuneN/FineCodeCoverage/assets/45461899/a62eefaa-9e68-4c2e-8b69-f2a2a943be25)

Same Outcome : 
![image](https://github.com/FortuneN/FineCodeCoverage/assets/45461899/6cfb040e-28f8-457a-bd09-6efa9369a343)

But when i copy my build files into **netcoreapp3.1\fine-code-coverage\build-output** manually , i get this which is a little improvement
![image](https://github.com/FortuneN/FineCodeCoverage/assets/45461899/c7d314ef-027b-480c-a892-dad04c53e63d)

There is till no Coverage Report 
![image](https://github.com/FortuneN/FineCodeCoverage/assets/45461899/2a25f625-2960-4449-8d9d-35bb3eca8515)

and No Coverage Lines 
![image](https://github.com/FortuneN/FineCodeCoverage/assets/45461899/466f6332-652a-45ff-b399-901428e1620c)

**Comment by Khareem23** [comment]
> If the cobertura file does exist can you post it

This file was not generated

**Comment by tonyhallett** [comment]
It is due to the file path lengths.

Do you really need the unit test directory to be nested that deep ?
C:\Workspace\scoring.dyslexia.testresponse.resolver\scoring.dyslexia.testresponse.resolver\scoring.dyslexia.testresponse.resolver.UnitTests

Can you not have 
C:\Workspace\scoring.dyslexia.testresponse.resolver\scoring.dyslexia.testresponse.resolver.UnitTests ?
