### ISSUE TITLE
FCC Stopped working, and unable to figure out why

### ISSUE THREAD

**Issue by Clive321A** [FortuneN/FineCodeCoverage#422]
### Installed product versions
- VS2022 17.9.5
- This extension: [example 1.1.24]

### Description
FCC was working using MS Code coverage, I noticed that its stopped producing a report.
It generates a html ouput file, only clues are Parse = CoberturaParser, but everything else says 0

I have tried following the setup instructions , but its pretty confusing with runsettings files etc, I can see that a runsettings is getting generated each time. But im unsure how to debug whats going on

[iUW.Services.Tests-fcc-mscodecoverage-generated.runsettings.txt](https://github.com/FortuneN/FineCodeCoverage/files/15171157/iUW.Services.Tests-fcc-mscodecoverage-generated.runsettings.txt)

**Comment by tonyhallett** [comment]
Setting IncludeReferencedProjects should do it
