### ISSUE TITLE
OutputToolWindowPackage error when trying to open the tool in VS

### ISSUE THREAD

**Issue by mavendano79** [FortuneN/FineCodeCoverage#424]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.215

### Description
When trying to open the extension window, I get "OutputToolWindowPackage" package did not load correctly

### Steps to recreate
1. Install the extension
2. Go to View->Other Windows
3. Select Fine Code Coverage
4. Error appears

### Current behavior
When selecting the Fine Code Coverage window, I get the error message instead of the window

### Expected behavior
I should get the Fine Code Coverage Window.
![mavendano error message](https://github.com/FortuneN/FineCodeCoverage/assets/98706754/d537ae03-cb3f-4a24-97f7-927d1fe8a6ca)

### Side Notes
Please see attached image with the error message

**Comment by tonyhallett** [comment]
and what is the content of the activity log ?

**Comment by tonyhallett** [comment]
What versions of Visual Studio are you using ?
Have you successfully used FCC before version 1.1.215 ?

You could try https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache or update visual studio.

**Comment by mavendano79** [comment]
Updating VS 2022 to the latest versio solved this issue. Thank you very much for your input.
