### ISSUE TITLE
Test project gets modified during tests run

### ISSUE THREAD

**Issue by eugenelepekhin** [FortuneN/FineCodeCoverage#425]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: [1.1.215]

### Description
Test project gets modified during tests run if FCC is installed

### Steps to recreate
Create a new MSTest project and select .net 8.
Add it to a new local git repository and push.
Build project.
Run all tests.
Observe project file get changed in git changes window.

### Current behavior
Project file appears to be modified during test run.

### Expected behavior
Test project is intact.

### Side Notes
If you safe all files, then project file become unmodified in git changes window.

I first filed this in VS dev community, but turns out it occurred only when FCC is installed.
Here is my original bug:
https://developercommunity.visualstudio.com/t/Test-project-gets-modified-during-tests/10658708

**Comment by aaronasmith** [comment]
Isn't that due to this?

https://github.com/FortuneN/FineCodeCoverage?tab=readme-ov-file#how-to-utilize-ms-code-coverage-with-fcc-

**Comment by eugenelepekhin** [comment]
I think this is the case. In the long running tests I can see in git changes the runsettings file get added to the project and after they are finished the project get modified one more time to remove the settings.

**Comment by tonyhallett** [comment]
Fixed and added to the marketplace

**Comment by eugenelepekhin** [comment]
Thank you. It works like charm.
