### ISSUE TITLE
No Coverage due to false "tests failed" statement

### ISSUE THREAD

**Issue by Zaimatsu** [FortuneN/FineCodeCoverage#427]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.1
- This extension: 1.1.215

### Description
Coverage Log displays (Tests) Failed, despite the fact that tests passed. This results in no coverage report.

**Comment by tonyhallett** [comment]
Firstly I am assuming that you have set the FCC option for not providing coverage when tests fail. Secondly I am assuming that you are not using the option to use ms code coverage and that the tests have indeed failed. When ms code coverage is not used FCC copies DLLs to a different directory which will cause tests to fail that rely on the original dell paths.

**Comment by Zaimatsu** [comment]
Thank you for your quick response! Yes, I'm not using MS code coverage. Thank you for explaining what is happening under the hood; it's clearer now what could be causing the issue. I reported this issue because it was working fine a few weeks ago, and I'm pretty sure nothing that could affect the tests has changed in my solution. To confirm the problem, I've created a brand new solution (console app, .NET8, and NUnit3 project), and FCC fails there as well. Also, no fine-code-coverage directory is created. Maybe it has something to do with the Visual Studio upgrade I did recently? Are there any verbose logs I could check?

Output FCC:
```Fine Code Coverage 6/5/2024 9:17:04 AM: Initializing
Fine Code Coverage 6/5/2024 9:17:04 AM: Initialized
Fine Code Coverage 6/5/2024 9:18:13 AM: See option RunMsCodeCoverage for a better ( Beta ) experience.  https://github.com/FortuneN/FineCodeCoverage/blob/master/README.md
Fine Code Coverage 6/5/2024 9:18:13 AM: Coverage collected when tests finish. RunInParallel option true for immediate
Fine Code Coverage 6/5/2024 9:18:15 AM: ================================== START ==================================
Fine Code Coverage 6/5/2024 9:18:15 AM: (FCCTestTests) Failed.
Disabled
Fine Code Coverage 6/5/2024 9:18:15 AM: ================================== DONE ==================================
```

![image](https://github.com/FortuneN/FineCodeCoverage/assets/2474504/a1487a62-accb-4684-a9aa-f464c827a020)

**Comment by tonyhallett** [comment]
Looks like FCC is disabled

**Comment by Zaimatsu** [comment]
Well, you're right. It was disabled. `Tools->Options->Fine Code Coverage->General->Run(Common)` - 'Enabled' was set to false. I don't know how this could have happened. Are the Fine Code Coverage options global and shared between solutions?

**Comment by tonyhallett** [comment]
> I find it peculiar that all options have been reset.

Me too. This is the first time it has been mentioned

**Comment by Doomwhite** [comment]
> I find it peculiar that all options have been reset.

Happened to me as well
