### ISSUE TITLE
Not able to see the Tests

### ISSUE THREAD

**Issue by tawsif-patel** [FortuneN/FineCodeCoverage#428]
### Installed product versions
- Visual Studio: 2022 community
- This extension: Latest

### Description

I am not able to see the list of tests.

Replace this text with a short description
![image](https://github.com/FortuneN/FineCodeCoverage/assets/94037906/f01eace0-d7e0-4078-b1b4-35efc57529dd)

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Explain what it should be doing after it's fixed.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
The asterisk on the coverage log tab is present when coverage is being collected. If no results are shown when coverage completes then please provide some context.
