### ISSUE TITLE
Only the Unittest code coverage,  no the related project

### ISSUE THREAD

**Issue by PeterLu8888** [FortuneN/FineCodeCoverage#429]
### Installed product versions
- Visual Studio: [2022 Professional]
- This extension: [1.1.215]

### Description
When I finish the unit test, the FCC window only show the unit test coverage, not related project.

### Steps to recreate
1. Update the vs2022 to the latest version
2. Install the FCC on the vs extension page.
3. Run unit test
4. Only show unit test project

### Current behavior
Only show unit test project

### Expected behavior
Show the unit test project and the related project.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by PeterLu8888** [comment]
![image](https://github.com/FortuneN/FineCodeCoverage/assets/90822553/f35315b9-d2ff-442c-a534-8e3dbe10be6e)

**Comment by tonyhallett** [comment]
Set the option IncludeReferencedProjects to true

**Comment by PeterLu8888** [comment]
Thanks @tonyhallett 
It works. Why is it not the default set?
