### ISSUE TITLE
Hide coverage indicators

### ISSUE THREAD

**Issue by ekolis** [FortuneN/FineCodeCoverage#432]
### Installed product versions
- Visual Studio: 2022 Community
- This extension: 1.1.215

### Description
I would like an option to hide the code coverage indicators in the code files, temporarily until I either run tests again or turn it back on. They can really clutter up the vertical scroll bar in the code editor, making it hard to read, if a file has little to no test coverage.

**Comment by tonyhallett** [comment]
Functionality added.  
There is a button provided 
<img width="248" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/608396d6-ee82-4cbf-a3ca-fdb2a2c10a0a">

note that I applied the keyboard shortcut.

<img width="520" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/5084648c-fc2e-48bb-8628-71f89ab0cb85">
