### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by ScottyLightnin** [FortuneN/FineCodeCoverage#436]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: [N/A

### Description
Are there any plans to deploy this extension for ARM devices? All the new Snapdragon Copilot + PCs are ideal for running Visual Studio on ARM, but extensions need to be modified to work.

**Comment by craigktreasure** [comment]
Found some other issues that are certainly related (#352 and #322). Looks like support was rejected until the maintainer has ARM hardware. For what it's worth, I was able to get it to build locally and am currently using it on my Surface Pro 11 (run ARM64). I don't know if my PR will be accepted or not, but others are welcome to try out my changes and report back.

**Comment by tonyhallett** [comment]
@ScottyLightnin available on the marketplace

**Comment by ScottyLightnin** [comment]
perfect, working well from the marketplace on ARM.
Well done @craigktreasure and thanks @tonyhallett
