### ISSUE TITLE
Coverage details not displaying correctly in the window

### ISSUE THREAD

**Issue by Abhijith-Pradeep** [FortuneN/FineCodeCoverage#441]
### Installed product versions
- Visual Studio: 2022 Professional, 17.10.2
- This extension: 1.1.220

### Description
Details not showing correctly after running tests, tried reinstalling the extension but in vain.

### Steps to recreate
The behavior starts upon VS startup

![image](https://github.com/user-attachments/assets/81d36c01-42c4-48e7-8318-29a85b3d7a73)

**Comment by tonyhallett** [comment]
Arm64 ?

**Comment by tonyhallett** [comment]
Can you install the latest version of Visual Studio - 17.10.4

**Comment by Abhijith-Pradeep** [comment]
> Arm64 ?

no it's x64

**Comment by Abhijith-Pradeep** [comment]
> Can you install the latest version of Visual Studio - 17.10.4

let me try that

**Comment by tonyhallett** [comment]
Did FCC work after updating ?

**Comment by tonyhallett** [comment]
Please reopen if issue persists and you are available to determine the cause.
