### ISSUE TITLE
Getting Fine Code Coverage 7/26/2024 4:04:30 AM: Failed Initialization after running test explorer

### ISSUE THREAD

**Issue by wzewde** [FortuneN/FineCodeCoverage#445]
### Installed product versions
- Visual Studio: [example 2022Professional]
- This extension: [example 1.1.222]

### Description
Fine Code Coverage 7/26/2024 4:04:30 AM: Initializing
Fine Code Coverage 7/26/2024 4:04:30 AM: Failed Initialization
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at FineCodeCoverage.Engine.OpenCover.OpenCoverUtil.Initialize(String appDataFolder, CancellationToken cancellationToken)
   at FineCodeCoverage.Engine.CoverageUtilManager.Initialize(String appDataFolder, CancellationToken cancellationToken)
   at FineCodeCoverage.Engine.FCCEngine.Initialize(CancellationToken cancellationToken)
   at FineCodeCoverage.Core.Initialization.Initializer.<InitializeAsync>d__13.MoveNext()
Fine Code Coverage 7/26/2024 4:04:35 AM: Skipping TestExecutionStarting as FCC not initialized
Fine Code Coverage 7/26/2024 4:04:36 AM: Skipping TestExecutionFinished as FCC not initialized

### Steps to recreate
1. Running test explorer
2. Go to FCC output window

### Current behavior
Not working

### Expected behavior
Should show code coverage

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
This suggests that FCC has been unable to unzip files in to your AppData folder.
Can you see if this exists `C:\Users\xxxx\AppData\Local\FineCodeCoverage\openCover` ?
Is this ARM64 Visual Studio ?

**Comment by wzewde** [comment]
Thanks for the hint @tonyhallett, I deleted the C:\Users\xxxx\AppData\Local\FineCodeCoverage\openCover folder, uninstalled Fine Code Coverage and installed again. It started working after that.
