### ISSUE TITLE
Can't install on VS 2022 Professional 

### ISSUE THREAD

**Issue by DoctaJonez** [FortuneN/FineCodeCoverage#448]
### Installed product versions
- Visual Studio: [2022 Professional]
- This extension: [example 1.1.223]

### Description
Installation fails with VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

### Steps to recreate
1. Attempt to install for VS2022 Professional

### Current behavior
Fails to install

### Expected behavior
Installs correctly

### Side Notes
The manifest lists Community as the only supported edition of VS.  This is supported by the failure install log:

01/08/2024 11:13:39 - 	Supported Products : 
01/08/2024 11:13:39 - 		Microsoft.VisualStudio.Community
01/08/2024 11:13:39 - 			Version : [17.10,18.0)
01/08/2024 11:13:39 - 			ProductArchitecture : amd64
01/08/2024 11:13:39 - 		Microsoft.VisualStudio.Community
01/08/2024 11:13:39 - 			Version : [17.10,18.0)
01/08/2024 11:13:39 - 			ProductArchitecture : arm64

**Comment by tonyhallett** [comment]
It is installable in Visual Studio Professional.  What version of Visual Studio do you have ? Where are you obtaining the vsix from ?

**Comment by DoctaJonez** [comment]
Updating to 17.10 has resolved it. I'm going to close this issue, thank you for your help.

**Comment by tonyhallett** [comment]
no problem

**Comment by DerReparator** [comment]
I had the same problem with Visual Studio version 17.9.2.

Unfortunately, I cannot easily update to 17.10.

My question is: Is the big version bump from 3 weeks ago (-> https://github.com/FortuneN/FineCodeCoverage/commit/5ccad9106b629cf85b534cc6eb072da4559f3f13) from 17.0 -> 17.10 really necessary?

Thank you for any information!

**Comment by tonyhallett** [comment]
@DerReparator 
The manifest matches the version of the Sdk package reference updated in the pull request. Is it really necessary? Not to the latest version but possibly a required version for Arm support.

**Comment by DerReparator** [comment]
Okay, thank you for the quick reply!
I will use a slightly older version of FCC until I can upgrade to 17.10 and beyond 😀 
Just wanted to make sure that the requirement was necessary.

**Comment by tonyhallett** [comment]
@DerReparator 
As I said, probably not necessarily. Fork the repo and build the vsix.

**Comment by tlunsfordCXP** [comment]
For me, installing it by launching it from Windows Explorer resulted in the same error. I then went successfully installed it by opening Visual Studio and searching for "Fine Code Coverage" in the Extensions menu. In other words, it seems that installing from within Visual Studio works successfully (or the second try is what fixed it).
