### ISSUE TITLE
Multi-framework project does not work

### ISSUE THREAD

**Issue by tonyhallett** [FortuneN/FineCodeCoverage#45]
### Installed product versions
- Visual Studio: [Community 16.8.3]
- This extension: [example 1.1.39]

### Description
There are two major issues with regard to multi-frameworks sdk style project.
1) FileSynchronization can fail to copy necessary files - test does not run and error messages
https://github.com/FortuneN/FineCodeCoverage/blob/b803afaafc007df6b69534630b7e5ca280e7d78a/FineCodeCoverage/Core/FileSynchronization/FileSynchronizationUtil.cs#L24

There are two reasons for this.
The main issue is that the destination folder for frameworks in multi framework is the same - e.g .../Debug/fine-code-coverage

The second is the equality comparison - the hash code can be the same for different framework files.
[ComparableFile](https://github.com/FortuneN/FineCodeCoverage/blob/6b567c20a62aca5905caed3ac993c68ad1da37e7/FineCodeCoverage/Core/Utilities/ComparableFile.cs)
`
public ComparableFile(FileInfo fileInfo, string relativePath)
{
	FileInfo = fileInfo;
	RelativePath = relativePath;
	hashCode = string.Format("{0}|{1}|{2}", RelativePath, FileInfo.Length, FileInfo.LastWriteTimeUtc.Ticks).GetHashCode();
}
`
This could be resolved by using the full path although this solution does not resolve issue 2.

2) Running tests for multiple frameworks does not merge the results.
This again is due to shared folder.
The problematic code https://github.com/FortuneN/FineCodeCoverage/blob/fc44d906e0d761f718d111e603b305610bfebf38/FineCodeCoverage/Impl/TestContainerDiscoverer.cs#L153

So when the FCCEngine.ReloadCoverage
`

project.WorkOutputFolder = Path.Combine(project.WorkFolder, "_outputfolder");
project.CoverToolOutputFile = Path.Combine(project.WorkOutputFolder, "_cover.tool.xml");
...
var coverOutputFiles = projects
				.Select(x => x.CoverToolOutputFile)
				.ToArray();
ReportGeneratorUtil.RunReportGenerator(coverOutputFiles, darkMode, out var unifiedHtmlFile, out var unifiedXmlFile, true);
`
The report generator is asked for a unified xml file for the same ( last generated) file path.

The solution would be to replace
`project.WorkFolder = Path.Combine(Path.GetDirectoryName(defaultOutputFolder), "fine-code-coverage"); `
with
```
var legacyWorkFolder = Path.Combine(Path.GetDirectoryName(defaultOutputFolder), "fine-code-coverage");
try
{
	Directory.Delete(legacyWorkFolder, true);
}
catch
{
	// ignore
}
project.WorkFolder = Path.Combine(Path.GetDirectoryName(defaultOutputFolder), $"fine-code-coverage-{project.ProjectName}");
projects.Add(project);
```

**Comment by FortuneN** [comment]
Please attach a repro for this case.

**Comment by tonyhallett** [comment]
https://github.com/tonyhallett/CoverageIssueDemo
3 projects
Test project and tested project both multi framework .Net Core / .Net Framework.  
A Project that demonstrates 

> FileSynchronization can fail to copy necessary files 

Here you can see LastWriteTimeUtc.Ticks is the same for both Net Core and Net Framework.
![image](https://user-images.githubusercontent.com/11292998/102986103-2f446b00-4508-11eb-848c-e007bcc0c6c7.png)
Note that this is not always the case.

Running both tests
![image](https://user-images.githubusercontent.com/11292998/102986385-a24de180-4508-11eb-8921-854f47d8a766.png)

This is the build output I have bolded the issue with the shared output folder.  Given that the WorkFolder is the same the report generator is asked to merge a file with itself.  

========== Build: 0 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Ensure Work Folder Exists (Test (net472))

Fine Code Coverage : Synchronize Output Files To Work Folder (Test (net472))

Fine Code Coverage : Run Coverage Tool (Test (net472))

Fine Code Coverage : Coverlet Run (Test (net472)) Arguments 
"C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\Test.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
**--output "C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml"**
--targetargs "test  ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\Test.dll"" --nologo --blame --results-directory ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder"" --diag ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder/diagnostics.log""  "

Fine Code Coverage : Coverlet Run (Test (net472))
C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage>"C:\Users\tonyh\AppData\Local\FineCodeCoverage\coverlet\coverlet.exe" "C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\Test.dll" --format "cobertura" --exclude-by-file "**/Migrations/*" --exclude-by-attribute "GeneratedCode" --target "dotnet" --threshold-type line --threshold-stat total --threshold 0 --output "C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml" --targetargs "test  ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\Test.dll"" --nologo --blame --results-directory ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder"" --diag ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder/diagnostics.log""  "  1>"C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\0c768847.bat.output"
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\diagnostics.log
A total of 1 test files matched the specified pattern.
Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 17 ms - Test.dll (net472)

Calculating coverage result...
  Generating report 'C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml'
+-------------------+------+--------+--------+
| Module            | Line | Branch | Method |
+-------------------+------+--------+--------+
| CoverageIssueDemo | 50%  | 100%   | 50%    |
+-------------------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 50%  | 100%   | 50%    |
+---------+------+--------+--------+
| Average | 50%  | 100%   | 50%    |
+---------+------+--------+--------+

Fine Code Coverage : Ensure Work Folder Exists (Test (netcoreapp3.1))

Fine Code Coverage : Synchronize Output Files To Work Folder (Test (netcoreapp3.1))

Fine Code Coverage : Run Coverage Tool (Test (netcoreapp3.1))

Fine Code Coverage : Coverlet Run (Test (netcoreapp3.1)) Arguments 
"C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\Test.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
**--output "C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml"**
--targetargs "test  ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\Test.dll"" --nologo --blame --results-directory ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder"" --diag ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder/diagnostics.log""  "

Fine Code Coverage : Coverlet Run (Test (netcoreapp3.1))
C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage>"C:\Users\tonyh\AppData\Local\FineCodeCoverage\coverlet\coverlet.exe" "C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\Test.dll" --format "cobertura" --exclude-by-file "**/Migrations/*" --exclude-by-attribute "GeneratedCode" --target "dotnet" --threshold-type line --threshold-stat total --threshold 0 --output "C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml" --targetargs "test  ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\Test.dll"" --nologo --blame --results-directory ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder"" --diag ""C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder/diagnostics.log""  "  1>"C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\1b718f20.bat.output"
Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\diagnostics.log
A total of 1 test files matched the specified pattern.
Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 5 ms - Test.dll (netcoreapp3.1)

Calculating coverage result...
  Generating report 'C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml'
+-------------------+------+--------+--------+
| Module            | Line | Branch | Method |
+-------------------+------+--------+--------+
| CoverageIssueDemo | 50%  | 100%   | 50%    |
+-------------------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 50%  | 100%   | 50%    |
+---------+------+--------+--------+
| Average | 50%  | 100%   | 50%    |
+---------+------+--------+--------+

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder"
**"-reports:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml;C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml"**
"-reporttypes:Cobertura"

Fine Code Coverage : ReportGenerator Run [reporttype:Cobertura]
C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder>"C:\Users\tonyh\AppData\Local\FineCodeCoverage\reportGenerator\reportgenerator.exe" "-targetdir:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder" "-reports:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml;C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml" "-reporttypes:Cobertura"  1>"C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\3ab7cde8.bat.output"
2020-12-23T10:22:11: Arguments
2020-12-23T10:22:12:  -targetdir:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder
2020-12-23T10:22:12:  -reports:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml;C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\_cover.tool.xml
2020-12-23T10:22:12:  -reporttypes:Cobertura
2020-12-23T10:22:12: Writing report file 'C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\Cobertura.xml'
2020-12-23T10:22:12: Report generation took 0.1 seconds

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder"
"-reports:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\cobertura.xml"
"-plugins:C:\USERS\TONYH\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_44B31A9D\EXTENSIONS\JWAMYQ01.WV1\ReportGeneratorPlugins.dll"
"-reporttypes:FccDark"

Fine Code Coverage : ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder>"C:\Users\tonyh\AppData\Local\FineCodeCoverage\reportGenerator\reportgenerator.exe" "-targetdir:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder" "-reports:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\cobertura.xml" "-plugins:C:\USERS\TONYH\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_44B31A9D\EXTENSIONS\JWAMYQ01.WV1\ReportGeneratorPlugins.dll" "-reporttypes:FccDark"  1>"C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\94f9a14e.bat.output"
2020-12-23T10:22:12: Arguments
2020-12-23T10:22:12:  -targetdir:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder
2020-12-23T10:22:12:  -reports:C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\cobertura.xml
2020-12-23T10:22:12:  -plugins:C:\USERS\TONYH\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_44B31A9D\EXTENSIONS\JWAMYQ01.WV1\ReportGeneratorPlugins.dll
2020-12-23T10:22:12:  -reporttypes:FccDark
2020-12-23T10:22:12: Writing report file 'C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage\_outputfolder\index.html'
2020-12-23T10:22:12: Report generation took 0.2 seconds

Fine Code Coverage : ================================== DONE ===================================

The report is for .Net Core, the one that was run last.
I would expect it to be a merge of the two - which would be 100% coverage.

![image](https://user-images.githubusercontent.com/11292998/102987057-b34b2280-4509-11eb-8fe6-c1f4da7da4ff.png)

**Comment by FortuneN** [comment]
Thank you for the repro.

**Synchronization**

> FileSynchronization can fail to copy necessary files
> Here you can see LastWriteTimeUtc.Ticks is the same for both Net Core and Net Framework.

I disagree.
VS compiles the dll once (hence commonLastWriteTimeUtc) and copies it to each of the framework folders (net472, netcoreapp3.1).
As such, it IS the same file and should not be deleted and recopied by the synchronization

**Shared output folder**

> This is the build output I have bolded the issue with the shared output folder.

I agree
The output folder is the same (but that's not necessarily what hurts us).  

> Given that the WorkFolder is the same the report generator is asked to merge a file with itself.
> C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage_outputfolder_cover.tool.xml;C:\Users\tonyh\Source\Repos\CoverageIssueDemo\Test\bin\Debug\fine-code-coverage_outputfolder_cover.tool.xml

I agree.
We are asking report generator to merge the same file. LOL!

**The problem (i think)**

Because the cover output file (_cover.tool.xml) does not exist in either of the framework folders (net472, netcoreapp3.1), it gets deleted during each file synchronization.
Note though that it gets **deleted** by the synchronization and **is not overwritten** by the cover tool (Coverlet/OpenCover) for each respective framework.

**The solution (i think)**

We could solve this by
1) Making the cover file (_cover.tool.xml) name unique by introducing some random text. I considered using the project name but i don't like the brackets, spaces and other unpredictable 'interesting' characters that may be in the file name.
2) Read from disk and retain the content of the cover file (_cover.tool.xml) in the CoverageProject object after running the cover tool
3) Write out all the files back to disk that have been deleted by subsequent synchronizations since we have the contents in memory (also, the fact that they are uniquely name means we can have them side by side)

**Solution code**

These changes go into the FCCEngine class

1)  Make the cover file (_cover.tool.xml) name unique by introducing some random text

```cs
project.CoverToolOutputFile = Path.Combine(project.WorkOutputFolder, $"_cover.tool.{Guid.NewGuid().ToString().Split('-').First().ToLower()}.xml");
```
2) Read from disk and retain the content of the cover file (_cover.tool.xml)

```cs
project.CoverToolOutputFileContent = File.ReadAllText(project.CoverToolOutputFile);
```

3) Write out all the files back to disk that have been deleted 

```cs
var coverOutputFiles = projects
	.Select(x =>
	{
		// ensure the cover file exists on disk (in multi-framework projects the file gets wiped out while processing each framework)

		if (!File.Exists(x.CoverToolOutputFile))
		{
			File.WriteAllText(x.CoverToolOutputFile, x.CoverToolOutputFileContent);
		}

		// return path

		return x.CoverToolOutputFile;
	})
	.ToArray();
```

4) New property in CoverageProject

```cs
public string CoverToolOutputFileContent { get; set; }
```

**[Download Code](https://github.com/FortuneN/FineCodeCoverage/files/5736478/code.zip)**

**Comment by tonyhallett** [comment]
> Note though that it gets deleted by the synchronization and is not overwritten by the cover tool (Coverlet/OpenCover) for each respective framework.

I am well aware of the guilty source code.

> I disagree.VS compiles a dll once (hence commonLastWriteTimeUtc) and copies it to each of the framework folders (net472, netcoreapp3.1).
As such, it IS the same file and should not be deleted and recopied by the synchronization

Consider this, we change the code to the following
`
public class CoverMe
    {
        public void Method1()
        {
        }

        public void Method2()
        {
        }

        
#if NET472
        public void NetFramework(){

        }
#else
         public void NetCore()
        {

        }
#endif

        
    }
`
Are you telling me that the dlls are the same ?

Believe me not copying the dll because the hash code is the same is an issue.
In the project I was testing I selected all .Net Core and all .Net framework tests in test explorer and run them.  All ran and passed.  Yet the tests that Fine Code Coverage ran passed for one and had exceptions for the other.
Deleting the contents of the fine-code-coverage folder and then running the tests that just failed passed successfully.

----


As an aside, is it necessary to copy the files ? 

Coverlet instruments the dlls then returns them to their original state
https://github.com/coverlet-coverage/coverlet/blob/fcb2ec039ff556ddb63d6f32e3c2da64ea4e7666/src/coverlet.core/Coverage.cs#L257

**Comment by FortuneN** [comment]
I've considered that code
Even when the code is identical the synchronization works (tested by running the FileSynchronization project).

```cs
#if NET472
public void AB(){}
#else
public void AB(){}
#endif
``` 

> Believe me not copying the dll because the hash code is the same is an issue.

I believe you.
I understand that the synchronization algorithm is not perfect (we are comparing characteristics about the files and not the contents of the files).
This was a performance call as generating file hashes costs more (IO, CPU, RAM and time).

Other hand, using the whole path guarantees that all files will be wiped out and replaced in the synchronization.
While this would work, it's not really synchronization. That's as good as deleting the folder and re-copying afresh.
The benefit of synchronization is not incurring IO, CPU, RAM and time cost on files that haven't changed, making the process fast (after the first time). 

> As an aside, is it necessary to copy the files ?

Consider these 'phases'  : BUILD -> TEST -> COVERAGE.

Let say we don't copy/synchronize files elsewhere.

If the user were to re-build while were in the (previous) COVERAGE phase, the re-build would fail because the coverage process would still be locking dlls that VS has to clear and re-write.

Working on alternate copies of the files allows the builds to always work.
You will have noticed that i spawn thread for the coverage process; This also is in the spirit of not hindering the normal VS processes.

During the TEST phase i can stop the COVERAGE process **_reloadCoverageThread?.Abort()** and that is because i know when tests have started running.
I don't know when the build has started. Perhaps if we can detect that event we could interrupt the (previous) COVERAGE phase and that way guarantee that BUILD and COVERAGE don't run at the same time and therefore have no need to copy/synchronize  files.

**Comment by FortuneN** [comment]
Soooooooo

I have hooked up to the the BUILD event and can stop the coverage process from there.
It's running smoothly; The BUILD phase never fails (i have tried so many times to get it to fail)

- No more file synchronization
- No more shared 'fine-code-coverage' folder

Nice catch.
I'm holding back from pushing up the commit and until i get your opinion

**Comment by tonyhallett** [comment]
> I've considered that code

Ok, does that mean that you have changed your opinion on.

> As such, it IS the same file and should not be deleted and recopied by the synchronization

Which logically leads to a required change in the imperfect synchronization algorithm given that

> comparing characteristics about the files and **not the contents of the files**.

----

> Even when the code is identical the synchronization works i.e. replaces the file (tested by running the FileSynchronization project).

#if NET472
public void AB(){}
#else
public void AB(){}
#endif

As I said before, it is not always the case that the hash code is the same, it is intermittent.  For me, if the first build came as a result of running the tests then the hash codes of the .Net Framework and the .Net Core SUT dll are the same.

The image I provided shows that it occurred for me.  Of course this is not the same as seeing on your own machine, but I will show you it occurring for me again, right now at 00:21.  I could do this in photoshop but come on !
So delete the contents of the bin and run the tests to to build CoverageIssueDemo.

![image](https://user-images.githubusercontent.com/11292998/103045853-fd6deb80-457d-11eb-90c0-5a0f9528df8b.png)

**Comment by tonyhallett** [comment]
Are you saying that you are now removing file synchronization completely ?

Hooking in to the build event in visual studio would be sufficient if the build only occurred via vs.  
Command line builds would still give locking issues though.

**Comment by FortuneN** [comment]
> Hooking in to the build event in visual studio would be sufficient if the build only occurred via vs.
> Command line builds would still give locking issues though.

True. But that issue would occur if say you built the same project in multiple VS instances or vs code or msbuild CLI or dotnet-build e.t.c simultaneously.
I don't think we need to worry about that

But hey, if you are happy i will proceed with the removal of synchronization.
We will now deal with output in the respective framework folders.

**Comment by tonyhallett** [comment]
Agreed, you could add a disclaimer but I think it is safe to proceed.

Does OpenCover do the same as Coverlet and put back the original uninstrumented assembly ? Does it matter ?

I have one other idea for an improvement for Coverlet cover that you may be interested in.  I will add my idea and preliminary investigation tomorrow to a new issue and you can give me your thoughts when you get the time, no rush it is Christmas after all.  Of course code fixes and features are addictive for the challenges that they pose but time to let the brain relax for a few days.

I wish you a Happy Christmas and no doubt will converse soon.

Tony

**Comment by FortuneN** [comment]
> ... you could add a disclaimer ...
> Does OpenCover do the same as Coverlet and put back the original uninstrumented assembly ? Does it matter ?

Well, the dlls used by OpenCover or Coverlet are in the test project's bin/Debug (VS copies the files there during BUILD).
The only process that cares about those files is the Test process itself and it runs before we do COVERAGE stuff.
So it does not matter.

> I have one other idea for an improvement

Awesome!

Happy Christmas to you too buddy!
