### ISSUE TITLE
This extension is not installable on any of the currently installed products.

### ISSUE THREAD

**Issue by CSRafaelOliveira** [FortuneN/FineCodeCoverage#450]
### Installed product versions
- Visual Studio: Visual Studio Professional 2022 (64 bits) - Version 17.8.5
- This extension: v1.1.223

### Description
I love this extension, and it was very helpful in my work when performing unit tests in Visual Studio 2019, and it worked very well. Now, when trying to install it in Visual Studio 2022 Professional version 17.8.5, I get the following error:

19/08/2024 17:09:27 - Microsoft VSIX Installer
19/08/2024 17:09:27 - -------------------------------------------
19/08/2024 17:09:27 - vsixinstaller.exe version:
19/08/2024 17:09:27 - 17.9.3180+083a582996
19/08/2024 17:09:27 - -------------------------------------------
19/08/2024 17:09:27 - Command line parameters:
19/08/2024 17:09:27 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\cs389682\Downloads\FineCodeCoverage2022 (4).vsix
19/08/2024 17:09:27 - -------------------------------------------
19/08/2024 17:09:27 - Microsoft VSIX Installer
19/08/2024 17:09:27 - -------------------------------------------
19/08/2024 17:09:27 - Initializing Install...
19/08/2024 17:09:27 - Pesquisando produtos aplicáveis...
19/08/2024 17:09:28 - Produto instalado encontrado - Visual Studio Professional 2019
19/08/2024 17:09:28 - Produto instalado encontrado - Visual Studio Professional 2022
19/08/2024 17:09:28 - Produto instalado encontrado - Local Global
19/08/2024 17:09:28 - Detalhes da Extensão...
19/08/2024 17:09:28 - 	Identifier         : FineCodeCoverage2022.ad53fb28-7a11-4465-a27a-3550499ea4a1
19/08/2024 17:09:28 - 	Name               : Fine Code Coverage
19/08/2024 17:09:28 - 	Author             : Fortune Ngwenya
19/08/2024 17:09:28 - 	Version            : 1.1.223
19/08/2024 17:09:28 - 	Description        : Visualize unit test code coverage easily for free in Visual Studio Community Edition (and other editions too)
19/08/2024 17:09:28 - 	Locale             : en-US
19/08/2024 17:09:28 - 	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage
19/08/2024 17:09:28 - 	InstalledByMSI     : False
19/08/2024 17:09:28 - 	SupportedFrameworkVersionRange : [4.7,)
19/08/2024 17:09:28 - 	SignatureState     : Unsigned
19/08/2024 17:09:28 - 	Produtos com Suporte : 
19/08/2024 17:09:28 - 		Microsoft.VisualStudio.Community
19/08/2024 17:09:28 - 			Version : [17.10,18.0)
19/08/2024 17:09:28 - 			ProductArchitecture : amd64
19/08/2024 17:09:28 - 		Microsoft.VisualStudio.Community
19/08/2024 17:09:28 - 			Version : [17.10,18.0)
19/08/2024 17:09:28 - 			ProductArchitecture : arm64
19/08/2024 17:09:28 - 	Referências        : 
19/08/2024 17:09:28 - 	Pré-requisitos     : 
19/08/2024 17:09:28 - 		-------------------------------------------------------
19/08/2024 17:09:28 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
19/08/2024 17:09:28 - 		Name         : Visual Studio core editor
19/08/2024 17:09:28 - 		Version      : [17.10,18.0)
19/08/2024 17:09:28 - Signature Details…
19/08/2024 17:09:28 - 	Extension is not signed.
19/08/2024 17:09:28 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   em VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   em VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   em VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   em VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   em VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   em VSIXInstaller.App.Initialize()
   em System.Threading.Tasks.Task`1.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()

**Comment by tonyhallett** [comment]
You need to install in version >= 17.10

**Comment by StingyJack** [comment]
> You need to install in version >= 17.10

@tonyhallett the log above seems to indicate the target VS installation is 17.10.18
```
19/08/2024 17:09:28 - Identifier : Microsoft.VisualStudio.Component.CoreEditor
19/08/2024 17:09:28 - Name : Visual Studio core editor
19/08/2024 17:09:28 - Version : [17.10,18.0)
```

**Comment by xstrahl-mrankl** [comment]
I had the same problem in 17.10. But it installs fine in 17.11

**Comment by tonyhallett** [comment]
@xstrahl-mrankl I have it installed in 17.10.4
