### ISSUE TITLE
Partial coverage is reported for unit test files that contain more than one Moq Verify statements.

### ISSUE THREAD

**Issue by andimiar** [FortuneN/FineCodeCoverage#456]
### Installed product versions
- Visual Studio: Community 2022 (x64) version 17.11.4
- Fine Code Coverage extension version 1.1.223
- Coverlet collector version 6.0.2
- Xunit package version 2.9.2
- Moq package version 4.20.72

### Description
Unit tests pass successfully, but code coverage reports partial coverage for all lines in the unit tests that contain a Moq Verify statement, except for the first one.

### Steps to recreate
1. Create a unit test project and add this code:
namespace Evaluate.Tests
{
    using Moq;

    public class FCCEvaluate
    {
        private readonly Mock<IEvaluate> evaluateMock;
        private readonly Evaluate evaluate;

        public FCCEvaluate()
        {
            this.evaluateMock = new Mock<IEvaluate>();
            this.evaluate = new Evaluate(this.evaluateMock.Object);
        }

        [Fact]
        public void ProcedureAsync_ShouldCallEvaluate1ProcedureAsync()
        {
            var parameter = "test";
            this.evaluate.Procedure(parameter);
            this.evaluateMock.Verify(e => e.Procedure(parameter), Times.Once);
        }

        [Fact]
        public void FunctionAsync_ShouldCallEvaluate1FunctionAsync()
        {
            var parameter = "test";
            var expectedResult = "result";
            this.evaluateMock.Setup(e => e.Function(parameter)).Returns(expectedResult);
            var result = this.evaluate.Function(parameter);
            Assert.Equal(expectedResult, result);
            this.evaluateMock.Verify(e => e.Function(parameter), Times.Once);
        }
    }

    public interface IEvaluate
    {
        void Procedure(string parameter);
        string Function(string parameter);
    }

    public class Evaluate : IEvaluate
    {
        private readonly IEvaluate evaluate;

        public Evaluate(IEvaluate evaluate)
        {
            this.evaluate = evaluate;
        }

        public void Procedure(string parameter)
        {
            this.evaluate.Procedure(parameter);
        }

        public string Function(string parameter)
        {
            return this.evaluate.Function(parameter);
        }
    }
}
2. Run the unit tests
3. Look at the code coverage margin markings and the Fine Code Coverage view.

### Current behavior
All the unit tests pass with 100% line coverage.
All lines in the unit test file that call Moq Verify(), except one, are marked as partial coverage.
The Fine Code Coverage View shows 100% line coverage, but in this case, 75% branch coverage.
The view also shows 3 covered, 4 total branches.
This increases to 4 covered and 6 total branches when another Moq Verify statement is added to the unit test file.

### Expected behavior
All lines should be marked as fully covered, both line and branch coverage should be 100%.

**Comment by tonyhallett** [comment]
`Times.Once()`
