### ISSUE TITLE
Fine Code Coverage panel's content is blank - FCC output panel has exceptions: Error creating tracked lines

### ISSUE THREAD

**Issue by Camios** [FortuneN/FineCodeCoverage#457]
### Installed product versions
- Visual Studio: 2022, 17.11.4
- This extension: 1.1.223

### Description
Trying to use FCC on a large solution. I've run the unit tests, but the Fine Code Coverage panel is blank (apart for toolbar).
On the Output panel, the FCC output shows a lot of problems, but does appear to generate text-based coverage percentages.

### Steps to recreate
1. I installed the latest version of the FCC extension
2. Note: I don't know if I still have default settings (you can't tell because the Options shows everything as bold which usually means it has been modified). Is there a way to reset them?
3. I run unit tests from Test Explorer on a C# class library
4. I check the Fine Code Coverage window

### Current behavior
FCC output panel shows exceptions

```
<snip>
024-10-17T14:02:59: Writing report file '<path>\Bin\Win64-Dll\debug\fine-code-coverage\coverage-tool-output\index.html'
2024-10-17T14:02:59: Report generation took 0.5 seconds
Fine Code Coverage 17/10/2024 2:02:59 PM: Processing cobertura
Fine Code Coverage 17/10/2024 2:03:00 PM: Processing report
Fine Code Coverage 17/10/2024 2:03:00 PM: ================================== DONE ==================================
Fine Code Coverage 17/10/2024 2:03:00 PM: Error creating tracked lines for C:\Users\<user>\AppData\Local\Temp\blpp14e4..cs
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FineCodeCoverage.Editor.DynamicCoverage.ContainingCodeTrackedLinesBuilder.Create(List`1 lines, ITextSnapshot textSnapshot, String filePath)
   at FineCodeCoverage.Editor.DynamicCoverage.BufferLineCoverage.CreateTrackedLines(Boolean initial)
   at FineCodeCoverage.Editor.DynamicCoverage.BufferLineCoverage.TryCreateTrackedLines(Boolean initial)
Fine Code Coverage 17/10/2024 2:03:00 PM: Error creating tracked lines for Temp.txt
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FineCodeCoverage.Editor.DynamicCoverage.ContainingCodeTrackedLinesBuilder.Create(List`1 lines, ITextSnapshot textSnapshot, String filePath)
   at FineCodeCoverage.Editor.DynamicCoverage.BufferLineCoverage.CreateTrackedLines(Boolean initial)
   at FineCodeCoverage.Editor.DynamicCoverage.BufferLineCoverage.TryCreateTrackedLines(Boolean initial)
Fine Code Coverage 17/10/2024 2:03:00 PM: Error creating tracked lines for Temp.txt
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FineCodeCoverage.Editor.DynamicCoverage.ContainingCodeTrackedLinesBuilder.Create(List`1 lines, ITextSnapshot textSnapshot, String filePath)
   at FineCodeCoverage.Editor.DynamicCoverage.BufferLineCoverage.CreateTrackedLines(Boolean initial)
   at FineCodeCoverage.Editor.DynamicCoverage.BufferLineCoverage.TryCreateTrackedLines(Boolean initial)

```

Note: I can click on the Cobertura or Hotspot icons in the Fine Code Coverage panel and it opens XML reports.

I'll try to remember to send you an email with the log

Note: on a different, tiny solution, with no unit tests, the fine code coverage panel is at least showing the expected tabs.

### Expected behavior
I should see no exceptions in the FCC output panel.
I should see my code coverage visual report in the Fine Code Coverage panel.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by Camios** [comment]
@tonyhallett 
I was able to open the index.html report in Chrome and no errors were shown in the browser's Console.

I found some lowercase temp.txt files. Contents are "Placeholder file to mark for add the path in the p4 depot."
They are in the `fine-code-coverage\build-output\<folder>
So I'm guessing it FCC is setting a working directory and the tests are outputting files there

These lowercase files were marked with readonly attribute.

Could FCC be handling this gracefully rather than crashing?

**Comment by tonyhallett** [comment]
> Could FCC be handling this gracefully rather than crashing?

Lets determine what is causing this issue.

Did you open ` C:\Users\<user>\AppData\Local\Temp\blpp14e4..cs` and "Temp.txt" in the vs editor ?

**Comment by Camios** [comment]
The *.cs file is not there any more. The temp.txt file opens like a normal text file in VS editor

**Comment by tonyhallett** [comment]
But did you open these files ? I ask because the code that throws should only be run by the vs editor.

**Comment by tonyhallett** [comment]
Are you running any code generation utilities ? Extensions, custom tools - anything that might open files in the editor ?

**Comment by tonyhallett** [comment]
Note that FCC is not crashing.  The log entry has been written in a catch handler.

If you can show me the index.html we can determine why you are not seeing anything.

**Comment by Camios** [comment]
I restarted VS (haven't run any tests) and now the Fine code coverage panel is in worse shape
![image](https://github.com/user-attachments/assets/fd9c577b-8d7f-46c2-8f1a-0f57c75bd2be)

**Comment by Camios** [comment]
After the restart, I ran some tests and waited a while it seems to have resolved itself. Strange.
Thanks for assisting to troubleshoot

**Comment by tonyhallett** [comment]
For the error that FCC logs. All I can assume that a .cs file that was open in the editor has been renamed to a .txt file which caused the exception that was caught and logged.  There will be a new release shortly that deals with content type changes. 

Going to close this issue - let me know if you have any further issues with the FCC panel.
Note that I am aware of the hacky javascript that exists in index.html and will at some point replace with WPF.
