### ISSUE TITLE
Tool is generating bin and debug folders

### ISSUE THREAD

**Issue by sudha-93** [FortuneN/FineCodeCoverage#463]
Installed product versions
- Visual Studio: [2022 Professional]
- This extension: [ 1.1.223]

 Description
After running tests fine code coverage is generating bin folders and project specific debug folders 

 Steps to recreate
1. run the tests on right click of solution explorer

Current behavior

![finecodecoverageissue](https://github.com/user-attachments/assets/77c31c7d-17bd-4d43-a671-98ec02602cda)
All bin and debug folders are getting created 

Expected behavior
only report should be generated without creating any bin or debug folders

Side Notes

**Comment by tonyhallett** [comment]
This is not solution explorer.

**Comment by sudha-93** [comment]
Hi @tonyhallett ,
can you pls let me know how to avoid this?  is there any configuration changes to be done (tools->options-> fine code coverage) ?

**Comment by tonyhallett** [comment]
You are checking in the bin/obj directories. These should be excluded with gitignore.

See https://git-scm.com/docs/gitignore
You can check this repo https://github.com/github/gitignore/blob/main/community/DotNet/core.gitignore

**Comment by tonyhallett** [comment]
Closing as expected behaviour
