### ISSUE TITLE
Fine Code Coverage shows coverage of 0% after enable a third pard library

### ISSUE THREAD

**Issue by marcelbeekercgm** [FortuneN/FineCodeCoverage#464]
### Installed product versions
- Visual Studio: example 2022 Professional
- This extension: example 1.1.223

### Description
After invoking a method of a third party library there is 0% code coverage using coverlet.
When I generate a code coverage report using dotnet test --collect:"XPlat Code Coverage" and the report generator there is a code coverage report. So I guess the problem is in de fine code coverage extension.

### Steps to recreate
1. Enable third party method
2. Run test 

### Current behavior
Coverage of 0% in all methods

### Expected behavior
Coverage of 50%

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
Perhaps you could provide some information so we can determine the nature of the problem.

I am going to guess that you have not set the option RunMsCodeCoverage to Yes.  If you do not do this then FCC copies dlls changing paths which can result in tests that dependend on paths to fail and the result will be 0% coverage.

**Comment by marcelbeekercgm** [comment]
Hi Tony,

Thanks for your quick response. The RunMsCodeCoverage is set to False. What exact information do you want?

**Comment by tonyhallett** [comment]
Switch to RunMsCodeCoverage Yes then if it is still not providing coverage then provide information as per the side notes in the issue template.
Ideally you provide a repo that exhibits the behaviour encountered so I can debug FCC.
There are also logs in the FCC Output Window Pane that may give information.

**Comment by tonyhallett** [comment]
Is the FCC output referring to the same run as the last in the image that is stuck on Generating html report ?
I ask as Processing cobertura and Processing report occurs after Generating cobertura report / duration and Generating html report /duration.  

Also DONE occurs after the report has been generated successfully and the new report is shown.

Aside from what you see in the screenshot what makes you think that you can only generate the report only once ?
Are you sure that the coverage has changed and that you should be seeing a different report ?

**Comment by marcelbeekercgm** [comment]
Yes it is the same run. 
I did the same test once again. The generation of the report is done as you can see below. But no report is displayed.

Fine Code Coverage 08/11/2024 16:23:18: Ms code coverage
Fine Code Coverage 08/11/2024 16:23:26: ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output"
"-reports:C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output\781c3be4-9036-4261-ae3e-4ca5106e8a1a\marcel.beeker_N-4WJCLL3_2024-11-08.16_23_22.cobertura.xml"
"-reporttypes:Cobertura"
Fine Code Coverage 08/11/2024 16:23:27: ReportGenerator Run [reporttype:Cobertura]
2024-11-08T16:23:26: Arguments
2024-11-08T16:23:26:  -targetdir:C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output
2024-11-08T16:23:26:  -reports:C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output\781c3be4-9036-4261-ae3e-4ca5106e8a1a\marcel.beeker_N-4WJCLL3_2024-11-08.16_23_22.cobertura.xml
2024-11-08T16:23:26:  -reporttypes:Cobertura
2024-11-08T16:23:27: Writing report file 'C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output\Cobertura.xml'
2024-11-08T16:23:27: Report generation took 0,1 seconds
Fine Code Coverage 08/11/2024 16:23:27: ReportGenerator Run Arguments [reporttype:HtmlInline_AzurePipelines] 
"-targetdir:C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output"
"-reports:C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output\Cobertura.xml"
"-plugins:c:\users\marcel.beeker\appdata\local\microsoft\visualstudio\17.0_916629b8\extensions\qewmklx5.aqc\ReportGeneratorPlugins.dll"
"-reporttypes:FccLight"
"riskHotspotsAnalysisThresholds:metricThresholdForCyclomaticComplexity=30"
"riskHotspotsAnalysisThresholds:metricThresholdForCrapScore=15"
"riskHotspotsAnalysisThresholds:metricThresholdForNPathComplexity=200"
Fine Code Coverage 08/11/2024 16:23:27: ReportGenerator Run [reporttype:HtmlInline_AzurePipelines]
2024-11-08T16:23:27: Arguments
2024-11-08T16:23:27:  -targetdir:C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output
2024-11-08T16:23:27:  -reports:C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output\Cobertura.xml
2024-11-08T16:23:27:  -plugins:c:\users\marcel.beeker\appdata\local\microsoft\visualstudio\17.0_916629b8\extensions\qewmklx5.aqc\ReportGeneratorPlugins.dll
2024-11-08T16:23:27:  -reporttypes:FccLight
2024-11-08T16:23:27:  riskHotspotsAnalysisThresholds:metricThresholdForCyclomaticComplexity=30
2024-11-08T16:23:27:  riskHotspotsAnalysisThresholds:metricThresholdForCrapScore=15
2024-11-08T16:23:27:  riskHotspotsAnalysisThresholds:metricThresholdForNPathComplexity=200
2024-11-08T16:23:27: Writing report file 'C:\Development\Repos\z<pathtotestproject>\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output\index.html'
2024-11-08T16:23:27: Report generation took 0,1 seconds
Fine Code Coverage 08/11/2024 16:23:27: Processing cobertura
Fine Code Coverage 08/11/2024 16:23:27: Processing report
Fine Code Coverage 08/11/2024 16:23:27: ================================== DONE ==================================

![image](https://github.com/user-attachments/assets/a6293896-b3ba-4447-99e5-35515d60f8ba)

**Comment by tonyhallett** [comment]
Can you show the cobertura
<img width="29" alt="image" src="https://github.com/user-attachments/assets/ce9cfda3-a93f-4eec-8691-fdaaf5692335">

**Comment by marcelbeekercgm** [comment]
I can't attach the file. Github is not allow to do it. Can I show you a peace of the xml file?

**Comment by marcelbeekercgm** [comment]
Sorry I was trying to sent the report after Visual Studio was restarted. Below you can find the Corbertura of the report what went wrong. 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage line-rate="1" branch-rate="1" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="NaN" version="0" timestamp="1731084451">
  <sources />
  <packages />
</coverage>

**Comment by marcelbeekercgm** [comment]
It's better to sent a picture. 
![image](https://github.com/user-attachments/assets/3bdffe5b-a348-4abd-b384-f7d110b7ec91)

**Comment by marcelbeekercgm** [comment]
I didn't change anything in my code. The only thing I changed was, after the changing the setting RunMsCodeCoverage to Yes and Visual Studio restarted. After the restart the  Code Coverage report is generated. The second time, if I execute the unit tests in Visual Studio, the previously generated report disappeared but no report is generated after that.

**Comment by tonyhallett** [comment]
Have you set IncludeReferencedProjects and re-run your tests ?

**Comment by marcelbeekercgm** [comment]
I'm not sure if I understand you correctly. Do you mean this setting? 
![Screenshot 2024-11-11 095507](https://github.com/user-attachments/assets/68cdea49-b138-48c7-81ea-c1008754bf3f)

**Comment by tonyhallett** [comment]
Yes. You do have your SUT in a separate project ?

**Comment by marcelbeekercgm** [comment]
Yes my SUT is a seperate project from the tests.

**Comment by tonyhallett** [comment]
If you are getting no coverage with those settings then you need to show your solution or create a repro.

**Comment by marcelbeekercgm** [comment]
I will do. But I can't create a repro with the external library for you because it is confidential. But the issue about the  RunMsCodeCoverage to Yes which I mentioned today I can create a repro for you. That's no problem. I will contact again when the repro is available. Thanks for you time for now.

**Comment by tonyhallett** [comment]
Do you get the same problem with a different solution ?

**Comment by marcelbeekercgm** [comment]
Yes, it's very simple to reproduce the issue after RunMsCodeCoverage  is set to true?

**Comment by tonyhallett** [comment]
If this behaviour is present for all solutions then it suggests that visual studio has changed something we rely on, which could be a massive issue.
Can you create the simplest of solutions, a test project with a single test of a SUT with a single class, single method.  Do you get the same behaviour, cobertura with results first run and no results the second time.

What programming language are you using ?

**Comment by marcelbeekercgm** [comment]
Sorry for my late reaction. I have created a public repository where you can reproduce the issue. 
https://github.com/marcelbeekercgm/SampleCoverageProject.git

After set RunMsCodeCoverage to the value true, no code coverage is generated after the test running more than once.

**Comment by tonyhallett** [comment]
Thanks, as expected no issues with my version of Visual Studio
Microsoft Visual Studio Community 2022 (3) (64-bit) - Current
Version 17.10.4

What version of Visual Studio Professional do you have ?

**Comment by tonyhallett** [comment]
Works with 
Microsoft Visual Studio Community 2022 (3) (64-bit) - Current
Version 17.11.5

I do not have Visual Studio Profesional so the only way to proceed is for you to fork the extension and debug through yourself.

Are you willing to do that if I provide instructions ?

**Comment by marcelbeekercgm** [comment]
Sorry, at this moment i don't have time to debug the extension for you. However this problem can also be reproduced with the Community Edition of Visual Studio

**Comment by tonyhallett** [comment]
> However this problem can also be reproduced with the Community Edition of Visual Studio

With https://github.com/marcelbeekercgm/SampleCoverageProject.git RunMsCodeCoverage Yes and IncludeReferencedProjects cobertura present after the first run and not the second ?

Please ensure that if you have muliple installs of Visual Studio they have the same version of FCC installed.

After running the first test open ...\SampleCoverageProject-master\SampleCoverageProject-master\SampleCoverageProject.Test\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output it should look like
<img width="327" alt="image" src="https://github.com/user-attachments/assets/5fe72103-85a2-4778-9378-3c6aa371dce0">


One the second run the directory should be emptied and files generated again.
What do you see after the second run ?

**Comment by marcelbeekercgm** [comment]
I see the same results as the results displayed in your screenshot. Hower when I opened the index.html page I see this: 
![image](https://github.com/user-attachments/assets/97d219fc-c246-4541-8aa3-37e570e48744)

Only the results of my testproject not the sut project.

**Comment by tonyhallett** [comment]
I am now getting the behaviour you see.  I can see why, FCC generates .runsettings.  

When it works initially 
```
            <ModulePaths>
              <Exclude></Exclude>
              <Include>
                <ModulePath>.*\\SampleCoverageProject.dll$</ModulePath>
                <ModulePath>C:\\Users\\tonyh\\Downloads\\SampleCoverageProject-master\\SampleCoverageProject-master\\SampleCoverageProject.Test\\bin\\Debug\\net8.0\\SampleCoverageProject.Test.dll</ModulePath>
              </Include>
```

When it does not
```
            <ModulePaths>
              <Exclude></Exclude>
              <Include>
                <ModulePath>.*\\.dll$</ModulePath>
                <ModulePath>C:\\Users\\tonyh\\Downloads\\SampleCoverageProject-master\\SampleCoverageProject-master\\SampleCoverageProject.Test\\bin\\Debug\\net8.0\\SampleCoverageProject.Test.dll</ModulePath>
              </Include>
```

Will let you know when I have determined the cause.

**Comment by tonyhallett** [comment]
In the mean time for your original test of the third party library you can include it with a finecodecoverage-settings.xml

**Comment by tonyhallett** [comment]
The problem was that Visual Studio was intermittently ( for me, once in many test runs )  returning null for https://learn.microsoft.com/en-us/dotnet/api/vslangproj.reference.path?view=visualstudiosdk-2022

This has been fixed but the fix is only available in releases, [vsix](https://github.com/FortuneN/FineCodeCoverage/releases/download/v1.1.227/FineCodeCoverage.vsix),  untill @FortuneN resolves the [Github Actions issue ](https://github.com/FortuneN/FineCodeCoverage/actions/runs/11835552826/job/32978564437)

**Comment by marcelbeekercgm** [comment]
Sorry for my late answer. Can you give an indication whether a new version of the extension becomes available. 

Second question: Your answer which is a solution in the mean time. In the mean time for your original test of the third party library you can include it with a finecodecoverage-settings.xml

Can you give an example of the content of the settings xml file? 

Thanks in advance.

**Comment by tonyhallett** [comment]
Afraid not. @FortuneN .....

Did you try the vsix from releases ?

**Comment by FortuneN** [comment]
@tonyhallett Try deployment again

**Comment by marcelbeekercgm** [comment]
I'm affraid Visual Studio doesn't allow that to do. 
![image](https://github.com/user-attachments/assets/e3a34c3d-a17b-460d-bf5b-d2796bb33819)

**Comment by tonyhallett** [comment]
released !

**Comment by marcelbeekercgm** [comment]
Unfortunately this update doesn't solve the problem.
When I execute my tests I see only the coverage results of my test project.


![Screenshot 2024-11-20 163236](https://github.com/user-attachments/assets/76c4deca-eb87-4f71-b82c-9bee2bfcaa46)

**Comment by tonyhallett** [comment]
have you set the option IncludeReferencedProjects to true.

**Comment by tonyhallett** [comment]
Does it work with the SampleCoverageProject ?

**Comment by tonyhallett** [comment]
FYI

IncludeReferencedProjects only works with directly referenced projects.
Is the SUT directly referenced ?

from https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#include-or-exclude-assemblies-and-members

```
Include or exclude assemblies and members
You can include or exclude assemblies or specific types and members from code coverage analysis. If the Include section is empty or omitted, then all assemblies that are loaded and have associated PDB files are included. If an assembly or member matches a clause in the Exclude section, then it is excluded from code coverage. The Exclude section takes precedence over the Include section: if an assembly is listed in both Include and Exclude, it will not be included in code coverage.
```

So when you have included the test project we must include the SUT.

You could not include the test assembly and all loaded assemblies will be included.

I assume that there are PDB files for them ?

**Comment by marcelbeekercgm** [comment]
I finally find out it that this problem only occur in my real project. The test project which I have uploaded in Github seems to working ok after the update of your extension.

Yes, the SUT is directly reference. It also includes PDB files.

**Comment by tonyhallett** [comment]
Can you confirm the following for your real project.

When running with RunMsCodeCoverage to Yes and IncludeReferencedProjects True and no finecodecoverage-settings.xml you get the expected Cobertura but the next test run ( or subsequent ) the Cobertura has no package entries.
If this is indeed the case then can you show the difference in the TestProjectName-fcc-mscodecoverage.generated.runsettings between the two test runs, will be in TestProjectName\bin\Debug\net8.0\fine-code-coverage\coverage-tool-output.

That with finecodecoverage-settings.xml you get the correct Cobertura each and every time.  If so how does the generated.runsettings compare against the one generated with IncludeReferencedProjects.

**Comment by marcelbeekercgm** [comment]
Hi Tony,
Finally I have found the root cause why the code coverage wasn't working with my real project where third party libraries were used.

It was cased by a definition of a AssemblyName in the project file of the application. When the assemblyname is disabled it starts working.
I think I have to include the assembly name in de .runsettings file of my test project. Can you give an example how to do that? Thanks in advance.

**Comment by tonyhallett** [comment]
See https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#include-or-exclude-assemblies-and-members  - I assume you will use ModulePath
and https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#regular-expressions

If you could provide a repro with an AssemblyName that has the behaviour of your real project I can debug in and change the FCC source accordingly.

**Comment by marcelbeekercgm** [comment]
Thanks for you quick response. I finally solved this issue by adding a .runsettings file with this content: <?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <DataCollectionRunSettings>
      <DataCollectors>
          <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
              <Configuration>
                <CodeCoverage>
                  <ModulePaths>
                    <Include>
                        <ModulePath>.*\.dll$</ModulePath>
                    </Include>
                  </ModulePaths>
                </CodeCoverage>
              </Configuration>
        </DataCollector>
     </DataCollectors>
    </DataCollectionRunSettings>
</RunSettings>

**Comment by tonyhallett** [comment]
The latest release now obtains the assembly name when changed with msbuild property.
