### ISSUE TITLE
Extension is not signed.

### ISSUE THREAD

**Issue by gokulcaringula** [FortuneN/FineCodeCoverage#465]
### Installed product versions
- Visual Studio: VS 2022 Professional
- This extension: 1.1.23

### Description
Extension is not signed.

### Steps to recreate
1. Download and install *.vsix

### Current behavior
N/A

### Expected behavior
Install the extension

### Side Notes
11/8/2024 12:19:24 PM - Microsoft VSIX Installer
11/8/2024 12:19:24 PM - -------------------------------------------
11/8/2024 12:19:24 PM - vsixinstaller.exe version:
11/8/2024 12:19:24 PM - 17.10.2186+0bf64ad641
11/8/2024 12:19:24 PM - -------------------------------------------
11/8/2024 12:19:24 PM - Command line parameters:
11/8/2024 12:19:24 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\consuzy\Downloads\FineCodeCoverage.vsix
11/8/2024 12:19:24 PM - -------------------------------------------
11/8/2024 12:19:24 PM - Microsoft VSIX Installer
11/8/2024 12:19:24 PM - -------------------------------------------
11/8/2024 12:19:25 PM - Initializing Install...
11/8/2024 12:19:25 PM - Searching for applicable products...
11/8/2024 12:19:25 PM - Found installed product - Visual Studio Professional 2022
11/8/2024 12:19:25 PM - Found installed product - Global Location
11/8/2024 12:19:25 PM - Extension Details...
11/8/2024 12:19:25 PM - 	Identifier         : fcc-f339fe606-9d51-4fca-895c-d50375137b62
11/8/2024 12:19:25 PM - 	Name               : Fine Code Coverage
11/8/2024 12:19:25 PM - 	Author             : Fortune Ngwenya
11/8/2024 12:19:25 PM - 	Version            : 1.1.223
11/8/2024 12:19:25 PM - 	Description        : Visualize unit test code coverage easily for free in Visual Studio Community Edition (and other editions too)
11/8/2024 12:19:25 PM - 	Locale             : en-US
11/8/2024 12:19:25 PM - 	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage
11/8/2024 12:19:25 PM - 	InstalledByMSI     : False
11/8/2024 12:19:25 PM - 	SupportedFrameworkVersionRange : [4.7,)
11/8/2024 12:19:25 PM - 	SignatureState     : Unsigned
11/8/2024 12:19:25 PM - 	Supported Products : 
11/8/2024 12:19:25 PM - 		Microsoft.VisualStudio.Community
11/8/2024 12:19:25 PM - 			Version : [16.11,17.0)
11/8/2024 12:19:25 PM - 			ProductArchitecture : x86
11/8/2024 12:19:25 PM - 	References         : 
11/8/2024 12:19:25 PM - 		-------------------------------------------------------
11/8/2024 12:19:25 PM - 		Identifier   : Microsoft.VisualStudio.MPF.16.0
11/8/2024 12:19:25 PM - 		Name         : Visual Studio MPF 16.0
11/8/2024 12:19:25 PM - 		Version      : [16.0,17.0)
11/8/2024 12:19:25 PM - 		MoreInfoURL  : 
11/8/2024 12:19:25 PM - 		Nested       : No
11/8/2024 12:19:25 PM - 	Prerequisites      : 
11/8/2024 12:19:25 PM - 		-------------------------------------------------------
11/8/2024 12:19:25 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
11/8/2024 12:19:25 PM - 		Name         : Visual Studio core editor
11/8/2024 12:19:25 PM - 		Version      : [16.0,17.0)
11/8/2024 12:19:25 PM - Signature Details...
11/8/2024 12:19:25 PM - 	Extension is not signed.
11/8/2024 12:19:25 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by tonyhallett** [comment]
Update visual studio. This has nothing to do with the absence of signing.
