### ISSUE TITLE
An exception occurred during a WebClient request.

### ISSUE THREAD

**Issue by gokulcaringula** [FortuneN/FineCodeCoverage#466]
### Installed product versions
- Visual Studio: 2022 Latest Updated Version as on 11-08-2024
- This extension: [example 1.1.21]

### Description
---------------------------
Microsoft Visual Studio
---------------------------
One or more extensions could not be installed because the following errors occurred:
An exception occurred during a WebClient request.

### Steps to recreate
1.Try to add extension from Extension Manager in VS 2022 Professional.

### Current behavior
When clicked on Install button from Extensions Manager it throws above error.

### Expected behavior
Work as expected.

### Side Notes
One or more extensions could not be installed because the following errors occurred:
An exception occurred during a WebClient request.

**Comment by tonyhallett** [comment]
That does not seem like an FCC issue. We do not use a Web client.
Is there a stack trace ?

**Comment by gokulcaringula** [comment]
This error comes when I click Install in lastest updated Visual Studio 2022
from Extension Manager.

**Comment by tonyhallett** [comment]
Visual studio has log files. Please do an internet search for where they are located and post the log.
Again we do not use a Web client.

Do you get this error each and every time ?

**Comment by tonyhallett** [comment]
Did you get FCC to install ?

**Comment by tonyhallett** [comment]
Closing as the vs ExtensionRepositoryService uses the VSGalleryRepository base class BaseExtensionRepository to download extensions which in turn uses a ExtensionManagerWebClient WebClient wrapper.  This is raising the exception.  Nothing to do with FCC in my opinion.

**Comment by gokulcaringula** [comment]
Nope. Tried all I could, its giving the same error.

Thanks,
Gokul

**Comment by tonyhallett** [comment]
Can you update visual studio ?

**Comment by tonyhallett** [comment]
Can you try and install any other extension now that you have updated.

**Comment by tonyhallett** [comment]
You could download from here instead https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage2022

**Comment by tonyhallett** [comment]
"An exception occurred during a WebClient request" [has been reported to visual studio before](https://developercommunity.visualstudio.com/t/SonarLint-for-Visual-Studio-2022-Error/10539528?q=%22An+exception+occurred+during+a+WebClient+request%22).

**Comment by gokulcaringula** [comment]
Guess what, I installed '.Net Upgrade Assistant' extension and then tried
FCC, and it got installed. Not sure what exactly fixed it. But thanks for
following up on this. :)

Regards,
Gokul

**Comment by tonyhallett** [comment]
Ok, great !
