### ISSUE TITLE
Not able to get any results regardless of settings

### ISSUE THREAD

**Issue by Flohack74** [FortuneN/FineCodeCoverage#469]
### Installed product versions
- Visual Studio: 2022 Version 17.12.0
- This extension: 1.1.228

### Description
No matter which guide I follow I never receive any coerage results in the output window.

### Steps to recreate
1. Install FCC
2. Have a generic .runsettings file in the root folder (No special treatment was done there for FCC but we need it for other things, see below)
3. Install either coverlet.collector, or MS Code Coverage NuGet packages into the test project, or neither of them
4. It does not matter if I enable MS code coverage in the settings or not
5. Trigger test run from Test Explorer

### Current behavior
After unit test run has been triggered the FCC log picks it up and starts doing some steps it seems. However, I am only able to produce logs like the following:

```
Fine Code Coverage 03.12.2024 14:37:52: Ms code coverage with user runsettings
Fine Code Coverage 03.12.2024 14:38:17: No cobertura files for ms code coverage.
Fine Code Coverage 03.12.2024 14:38:17: ================================== DONE ==================================
Fine Code Coverage 03.12.2024 14:44:35: Coverage collected when tests finish. RunInParallel option true for immediate
Fine Code Coverage 03.12.2024 14:44:39: ================================== START ==================================
Fine Code Coverage 03.12.2024 14:44:39: (BusinessObjectsTests) Failed.
Disabled
Fine Code Coverage 03.12.2024 14:44:39: ================================== DONE ==================================
Fine Code Coverage 03.12.2024 14:45:02: Coverage collected when tests finish. RunInParallel option true for immediate
Fine Code Coverage 03.12.2024 14:45:22: ================================== START ==================================
Fine Code Coverage 03.12.2024 14:45:22: (BusinessObjectsTests) Failed.
Disabled
Fine Code Coverage 03.12.2024 14:45:22: ================================== DONE ==================================
Fine Code Coverage 03.12.2024 14:46:29: Coverage collected when tests finish. RunInParallel option true for immediate
Fine Code Coverage 03.12.2024 14:46:51: ================================== START ==================================
Fine Code Coverage 03.12.2024 14:46:51: (BusinessObjectsTests) Failed.
Disabled
Fine Code Coverage 03.12.2024 14:46:51: ================================== DONE ==================================
Fine Code Coverage 03.12.2024 14:51:46: See option RunMsCodeCoverage for a better ( Beta ) experience.  https://github.com/FortuneN/FineCodeCoverage/blob/master/README.md
Fine Code Coverage 03.12.2024 14:51:46: ================================== START ==================================
Fine Code Coverage 03.12.2024 14:51:47: (BusinessObjectsTests) Failed.
Disabled
Fine Code Coverage 03.12.2024 14:51:47: ================================== DONE ==================================
```

### Expected behavior
Should produce coverage results.

### Side Notes

.runsettings contains:
```

<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <!-- Use 0 for maximum process-level parallelization. This does not force parallelization within the test DLL (on the thread-level). You can also change it from the Test menu; choose "Run tests in parallel". Unchecked = 1 (only 1), checked = 0 (max). -->
    <MaxCpuCount>0</MaxCpuCount>
    <TargetPlatform>x64</TargetPlatform>
    <TestSessionTimeout>900000</TestSessionTimeout>
  </RunConfiguration>
</RunSettings>
```

**Comment by Flohack74** [comment]
What snot clear from the documentation:

- Which NuGet packages are needed / can be installed into the test projects, and which settings correspond so that the output is recognized.
- How to reset FCC settings to a default. It seems my settings are just bonkers, Run was set to Disabled: Yes

However I am now stuck here, again with no output:

![grafik](https://github.com/user-attachments/assets/62c7e2e7-af00-42f8-9da8-916dda6b0060)

**Comment by tonyhallett** [comment]
> Install either coverlet.collector, or MS Code Coverage NuGet packages into the test project, or neither of them

You do not need to install these.

Is that your full runsettings ?

I assume that you have no package elements in your cobertura ?
<img width="92" alt="image" src="https://github.com/user-attachments/assets/6a11fcad-fedb-4517-97f7-afdb82945937">
The leftmost icon.

If you have in your options IncludeTestAssembly then with Ms Code coverage you also need to include your SUT.  IncludeReferencedProjects should do that.
<img width="426" alt="image" src="https://github.com/user-attachments/assets/45b0b570-7cc9-45d4-89d3-6f59c3701d9b">

> How to reset FCC settings to a default. It seems my settings are just bonkers, Run was set to Disabled: Yes

I'll add a command to do that later.

In the mean time all options are defined [here](https://github.com/FortuneN/FineCodeCoverage/blob/cf7da3dc116cd452c32f5b483c914f442f97b8f5/SharedProject/Options/AppOptionsPage.cs#L65)
and any we explicitly set a value is done [here](https://github.com/FortuneN/FineCodeCoverage/blob/cf7da3dc116cd452c32f5b483c914f442f97b8f5/SharedProject/Options/AppOptionsProvider.cs#L55)

Here's mine
<img width="503" alt="image" src="https://github.com/user-attachments/assets/438d0a02-518d-4c7c-b65b-a9595a96533c">

<img width="503" alt="image" src="https://github.com/user-attachments/assets/05738721-7c43-498f-8ca8-077c1f73863d">

<img width="503" alt="image" src="https://github.com/user-attachments/assets/92e361cc-1f70-467c-afc0-530e569648a6">

**Comment by Flohack74** [comment]
Definitely for some reason my options were completly borken :D - I close this ticket here as now everything seems to work.
