### ISSUE TITLE
Allow resizing of columns in test coverage view

### ISSUE THREAD

**Issue by ekolis** [FortuneN/FineCodeCoverage#473]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.229

### Description
If class/namespace names are too long, the coverage view will get really wide and require scrolling. I'd like to be able to resize at least the class/namespace column smaller to avoid having to scroll.

### Steps to recreate
1. Open the coverage view
2. Try to resize the columns by dragging the borders between them

### Current behavior
Nothing happens.

### Expected behavior
The columns should resize.

**Comment by tonyhallett** [comment]
This is not available in the report generated by Report Generator.  This will be incorporated when we have a custom report
