### ISSUE TITLE
Hold title as you scroll through coverage report

### ISSUE THREAD

**Issue by JesseLiberty** [FortuneN/FineCodeCoverage#476]
### Installed product versions
- Visual Studio: Enterprise 2022 17.11.6
- This extension: 1.1.229

### Description
As I scroll down the Coerage report I lose track of what each column is. It would be nice if the column header did not scroll

### Steps to recreate
1. Run report
2. Scroll down enough lines for header to disappear

### Current behavior
Header disappears which makes it hard to know what the numbers indicate

### Expected behavior
Would be great if the headers remained visible

**Comment by tonyhallett** [comment]
That's what the StickyCoverageTable element is for
