### ISSUE TITLE
All lines and branches are highlighted Red

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [FortuneN/FineCodeCoverage#5]
### Installed product versions
- Visual Studio: 2019 Pro
- This extension: 1.0.43

### Description
After having run my tests every line and branch is highlighted as red (uncovered). Therefore, I am unsure how this extension is supposed to work.

### Steps to recreate
1. Load Project
2. Run Tests

### Current behavior
All lines and branches are highlighted red.

### Expected behavior
I expect my tested branches and lines to be green and not red.

**Comment by FortuneN** [comment]
Thank you for posting this.
Please attach a sample solution with the test code and code being tested.
Let’s get this resolved ASAP

**Comment by SamuelJohnsonMedia** [comment]
Here you go, I have a failing project (console app, library and a test); and a working project (library and a test):

[ConsoleApp1-DoesntWork.zip](https://github.com/FortuneN/FineCodeCoverage/files/5294258/ConsoleApp1-DoesntWork.zip)
[ClassLibrary1-Works.zip](https://github.com/FortuneN/FineCodeCoverage/files/5294260/ClassLibrary1-Works.zip)

Thanks

**Comment by SamuelJohnsonMedia** [comment]
With the latest update 1.0.49; the classlibrary sample I attached above which did work doesnt work at all now ... I get no red or green coverage lines anywhere on any project.

**Comment by FortuneN** [comment]
Please check the current/latest version

**Comment by SamuelJohnsonMedia** [comment]
Yay brilliant; i have log output showing coverage values; the new coverage view is showing some results and my code is showing Green. Well done!!

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
