### ISSUE TITLE
For contributors - tests

### ISSUE THREAD

**Issue by tonyhallett** [FortuneN/FineCodeCoverage#50]
Refactor and create a tests project.

**Comment by FortuneN** [comment]
I see you've posted some stuff that's on the roadmap (unit tests, a custom UI, ...)
There are a few more things that i have up my sleeve but being the only dev and having full day job leaves very little time to get to these.
I'm hoping you are going to be around for sometime in which case please give me your email address so i can invite you into the (newly created) slack workspace

**Comment by tonyhallett** [comment]
Done
