### ISSUE TITLE
Excluding file by reading ExcludeFromCodeCoverageAttribute from project file does not add any value.

### ISSUE THREAD

**Issue by tonyhallett** [FortuneN/FineCodeCoverage#53]
The commit that you made does not add any value.

https://github.com/FortuneN/FineCodeCoverage/blob/0eb3c53278ddd27d16f617102c00c04463d697f2/FineCodeCoverage/Core/OpenCover/OpenCoverUtil.cs#L206

`

				foreach (var referenceProjectWithExcludeAttribute in project.ReferencedProjects.Where(x => x.HasExcludeFromCodeCoverageAssemblyAttribute))
				{
					filters.Add($@"-[{referenceProjectWithExcludeAttribute.AssemblyName}]*");
				}
`

https://github.com/FortuneN/FineCodeCoverage/blob/0eb3c53278ddd27d16f617102c00c04463d697f2/FineCodeCoverage/Core/Coverlet/CoverletUtil.cs#L180
`

			foreach (var referenceProjectWithExcludeAttribute in project.ReferencedProjects.Where(x => x.HasExcludeFromCodeCoverageAssemblyAttribute))
			{
				coverletSettings.Add($@"--exclude ""[{referenceProjectWithExcludeAttribute.AssemblyName}]*""");
			}
`

https://github.com/FortuneN/FineCodeCoverage/blob/0eb3c53278ddd27d16f617102c00c04463d697f2/FineCodeCoverage/Core/FCCEngine.cs#L532
`

		private static bool HasExcludeFromCodeCoverageAssemblyAttribute(XElement projectFileXElement)
		{
			/*
			 ...
			<ItemGroup>
				<AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
			</ItemGroup>
			...
			 */

			var xassemblyAttribute = projectFileXElement.XPathSelectElement($"/ItemGroup/AssemblyAttribute[@Include='System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute']");
			
			return xassemblyAttribute != null;
		}
`

The problem lies with the exclude attribute that you are searching for.
Coverlet already has built in support for any attribute with name ExcludeFromCodeCoverage so there is no need to add to excludes.

https://github.com/tonyhallett/coverlet/blob/bc1626c20576bc2a1ac58aecc942dadf0be52d49/src/coverlet.core/Instrumentation/Instrumenter.cs#L233
`
_excludedAttributes = PrepareAttributes(excludedAttributes, nameof(ExcludeFromCoverageAttribute), nameof(ExcludeFromCodeCoverageAttribute));
///
        private bool IsExcludeAttribute(CustomAttribute customAttribute)
        {
            return Array.IndexOf(_excludedAttributes, customAttribute.AttributeType.Name) != -1;
        }
`

OpenCover only runs for .Net projects and as such it is not possible to add System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute as an assembly level attribute ( you can for .Net Core ).

If you change your xpath to match only on name and not on fully qualified then this would be beneficial to OpenCover runs.
Be sure to check for ExcludeFromCodeCoverage and ExcludeFromCodeCoverageAttribute and if you want to align with Coverlet then ExcludeFromCoverage and ExcludeFromCoverageAttribute too.

_Originally posted by @tonyhallett in https://github.com/FortuneN/FineCodeCoverage/issues/39#issuecomment-749656493_

**Comment by FortuneN** [comment]
> Coverlet already has built in support for any attribute with name ExcludeFromCodeCoverage so there is no need to add to excludes.

I apply the exclude there just for symmetry

> OpenCover only runs for .Net projects and as such it is not possible to add System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute as an assembly level attribute

This is where the magic comes in. Now you CAN add an assembly level attribute to a .net framework project.
In .net core it's handled implicitly by coverlet; In .net framework, we interpret that for the user and pass an exclude to OpenCover.
The user does not care how it's done. To them, the feature works for both .net core and .net framework. 

> If you change your xpath to match only on name and not on fully qualified then this would be beneficial to OpenCover runs.

Are you saying OpenCover supports the assembly level attribute if it's specified in the short format?

> Be sure to check for ExcludeFromCodeCoverage and ExcludeFromCodeCoverageAttribute and if you want to align with Coverlet then ExcludeFromCoverage and ExcludeFromCoverageAttribute too.

I can modify the logic add support both the short name and fully qualified name

**Comment by tonyhallett** [comment]
> This is where the magic comes in. Now you CAN add an assembly level attribute to a .net framework project. (That's the added value)

> In .net framework, we interpret that for the user and pass an exclude to OpenCover.

You are not going to be providing any magic trying to read an attribute that cannot be applied to a .Net Framework assembly.
I refer you back to the link https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute?view=netframework-4.0


> Are you saying OpenCover supports the assembly level attribute implicitly if it's specified in the short format?

No I am saying that there is no point trying to read an attribute that cannot be applied to a .Net Framework assembly !

Open cover, from the quick look that I had, does not support assembly level attribute exclusions and so your "magic" does make sense and would add value if you take my advice and provide similar behaviour to Coverlet.  As stated Coverlet will automatically exclude any assembly level attribute with name ExcludeFromCodeCoverageAttribute ( and the others mentioned ) not just the one from System.Diagnostics.CodeAnalysis because it is not available to .Net Framework and thus for parity with Coverlet you should change your xpath as advised.

**Comment by FortuneN** [comment]
I think we are misunderstanding each other on this one.
Maybe because of the written conversation.
I've started a google meeting and will keep it open some time; If you are able, please join
https://meet.google.com/hzf-dqrj-gya?authuser=0&hl=en

**Comment by tonyhallett** [comment]
Perhaps the misunderstanding is 

> OpenCover only runs for .Net projects and as such it is not possible to add System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute as an assembly level attribute ( you can for .Net Core ).

This should have read
OpenCover only runs for .Net **Framework** projects and as such it is not possible to add System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute as an assembly level attribute ( you can for .Net Core ).

If you compare the two links then you will see that the attribute usage differs.

You cannot apply it to a .Net Framework project and therefore you cannot read it and perform any magic.

That was the point of this commit in the Coverlet repository.
https://github.com/coverlet-coverage/coverlet/commit/511a3074bbc3ed97a227bda9e407696d95be3add

I am off to bed.  Hopefully you understand now.

**Comment by FortuneN** [comment]
> OpenCover only runs for .Net Framework projects and as such it is not possible

It **is** possible to add it into the project file (its just an extra XML tag).
- msbuild will ignore it
- FineCodeCoverage will read it and use it to apply an exclude when running OpenCover

I think we need to a live meeting and understand each other's perspective on this.
My email address is fortunengwenya@gmail.com; You can send me a calendar invite of when you would be available to do a meeting

**Comment by tonyhallett** [comment]
Excellent now we understand each other.

This comment of yours alluded to the attribute being used as a real attribute, as is the case when an sdk style project file has the item.
> The attribute is available to all .net projects since 4.0
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute?view=netframework-4.0

I apologise. You are correct. I knew visual studio did not like the attribute in the project file although, as you correctly state, msbuild will not complain.

![image](https://user-images.githubusercontent.com/11292998/102944223-15783900-44b2-11eb-902c-c3481cda5cfa.png)

I advise that you instead change to a property <FineCodeCoverageExclude/> so as to avoid the visual studio warning and to avoid the connection to an attribute that cannot be applied as an assembly attribute in a .Net Framework project ! It is also explicit that this asssembly will be excluded from code coverage only when being run from the Fine Code Coverage addin.

Again, please accept my apologies.  
Back to bed.
