### ISSUE TITLE
Add the ability to specify whether or not to proceed based on the number of failed tests or if any failed

### ISSUE THREAD

**Issue by FortuneN** [FortuneN/FineCodeCoverage#56]
https://github.com/FortuneN/FineCodeCoverage/issues/27#issuecomment-751356169

**Comment by tonyhallett** [comment]
Number of tests could be just as useful. If one test then apart from first test in TDD it is unlikely the intent is test and cover

**Comment by tonyhallett** [comment]
Feature provided with https://github.com/FortuneN/FineCodeCoverage/commit/8dba23234da055fca94e8f0107d60d057dae0861
