### ISSUE TITLE
After 1.1.52 I got error : "The file is locked by: "vstest.console (24820)"

### ISSUE THREAD

**Issue by nsentuna** [FortuneN/FineCodeCoverage#59]
### Installed product versions
- Visual Studio: [2019 Professional]
- This extension: [1.1.52]

### Description
After I have installed new version 1.1.52 I have faced with a problem like this, if my an unit test has been resoulted in assert failed, vs. 2019 has failed like below . I have to restart vs. or pc.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy "G:\GitProjects\Arles\ARLESApplication\ARLESServer\ArlesUnitTests\UnitTest\bin\Debug\UnitTest.dll" to "bin\Debug\UnitTest.dll". Exceeded retry count of 10. Failed. **### The file is locked by: "vstest.console (24820)"**	EntegrasyonServiceTests			

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Explain what it should be doing after it's fixed.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
@nsentuna 
You are going to have to provide a repro.
Are you only running your tests from visual studio Test Explorer ?

**Comment by nsentuna** [comment]
yes I 'm running tests from on Visual Studio Test (2019 Professional Version 16.8.3 ) 

I 've been never get like this error before. I have no problem running my tests. don't faced this problem after uninstall Fine code covarage. after reinstall FCC. I faced same problem again. for example, if my unit tests asserts is success this problem don't occure. but if my unit test finished with assert failed. I get this error and I never can't run again whole vs solution. if I close vs. or restart pc after then I can run again until my unit test assert failed.

**Comment by tonyhallett** [comment]
@nsentuna 


We know the code that was removed so it will be simple to put it back ( @FortuneN the original file synhronization code would have to change to fix the issue I reported on multi-target frameworks ) but it would be nice to investigate further as we thought that file locking would not occur.

Is there any way that you can add an repro.  ( I ran FCC on a very simple project where a test assertion failed and there was no locking. )

**Comment by nsentuna** [comment]
please rename extention as RAR.
[2020-12-31_161955rar.zip](https://github.com/FortuneN/FineCodeCoverage/files/5757396/2020-12-31_161955rar.zip)

**Comment by nsentuna** [comment]
I send you another long video for further information. but my videos part to part in 10MB don't forget rename extentios as RAR, 
[2020-12-31_162842.part1.zip](https://github.com/FortuneN/FineCodeCoverage/files/5757404/2020-12-31_162842.part1.zip)

you must comibine its.

**Comment by nsentuna** [comment]
[Uploading 2020-12-31_162842.part2.zip…]()

**Comment by nsentuna** [comment]
[Uploading 2020-12-31_162842.part3.zip…]()

**Comment by nsentuna** [comment]
[Uploading 2020-12-31_162842.part4.zip…]()

**Comment by tonyhallett** [comment]
@nsentuna 

part2/3/4 links don't work

**Comment by nsentuna** [comment]
the screen videos that  I sent you betwen part 1 and part 4 are actually one files. due to my videos bigger then 10mb I splited four file for 10mb when I create rar file.

**Comment by tonyhallett** [comment]
@nsentuna the URLs are not valid. I cannot download them

**Comment by tonyhallett** [comment]
I have reproduced with a simple repro.  It is not the assertion that is the problem but the build occurring as Fine Code Coverage is running tests.  Looking into it now

**Comment by tonyhallett** [comment]
@FortuneN 
I tried the following instead of _dteEvents.BuildEvents but no joy there - seems that it is too late there too.

```
internal class TestContainerDiscoverer : ITestContainerDiscoverer, IVsUpdateSolutionEvents2{
....
public int UpdateSolution_Begin(ref int pfCancelUpdate)
        {
			StopCoverageProcess();
			return VSConstants.S_OK;
	}
```

Repro
```
[TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Thread.Sleep(20000);
            Assert.IsTrue(true);
        }
    }
```
Run the test.
Change the source code e.g `Assert.IsTrue(true );`
Wait until FCC starts collecting coverage
Run the test again

**Comment by nsentuna** [comment]
dear @tonyhallett  I could not send video screen because of big file size ~50MB if you send me your email adress I want share my videos file from my microsoft outlook account to your email.

**Comment by tonyhallett** [comment]
@nsentuna no need. I will put in a fix in the next couple of days

**Comment by nsentuna** [comment]
I 'm so happy now. 

Also I noticed that When I got this error , I  kill the task vstest.console.exe in the running task manager and my test run again until next failed.

![image](https://user-images.githubusercontent.com/21196564/104186427-72b73880-5427-11eb-8e5f-b228ad12bed7.png)

**Comment by nsentuna** [comment]
is there any news 

Microsoft Visual Studio Professional 2019 Version 16.8.4
FCC updated as 1.1.63 my problem still goes on when you resolve this problem ? I added a short screen movie

https://user-images.githubusercontent.com/21196564/104703332-4271e180-5728-11eb-84cb-2e6f71f26fb4.mp4

**Comment by tonyhallett** [comment]
@nsentuna I am hoping to have the time to do this this weekend

**Comment by tonyhallett** [comment]
@FortuneN @nsentuna I am looking at this now

**Comment by FortuneN** [comment]
Check latest update
