### ISSUE TITLE
Code Coverage View Window Drawing Issues

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [FortuneN/FineCodeCoverage#6]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 1.0.74

### Description
The new extension 'View Window' has some redraw issues where column headings or text overwrites neighboring columns.

### Steps to recreate
1. Run tests
2. View "Fine Code Coverage" from Views->Other Windows

### Current behavior
The text overwrites other text in adjacent columns

![Coverage Columns](https://user-images.githubusercontent.com/68481262/95017916-ee992c00-0653-11eb-8296-1186a6428c0d.png)

![Coverage Columns 2](https://user-images.githubusercontent.com/68481262/95017917-f0fb8600-0653-11eb-999a-c3265a4c2e9f.png)

### Expected behavior
Text should not overwrite

**Comment by FortuneN** [comment]
Please check the latest version

**Comment by SamuelJohnsonMedia** [comment]
Wonderful, all fixed and donation made 👍

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
