### ISSUE TITLE
is there any news this problem vstest.console (14888)

### ISSUE THREAD

**Issue by nsentuna** [FortuneN/FineCodeCoverage#63]
### Installed product versions
Microsoft Visual Studio Professional 2019
Version 16.8.4

https://user-images.githubusercontent.com/21196564/104701034-1e150580-5726-11eb-8e9e-70b4965b2e1e.mp4

![image](https://user-images.githubusercontent.com/21196564/104700950-00e03700-5726-11eb-93a8-eca78130449e.png)

### Description
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy "obj\Debug\BusinessServicesTests.dll" to "bin\Debug\BusinessServicesTests.dll". Exceeded retry count of 10. Failed. The file is locked by: "vstest.console (14888)"	BusinessServicesTests			

### Steps to recreate

I added screen movie file 

### Current behavior
Explain what it's doing and why it's wrong

### Expected behavior
Explain what it should be doing after it's fixed.

### Side Notes
- It helps to attach a repro solution so i can test the fix
- It helps to attach the log (send it to my mailbox if you need todo so privately : fortunengwenya@gmail.com)
- It helps to attach a screen recoding video of steps to recreate (sometimes a video is worth a thousand words)
- Please consider giving this project a star and become one of the stagazers
  https://github.com/FortuneN/FineCodeCoverage/stargazers 
- Please consider buying me a coffee
  https://paypal.me/FortuneNgwenya (Once) OR https://liberapay.com/FortuneN/donate (Recurring)
- Please consider rating and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
@FortuneN @nsentuna I am lookingat this now

**Comment by nsentuna** [comment]
I checked on the market,  it seems still version is 1.1.63, when can I download 1.1.65 or update auto my vs. ?

thanks

necmi

**Comment by tonyhallett** [comment]
@nsentuna You could fork the project and build it to get the vsix in the Release directory.  You can pull in my branch https://github.com/tonyhallett/FineCodeCoverage/tree/fix_file_locking before you build.

**Comment by tonyhallett** [comment]
@FortuneN #65 closes this one as well

**Comment by FortuneN** [comment]
Check latest update

**Comment by tonyhallett** [comment]
@FortuneN I am getting file locking.  I will look at first thing

**Comment by nsentuna** [comment]
Dear @tonyhallett  I did your mentioned process, and I tested then I didn't have any problem. it seems resolved. but I builded it on my local pc and intalled,therefore the applications version seem 1.1.0 when you send it on market?
thanks

**Comment by FortuneN** [comment]
@tonyhallett 👍

**Comment by tonyhallett** [comment]
@nsentuna Could you update Fine Code Coverage and report back your findings.  Thanks
