### ISSUE TITLE
Color & Color blindness

### ISSUE THREAD

**Issue by ianpowell2017** [FortuneN/FineCodeCoverage#64]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.63

### Description
Support for Colourblindness?

### Steps to recreate
I have changed the colours in Visual Studio Options > Fonts & Colors for the following Display items
- Coverage Not Touched area
- Coverage Partially Touched area
- Coverage Touched area

### Current behaviour
This does not have any effect on the colours used when painting the IDE screen.

### Expected behaviour
It uses the colours chosen to paint the IDE screen.

### Side Notes
I hope you can solve this.

**Comment by tonyhallett** [comment]
@ianpowell2017 I am currently rewriting the report display and will be including colour information gained from Visual Studio.

**Comment by FortuneN** [comment]
@tonyhallett  👍

**Comment by DleanJeans** [comment]
Can you make the blue text buttons a bit lighter in Dark theme while you're at it? The contrast is not really great.

**Comment by pawchen** [comment]
+1 on lighter blue text buttons on the report. Additionally maybe add a little bit gray to the white text? Currently it's too shine.

**Comment by tonyhallett** [comment]
@DleanJeans @pawchen 

Latest version now incorporates visual studio themes.
