### ISSUE TITLE
Feature request - Dark theme support

### ISSUE THREAD

**Issue by maples3** [FortuneN/FineCodeCoverage#7]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.0.78

### Description
Extension background doesn't support Visual Studio's dark theme

### Steps to recreate
1. Configure Visual Studio to use the dark theme
2. Install Fine Code
3. Run tests to bring up the Fine Code Coverage Window

### Current behavior
The styling of the window is black-text-on-white-background
![Screenshot 2020-10-07 133455](https://user-images.githubusercontent.com/15505712/95366947-21386400-08a2-11eb-9d35-3ee77da32215.png)

### Expected behavior
The window should have a dark background with light text (when the user selects a dark theme)

**Comment by FortuneN** [comment]
Check latest version

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
