### ISSUE TITLE
Coverage result drops downs after updating to 1.1.78

### ISSUE THREAD

**Issue by jvaqueroh** [FortuneN/FineCodeCoverage#72]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.63 updated to 1.1.78

### Description
I had up to 98% of code coverage in some classes with 1.1.63 version of the extension.
After updating the extension to 1.1.78 for those classes I have 22% now!
No code changes made in between, I just closed Visual Studio and re-opened it with the automatic extension update applied.

### Steps to recreate
1. Extension 1.1.63 installed
2. Performed test suite with 98% of code coverage results
3. Auto-updated extension to 1.1.78 when restarting Visual Studio
4. Performed test suite with 22% of code coverage results now

### Current behavior
Code coverage result with new version 1.1.78 is wrong

### Expected behavior
Code coverage result should be the same I had before updating the extension from 1.1.63 to 1.1.78

**Comment by Yaevh** [comment]
probably related to #30

**Comment by tonyhallett** [comment]
@jvaqueroh Please try https://ci.appveyor.com/api/buildjobs/oixulkkqlbpjwr58/artifacts/FineCodeCoverage.vsix

**Comment by tonyhallett** [comment]
@jvaqueroh 
Was the coverage being performed by coverlet ?

If so the latest [vsix](https://ci.appveyor.com/api/buildjobs/v6lf9o06q8sjy21d/artifacts/FineCodeCoverage.vsix) can provide coverage with the coverlet data collector.  This is opt in as not all project versions are supported, but for those that are, the results should be consistent and not suffer from issues as reported in #30 and #92.

If you would like to see if your issue has now been resolved please see [ReadMe new coverlet set up](https://github.com/tonyhallett/FineCodeCoverage/blob/6789dfaaaea03ac9fbec7031f3c6f76d2ed3b803/README.md#coverlet-specific)

**Comment by tonyhallett** [comment]
@jvaqueroh The extension has been published to the marketplace with the latest functionality.
