### ISSUE TITLE
The variable $(MSBuildThisFileDirectory) is not expanded

### ISSUE THREAD

**Issue by codingdave** [FortuneN/FineCodeCoverage#73]
### Installed product versions
- Visual Studio 2019 16.8.4
- This extension: 1.1.78

### Description
Fine Code Coverage : Error
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Projects\Foo\UnitTests\$(MSBuildThisFileDirectory)..\Bar\Bar.csproj'.

### Steps to recreate
1. Have a unit and a unit test that tests the unit
2. Use the SDK style project (<Project Sdk="Microsoft.NET.Sdk">)
3. Reference a project in your solution like this:
`  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\Bar\Bar.csproj" />
  </ItemGroup>`

### Current behavior
The variable $(MSBuildThisFileDirectory) is not expanded and such the Directory.Exists check fails

### Expected behavior
Expand the $(MSBuildThisFileDirectory) variable like msbuild does it.

### Side Notes
> Fine Code Coverage : ================================== START ==================================
> 
> Fine Code Coverage : Error
> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Projects\Foo\UnitTests\$(MSBuildThisFileDirectory)..\Bar\Bar.csproj'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
>    at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
>    at System.IO.File.ReadAllText(String path)
>    at FineCodeCoverage.Engine.FCCEngine.GetReferencedProjects(CoverageProject project) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 494
>    at FineCodeCoverage.Engine.FCCEngine.<>c.<ReloadCoverage>b__31_0(CoverageProject project) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 412
>    at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
>    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at FineCodeCoverage.Engine.FCCEngine.ReloadCoverage(IEnumerable`1 projects, Boolean darkMode) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 392
>    at FineCodeCoverage.Impl.TestContainerDiscoverer.<>c__DisplayClass22_0.<OperationState_StateChanged>b__0() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscovery\TestContainerDiscoverer.cs:line 173
> 
> Fine Code Coverage : ================================== ERROR ==================================

**Comment by tonyhallett** [comment]
@codingdave 
Hi David, the proposed solution unfortunately did not work as anticipated.  It is still present but under certain circumstances cannot be used and the old code is used as a fallback.  This may cause issues if you still have $(MSBuildThisFileDirectory).  I will provide an alternative solution in the next couple of days.

**Comment by codingdave** [comment]
Thank you for the update @tonyhallett.

**Comment by tonyhallett** [comment]
@codingdave 
I have added a fix.  It is not on the market place yet but you can download from here if necessary https://www.vsixgallery.com/extension/fcc-f339fe606-9d51-4fca-895c-d50375137b62

**Comment by codingdave** [comment]
@tonyhallett I have tried the link above and it seems i get to another followup error:

    Fine Code Coverage : Coverlet Run (UnitTests)
    $MYPATH\UnitTests\bin\x64\Debug\net5.0\fine-code-coverage\build-output>"" "$MYPATH\UnitTests\bin\x64\Debug\net5.0\fine-code-coverage\build-output\UnitTests.dll" --format "cobertura" --exclude-by-file "**/Migrations/*" --exclude-by-attribute "GeneratedCode" --include-test-assembly --target "dotnet" --threshold-type line --threshold-stat total --threshold 0 --output "$MYPATH\UnitTests\bin\x64\Debug\net5.0\fine-code-coverage\coverage-tool-output\project.coverage.xml" --targetargs "test  ""$MYPATH\UnitTests\bin\x64\Debug\net5.0\fine-code-coverage\build-output\UnitTests.dll"" --nologo --blame  --results-directory ""$MYPATH\UnitTests\bin\x64\Debug\net5.0\fine-code-coverage\coverage-tool-output"" --diag ""$MYPATH\UnitTests\bin\x64\Debug\net5.0\fine-code-coverage\coverage-tool-output/diagnostics.log""  "  1>"$MYPATH\UnitTests\bin\x64\Debug\net5.0\fine-code-coverage\build-output\d4e7754f.bat.output" 

    '""' is not recognized as an internal or external command,
    operable program or batch file.
`

**Comment by tonyhallett** [comment]
This error has surfaced a few times.
I will have a look at that tomorrow.  I will keep you informed.

**Comment by tonyhallett** [comment]
@codingdave 
I think that the initialization process did not work and that coverlet was not installed.  I have changed the code so that initialization is logged.

Please can you follow these steps so I can investigate further.
a) Delete the FineCodeCoverage app data folder ( for me it is C:\Users\tonyh\AppData\Local\FineCodeCoverage )
b) Install this version of [fine code coverage ](https://ci.appveyor.com/api/buildjobs/y2uqs10127x0ginv/artifacts/FineCodeCoverage.vsix)
c) Open vs and check the output window pane - FCC.  You should see Initializing / install info / Initialized if successful or an error message.
![image](https://user-images.githubusercontent.com/11292998/107851715-d60c0000-6e03-11eb-8e7d-ca0ce43c42c9.png)
d) If no error message run a test and should work.  ( If there is an error you could run a test and FCC should repeat the initialization error )

**Comment by tonyhallett** [comment]
Please use [this version](https://ci.appveyor.com/api/buildjobs/j47e6nqtstrjxaqv/artifacts/FineCodeCoverage.vsix) instead of the one above

**Comment by codingdave** [comment]
Hi @tonyhallett,

the initialization and the code coverage detection is working now. 

    Fine Code Coverage : Initializing
    
    Fine Code Coverage : ReportGenerator Install
    Build started 14.02.2021 08:04:16.
         1>Project "C:\Users\david\AppData\Local\Temp\hx1wwy5e.jl0\restore.csproj" on node 1 (Restore target(s)).
         1>_GetAllRestoreProjectPathItems:
             Determining projects to restore...
           Restore:
             Restoring packages for C:\Users\david\AppData\Local\Temp\hx1wwy5e.jl0\restore.csproj...
               GET https://ci.appveyor.com/nuget/benchmarkdotnet/FindPackagesById()?id='dotnet-reportgenerator-globaltool'&semVerLevel=2.0.0
               GET https://api.nuget.org/v3-flatcontainer/dotnet-reportgenerator-globaltool/index.json
               OK https://api.nuget.org/v3-flatcontainer/dotnet-reportgenerator-globaltool/index.json 180ms
               GET https://api.nuget.org/v3-flatcontainer/dotnet-reportgenerator-globaltool/4.7.1/dotnet-reportgenerator-globaltool.4.7.1.nupkg
               OK https://api.nuget.org/v3-flatcontainer/dotnet-reportgenerator-globaltool/4.7.1/dotnet-reportgenerator-globaltool.4.7.1.nupkg 41ms
             Installing dotnet-reportgenerator-globaltool 4.7.1.
               OK https://ci.appveyor.com/nuget/benchmarkdotnet/FindPackagesById()?id='dotnet-reportgenerator-globaltool'&semVerLevel=2.0.0 1331ms
             Committing restore...
             Generating MSBuild file C:\Users\david\AppData\Local\FineCodeCoverage\reportGenerator\.store\.stage\qxjsuarn.2wl\restore.csproj.nuget.g.props.
             Writing assets file to disk. Path: C:\Users\david\AppData\Local\FineCodeCoverage\reportGenerator\.store\.stage\qxjsuarn.2wl\project.assets.json
             Restored C:\Users\david\AppData\Local\Temp\hx1wwy5e.jl0\restore.csproj (in 2,24 sec).
             
             NuGet Config files used:
                 C:\Users\david\AppData\Roaming\NuGet\NuGet.Config
                 C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
             
             Feeds used:
                 https://api.nuget.org/v3/index.json
                 https://ci.appveyor.com/nuget/benchmarkdotnet
                 C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
                 C:\Program Files\dotnet\sdk\NuGetFallbackFolder
             
             Installed:
                 1 package(s) to C:\Users\david\AppData\Local\Temp\hx1wwy5e.jl0\restore.csproj
         1>Done Building Project "C:\Users\david\AppData\Local\Temp\hx1wwy5e.jl0\restore.csproj" (Restore target(s)).
    
    Build succeeded.
        0 Warning(s)
        0 Error(s)
    
    Time Elapsed 00:00:02.93
    You can invoke the tool using the following command: reportgenerator
    Tool 'dotnet-reportgenerator-globaltool' (version '4.7.1') was successfully installed.
    
    Fine Code Coverage : MsTestPlatform Get Info Not Installed
    
    Fine Code Coverage : MsTestPlatform Install
    Installed version 16.7.1
    
    Fine Code Coverage : OpenCover Get Info Not Installed
    
    Fine Code Coverage : OpenCover Install
    Installed version 4.7.922
    
    Fine Code Coverage : Coverlet Install
    Build started 14.02.2021 08:04:32.
         1>Project "C:\Users\david\AppData\Local\Temp\1jfv43bf.gw5\restore.csproj" on node 1 (Restore target(s)).
         1>_GetAllRestoreProjectPathItems:
             Determining projects to restore...
           Restore:
             Restoring packages for C:\Users\david\AppData\Local\Temp\1jfv43bf.gw5\restore.csproj...
               GET https://api.nuget.org/v3-flatcontainer/coverlet.console/index.json
               GET https://ci.appveyor.com/nuget/benchmarkdotnet/FindPackagesById()?id='coverlet.console'&semVerLevel=2.0.0
               OK https://api.nuget.org/v3-flatcontainer/coverlet.console/index.json 774ms
               GET https://api.nuget.org/v3-flatcontainer/coverlet.console/1.7.2/coverlet.console.1.7.2.nupkg
               OK https://ci.appveyor.com/nuget/benchmarkdotnet/FindPackagesById()?id='coverlet.console'&semVerLevel=2.0.0 787ms
               OK https://api.nuget.org/v3-flatcontainer/coverlet.console/1.7.2/coverlet.console.1.7.2.nupkg 461ms
             Installing coverlet.console 1.7.2.
             Committing restore...
             Generating MSBuild file C:\Users\david\AppData\Local\FineCodeCoverage\coverlet\.store\.stage\jke3v1xu.duv\restore.csproj.nuget.g.props.
             Writing assets file to disk. Path: C:\Users\david\AppData\Local\FineCodeCoverage\coverlet\.store\.stage\jke3v1xu.duv\project.assets.json
             Restored C:\Users\david\AppData\Local\Temp\1jfv43bf.gw5\restore.csproj (in 2,39 sec).
             
             NuGet Config files used:
                 C:\Users\david\AppData\Roaming\NuGet\NuGet.Config
                 C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
             
             Feeds used:
                 https://api.nuget.org/v3/index.json
                 https://ci.appveyor.com/nuget/benchmarkdotnet
                 C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
                 C:\Program Files\dotnet\sdk\NuGetFallbackFolder
             
             Installed:
                 1 package(s) to C:\Users\david\AppData\Local\Temp\1jfv43bf.gw5\restore.csproj
         1>Done Building Project "C:\Users\david\AppData\Local\Temp\1jfv43bf.gw5\restore.csproj" (Restore target(s)).
    
    Build succeeded.
        0 Warning(s)
        0 Error(s)
    
    Time Elapsed 00:00:03.06
    You can invoke the tool using the following command: coverlet
    Tool 'coverlet.console' (version '1.7.2') was successfully installed.
    
    Fine Code Coverage : Initialized

Thank you

**Comment by codingdave** [comment]
I am not sure how stable it is and why the execution failed on the second run. I only added some --exclude-by-file items. On the next run (rebuild, test) it worked again.

    Calculating coverage result...
    Unable to read beyond the end of the stream.
       at FineCodeCoverage.Engine.Coverlet.CoverletUtil.<RunCoverletAsync>d__14.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Coverlet\CoverletUtil.cs:line 243
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at FineCodeCoverage.Engine.Model.CoverageProject.<StepAsync>d__62.MoveNext() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProject.cs:line 343
    
    Fine Code Coverage : ================================== DONE ==================================

**Comment by tonyhallett** [comment]
@codingdave 
This is a known issue with running coverlet the way that FCC currently does https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test.
I will be implementing the other method of running coverlet over the next couple of days.

I think that the current code needs to change so that the final message is Fine Code Coverage : ================================== ERROR ==================================

@FortuneN 
At the moment the CoverageProject.StepAsync handles the exception and reports it but allows the continuation of other test projects.  Should we change to report error if all test projects fail ?

**Comment by FortuneN** [comment]
> Should we change to report error if all test projects fail ?

The choice i made was to allow other test projects that can succeed to proceed when one blows up.
In the case there is an issue either with the solution or the extension, we don't completely block everything.
At least if the error is reported in the log, it is known why 'some' of the coverage is missing.

I'm open to different approach.

**Comment by tonyhallett** [comment]
@codingdave 

Please try [this vix](https://ci.appveyor.com/api/buildjobs/5uiywd05yx2xjd79/artifacts/FineCodeCoverage.vsix) 
[Readme](https://github.com/FortuneN/FineCodeCoverage/blob/f3cf3022ddde43aca974e2617128a5915b9ea270/README.md)

**Comment by codingdave** [comment]
Hi @tonyhallett 

I am not testing much these days but a quick check showed its working fine. Thanks.
