### ISSUE TITLE
Backspace and delete in filter textbox are broken

### ISSUE THREAD

**Issue by jbfraser1** [FortuneN/FineCodeCoverage#74]
### Installed product versions
- Visual Studio: 2019 Prof Preview (16.9.0 preview 3.0)
- This extension: 1.1.78

### Description
Filter textbox backspace doesn't work

### Steps to recreate
1. Run tests
2. Make sure cursor is in a code editing window in the midst of text.
2. In docked "Fine Code Coverage" pane, on "Coverage" tab, click in text box immediately after "Filter: " to place cursor there.
3. Type some text: "MyFilez"
4. [realize you don't use leet spelling for MyFilez. It's really MyFiles]
5. Press Backspace.
6. Watch as Filter text doesn't disappear, but text in main editor does.

### Current behavior
Not letting me delete a few characters in a text box and deleting text elsewhere as a surprise.

### Expected behavior
Only delete the text in the filter textbox.

### Side Notes
Let me know if you have problems with repro, I can try to figure out if there's anything weird I've got setup. Normal USB keyboard, US-English layout, so I'm not sure where to start...

P.S. Extension looks and works well for the most part. Thank you!!!

**Comment by tonyhallett** [comment]
@jbfraser1 Yes that is a surprise ! I am working on a new report view and will ensure that key strokes don't escape from the html.
( Enter and Tab also find their way out )

**Comment by tonyhallett** [comment]
@FortuneN 
This occurs for even the simplest of html, a single input and no js !

**Comment by tonyhallett** [comment]
@FortuneN 
Unfortunately overriding PreProcessMessage ( on OutputToolWindow ) did not help.  The code does get called but returning true does not have the desired effect.
```
protected override bool PreProcessMessage(ref Message m)
        {
			Keys keyData = ((Keys)((int)((long)m.WParam))) | Control.ModifierKeys;
			if(keyData == Keys.Back)
            {
				return true;
            }
			return false;
        }
```

**Comment by tonyhallett** [comment]
@jbfraser1 
The behaviour does not occur when floating or docked a a tabbed document.
Not a solution but I will look at further

**Comment by tonyhallett** [comment]
@jbfraser1 I have a solution that will be in the next release.  Thanks for reporting this issue

**Comment by tonyhallett** [comment]
Fixed by https://github.com/FortuneN/FineCodeCoverage/commit/cfc124164f49e0fbcbabf61842981677b40cb6bc
