### ISSUE TITLE
Fine Code coverage error : is not recognized as an internal or external command

### ISSUE THREAD

**Issue by fluch33** [FortuneN/FineCodeCoverage#76]
### Installed product versions
- Visual Studio: 2019 Professional 16.8.4
- Fine Code Coverage : 1.1.78

### Description
Hello,

I have already seen this issue in other issue but I still have this problem with recent version.
I installed extension Fine Code coverage. 

Running Test Explorer works fine but when I wait impatiently the results of my code coverage, I'm facing this issue in my output window. And, of course, I have nothing in my Fine Code Coverage Tab
Am I missing something?

### Steps to recreate
1. Lauch the test explorer

### Current behavior
Nothing appear in the fine code coverage tab.
And, in the output window, I have the error :

========== Build: 0 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (XUnitTestProject1)

Fine Code Coverage : Coverlet Run (XUnitTestProject1) Arguments 
"C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\XUnitTestProject1.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--include-test-assembly
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
--output "C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\project.coverage.xml"
--targetargs "test  ""C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\XUnitTestProject1.dll"" --nologo --blame  --results-directory ""C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"" --diag ""C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output/diagnostics.log""  "

Fine Code Coverage : Coverlet Run (XUnitTestProject1)
C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output>"" "C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\XUnitTestProject1.dll" --format "cobertura" --exclude-by-file "**/Migrations/*" --exclude-by-attribute "GeneratedCode" --include-test-assembly --target "dotnet" --threshold-type line --threshold-stat total --threshold 0 --output "C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\project.coverage.xml" --targetargs "test  ""C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\XUnitTestProject1.dll"" --nologo --blame  --results-directory ""C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"" --diag ""C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output/diagnostics.log""  "  1>"C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\build-output\46ed1b9b.bat.output" 

'""' is not recognized as an internal or external command,
operable program or batch file.

Fine Code Coverage : ReportGenerator Run Arguments [reporttype:Cobertura] 
"-targetdir:C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output"
"-reports:C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\project.coverage.xml"
"-reporttypes:Cobertura"

Fine Code Coverage : Error
System.Exception: C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output>"" "-targetdir:C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output" "-reports:C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\project.coverage.xml" "-reporttypes:Cobertura"  1>"C:\Users\xxx\source\repos\ConsoleApp1\XUnitTestProject1\bin\Debug\netcoreapp3.1\fine-code-coverage\coverage-tool-output\a195d869.bat.output" 

'""' is not recognized as an internal or external command,
operable program or batch file.
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.<RunReportGenerator>g__run|22_1(String outputReportType, String inputReports, <>c__DisplayClass22_0& ) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 217
   at FineCodeCoverage.Engine.ReportGenerator.ReportGeneratorUtil.RunReportGenerator(IEnumerable`1 coverOutputFiles, Boolean darkMode, String& unifiedHtmlFile, String& unifiedXmlFile, Boolean throwError) in C:\projects\finecodecoverage\FineCodeCoverage\Core\ReportGenerator\ReportGeneratorUtil.cs:line 231
   at FineCodeCoverage.Engine.FCCEngine.ReloadCoverage(IEnumerable`1 projects, Boolean darkMode) in C:\projects\finecodecoverage\FineCodeCoverage\Core\FCCEngine.cs:line 452
   at FineCodeCoverage.Impl.TestContainerDiscoverer.<>c__DisplayClass22_0.<OperationState_StateChanged>b__0() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscovery\TestContainerDiscoverer.cs:line 173

Fine Code Coverage : ================================== ERROR ==================================

I am available for more informations...
Thank you for  your help

**Comment by MikaelFerland** [comment]
It's because report generator is not installed as dotnet global tool.
Maybe it should generate a proper message instead an exception.

1. Close Visual Studio
2. Execute in a command prompt `dotnet tool install -g dotnet-reportgenerator-globaltool`

**Comment by tonyhallett** [comment]
I think that the initialization process did not work and that coverlet was not installed.  I have changed the code so that initialization is logged.

Please can you follow these steps so I can investigate further.
a) Delete the FineCodeCoverage app data folder ( for me it is C:\Users\tonyh\AppData\Local\FineCodeCoverage )
b) Install this version of [fine code coverage ](https://ci.appveyor.com/api/buildjobs/y2uqs10127x0ginv/artifacts/FineCodeCoverage.vsix)
c) Open vs and check the output window pane - FCC.  You should see Initializing / install info / Initialized if successful or an error message.
![image](https://user-images.githubusercontent.com/11292998/107851715-d60c0000-6e03-11eb-8e7d-ca0ce43c42c9.png)
d) If no error message run a test and should work.  ( If there is an error you could run a test and FCC should repeat the initialization error )

**Comment by tonyhallett** [comment]
@MikaelFerland Installing report generator as a global tool would not work as FCC only works with the specific exe version that it downloads to its app data folder.  ( coverlet is missing as well )

I agree that the error message is cryptic and is better surfaced now, sandwiched between Initializing and Initialized

**Comment by fluch33** [comment]
Hi everybody,

Thank you for yours answers.

@tonyhallett : I tried your solution :
- I uninstall FineCode Coverage
- I delete the folder
- Re-install your fine code coverage exe.
- Re-Open VS and got the erro on initialization :
Fine Code Coverage : Failed Initialization
System.InvalidOperationException: Microsoft.Build.Locator.MSBuildLocator.RegisterInstance was called, but MSBuild assemblies were already loaded.
Ensure that RegisterInstance is called before any method that directly references types in the Microsoft.Build namespace has been called.
This dependency arises from when a method is just-in-time compiled, so if it breaks even if the reference to a Microsoft.Build type has not been executed.
For more details, see aka.ms/RegisterMSBuildLocator
Loaded MSBuild assemblies: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   at Microsoft.Build.Locator.MSBuildLocator.RegisterMSBuildPath(String[] msbuildSearchPaths)
   at Microsoft.Build.Locator.MSBuildLocator.RegisterInstance(VisualStudioInstance instance)
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at FineCodeCoverage.Engine.Model.CoverageProjectFactory.Initialize() in C:\projects\finecodecoverage\FineCodeCoverage\Core\Model\CoverageProjectFactory.cs:line 41
   at FineCodeCoverage.Impl.Initializer.Initialize() in C:\projects\finecodecoverage\FineCodeCoverage\Impl\TestContainerDiscovery\Initializer.cs:line 40

- I ran a test an it seems that the initialization run infinitly... (Of course I got nothing in my Fine code coverage Tab ^^).

![image](https://user-images.githubusercontent.com/64831887/107853749-052c6c80-6e18-11eb-9e5e-bcb0eee22aab.png)

**Comment by tonyhallett** [comment]
Ok thanks for that.  Will resolve

**Comment by tonyhallett** [comment]
@fluch33 Please try https://ci.appveyor.com/api/buildjobs/j47e6nqtstrjxaqv/artifacts/FineCodeCoverage.vsix I have correct the msbuild locator code.

**Comment by FortuneN** [comment]
1.1.110. Released!
