### ISSUE TITLE
use the include/exclude settings within *.runsettings file 

### ISSUE THREAD

**Issue by tonyhallett** [FortuneN/FineCodeCoverage#77]
as per https://github.com/FortuneN/FineCodeCoverage/issues/67#issuecomment-772942219

@wdspider This has been mentioned in https://github.com/FortuneN/FineCodeCoverage/issues/30#issuecomment-765458148

What do you think the behaviour should be when there are globally defined include / exclude filters ?

**Comment by wdspider** [comment]
Personally, I'm not sure why I would use the globally defined include / exclude filters if the include/exclude (including the SkipAutoProps and IncludeTestAssemblies) were being read from the runsettings file.

That said, as I see it there would be 4 different behaviors that are possible:

1. If global settings defined, use them and ignore runsettings
2. If runsettings defined, use them and ignore global settings
3. If both are defined, merge together where global overrides runsettings
4. If both are defined, merge together where runsettings overrides global

I would say 2 or 4 would be the better options.  If I'm working on a 20 person team, it would be a bit annoying to ensure all 20 ppl have the same global settings; whereas, the runsettings file can be checked into git.  If I'm using multiple devices to work on the project, it would be a bit annoying to ensure all of my  devices have the same global settings; whereas, the runsettings file can be checked into git.

Finally, in the ideal I would want to be able to create the same report locally as on the build server.  This would be significantly easier to do via runsettings than global settings.

**Comment by tonyhallett** [comment]
Please try [this vix](https://ci.appveyor.com/api/buildjobs/5uiywd05yx2xjd79/artifacts/FineCodeCoverage.vsix) 
[Readme](https://github.com/FortuneN/FineCodeCoverage/blob/f3cf3022ddde43aca974e2617128a5915b9ea270/README.md)

**Comment by wdspider** [comment]
A quick pass through toggling the IncludeTestAssembly and SkipAutoProps flags in the runsettings file seems to work like I would expect.
