### ISSUE TITLE
Partial coverage is shown even if the code is fully covered

### ISSUE THREAD

**Issue by dozer75** [FortuneN/FineCodeCoverage#8]
### Installed product versions
- Visual Studio: 2019 Community (Version 16.7.4)
- This extension: 1.0.78

### Description
In some circumstances the code coverage reports entries as partial covered, even if they are full covered. The ReportGenerator tool does this coverage correctly, so it must be an issue with the presentation of the code coverage.

### Steps to recreate
1. Create a unit test project and apply this code:

```
        [Fact]
        public void TestIfChecksPartialCoverageThrowsException()
        {
            Assert.Throws<ArgumentNullException>(() => IfChecksPartialCoverage(null));
        }

        [Fact]
        public void TestIfChecksPartialCoverage()
        {
            Assert.Equal("blah", IfChecksPartialCoverage("blah"));
        }

        private static string IfChecksPartialCoverage(string something)
        {
            if (something is null)
            {
                throw new ArgumentNullException(nameof(something));
            }

            return something;
        }
```
2. Run the unit tests
3. Look at the code coverage markings.

### Current behavior
The line `if (something is null)` is marked as partial covered.

### Expected behavior
All lines should be marked as fully covered.

**Comment by FortuneN** [comment]
You are right

> \<line number="31" hits="2" branch="true" condition-coverage="100% (2/2)" /\>

Fix coming soon

**Comment by FortuneN** [comment]
Check latest version

**Comment by dozer75** [comment]
Now it works :)

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
