### ISSUE TITLE
FCC is not running

### ISSUE THREAD

**Issue by nsentuna** [FortuneN/FineCodeCoverage#88]
My FCC is not running anymore.

![Ekran görüntüsü 2021-02-11 161232](https://user-images.githubusercontent.com/21196564/107640961-0cbb0c80-6c84-11eb-8577-ab06591129c4.jpg)
and/or reviewing
  https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

**Comment by tonyhallett** [comment]
The current version on the market place is working.

![image](https://user-images.githubusercontent.com/11292998/107681850-827ca380-6c97-11eb-8fad-2105fc07721d.png)

**Comment by paul1956** [comment]
Is this supposed to work with Visual Basic because I am not seeing anything with 16.9 Preview 4 with DotNet Preview 5.0.200-preview.21079.7 I am running 1.1.99.

**Comment by tonyhallett** [comment]
@paul1956 
Yes.  I ran an NUnit Core V5.0 Visual Basic test against a Net Core V5.0 Visual Basic class library and Fine Code Coverage ran and produced coverage as expected.

What is your solution set up ? What tests are you running ? Have you checked the Build output window ?

**Comment by paul1956** [comment]
@tonyhallett I am using XUnit and project is https://github.com/paul1956/CSharpToVB. I am using 16.9 Preview 4 to get VB code generation but there is a new workaround in ReadMe,MD for 16.8.4, you just include 2 VB asset times in your build.

**Comment by tonyhallett** [comment]
@paul1956 Please can you try again with the latest version of FCC.  The output window FCC pane will give information on the required initialization and of coverage progress.

I would clone your project but I assume that it will not build without the preview version of visual studio

**Comment by paul1956** [comment]
The latest will build with 16.8 you just need to include the 2 Vb files under Assets in the project. I will also try what you said later today. 500+ tests will not be skipped but that is fine.

**Comment by paul1956** [comment]
@tonyhallett  No errors
```
Build started...
1>------ Build started: Project: HashLibrary, Configuration: Debug Any CPU ------
2>------ Build started: Project: ProgressReportLibrary, Configuration: Debug Any CPU ------
3>------ Build started: Project: csvGenerator, Configuration: Debug Any CPU ------
2>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
3>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
3>csvGenerator -> C:\Users\PaulM\Source\Repos\CSharpToVB\csvGenerator\bin\Debug\netstandard2.0\csvGenerator.dll
2>ProgressReportLibrary -> C:\Users\PaulM\Source\Repos\CSharpToVB\ProgressReportLibrary\bin\Debug\net5.0\ProgressReportLibrary.dll
1>HashLibrary -> C:\Users\PaulM\Source\Repos\CSharpToVB\HashLibrary\bin\Debug\net5.0\HashLibrary.dll
4>------ Build started: Project: CodeConverter, Configuration: Debug Any CPU ------
4>CodeConverter -> C:\Users\PaulM\Source\Repos\CSharpToVB\CodeConverter\bin\Debug\net5.0-windows7.0\VB.CodeConverter.dll
5>------ Build started: Project: CSharpToVB, Configuration: Debug Any CPU ------
5>CSharpToVB -> C:\Users\PaulM\Source\Repos\CSharpToVB\CSharpToVB\bin\Debug\net5.0-windows\CSharpToVBApp.dll
6>------ Build started: Project: CSharpToVB.Tests, Configuration: Debug Any CPU ------
6>CSharpToVB.Tests -> C:\Users\PaulM\Source\Repos\CSharpToVB\CSharpToVB.Tests\bin\Debug\net5.0-windows\CSharpToVB.Tests.dll
========== Build: 6 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

> Build started at 3:58 PM and took 4.619 seconds
```

**Comment by paul1956** [comment]
There is now a separate branch to support 16.8 that does not use SourceGenerators just 2 static files.It will skip 500+ tests will not be skipped but that is fine.

**Comment by tonyhallett** [comment]
@paul1956 you need to supply the log from the FCC pane in the output window.

**Comment by paul1956** [comment]
```
Fine Code Coverage : Initializing

Fine Code Coverage : Initialized

Fine Code Coverage : ================================== START ==================================

Fine Code Coverage : Run Coverage Tool (CSharpToVB.Tests)

Fine Code Coverage : Coverlet Run (CSharpToVB.Tests) Arguments 
"C:\Users\PaulM\Source\Repos\CSharpToVB\CSharpToVB.Tests\bin\Debug\net5.0-windows\fine-code-coverage\build-output\CSharpToVB.Tests.dll"
--format "cobertura"
--exclude-by-file "**/Migrations/*"
--exclude-by-attribute "GeneratedCode"
--include-test-assembly
--target "dotnet"
--threshold-type line
--threshold-stat total
--threshold 0
--output "C:\Users\PaulM\Source\Repos\CSharpToVB\CSharpToVB.Tests\bin\Debug\net5.0-windows\fine-code-coverage\coverage-tool-output\project.coverage.xml"
--targetargs "test  ""C:\Users\PaulM\Source\Repos\CSharpToVB\CSharpToVB.Tests\bin\Debug\net5.0-windows\fine-code-coverage\build-output\CSharpToVB.Tests.dll"" --nologo --blame  --results-directory ""C:\Users\PaulM\Source\Repos\CSharpToVB\CSharpToVB.Tests\bin\Debug\net5.0-windows\fine-code-coverage\coverage-tool-output"" --diag ""C:\Users\PaulM\Source\Repos\CSharpToVB\CSharpToVB.Tests\bin\Debug\net5.0-windows\fine-code-coverage\coverage-tool-output/diagnostics.log""  "

```

**Comment by paul1956** [comment]
[diagnostics.host.21-02-16_02-44-30_29220_6.log](https://github.com/FortuneN/FineCodeCoverage/files/5988004/diagnostics.host.21-02-16_02-44-30_29220_6.log)
[diagnostics.datacollector.21-02-16_02-44-29_97968_4.log](https://github.com/FortuneN/FineCodeCoverage/files/5988016/diagnostics.datacollector.21-02-16_02-44-29_97968_4.log)
[diagnostics.log](https://github.com/FortuneN/FineCodeCoverage/files/5988022/diagnostics.log)
There is also an empty directory named ccaf170e-2a6d-455e-aad6-51ad297b94ef

**Comment by tonyhallett** [comment]
Can you get coverage when run outside of FCC ?

**Comment by paul1956** [comment]
Yes I post the results in ReadMe.MD file when I run from PowerShell.

**Comment by tonyhallett** [comment]
I am away for a couple of days when I am back I will clone your project and have a look.  

How are you generating your coverage ? I see collector and msbuild as possible drivers.

**Comment by paul1956** [comment]
When I run Coverlet I do it from PowerShell (script in project) to get the pretty tables to include in ReadMe.MD,
```
Set MANUAL_TESTS=
dotnet test ./CSharpToVB.Tests.vbproj /p:CollectCoverage=true /p:CoverletOutputFormat=json /p:CoverletOutput=./TestResults/LastRun/Coverage.json /p:Exclude=\"[coverlet.*]*,[*]Coverlet.Core*,[xunit*]*,[Microsoft.DotNet.XUnitExtensions]*,[ProgressReportLibrary]*,[CSharpToVBApp]*,[HashLibrary]*"
```
I also include Coverlet in Coverlet.Colector and Coverlet.MSBuild NuGet packages in Project. My tests run from both Test Explorer and command line. There are 2 groups of tests those that only run on my local machine because then need Roslyn Source access and those that run on GitHub. The reason I want your tool is so I can figure out want tests I need to add to GitHub so I don't need Roslyn source. With Roslyn Source coverage is >90%. Without it it is much lower.

**Comment by tonyhallett** [comment]
If you cannot wait until tomorrow when I can have a look fork the repo and debug in.  The TestContainerDiscoverer is the entry point and coverage should begin when TestExecutionFinished.

**Comment by paul1956** [comment]
Take you time, it is just a better solution then anything I have for VB.

**Comment by tonyhallett** [comment]
@paul1956 
The solution does not build for me
![image](https://user-images.githubusercontent.com/11292998/108537146-2c31e500-72d5-11eb-804d-8e3ff6f8699c.png)

**Comment by paul1956** [comment]
If you are running 16.8 you need to use branch support16.8.

Master requires 16.9 Preview 3 or later as it uses Vb Source Generator

**Comment by tonyhallett** [comment]
sorry you had already mentioned this.  I am running CSharpToVB.Tests as I write this.  FCC has started coverage but Coverlet has yet to return a result after 5 minutes.....

**Comment by tonyhallett** [comment]
It appears that the tests are taking a long time to run on my machine as ConvertDirectory.Tests are not being skipped as I have forked Roslyn in the past ! I am going to delete the folder and try again.

**Comment by tonyhallett** [comment]
With tests skipped FCC completes quickly but with 0% coverage.  This is either a true representation or is due to an issue with the coverlet console driver that FCC currently uses.  I am currently adding code to use data collectors.

**Comment by paul1956** [comment]
You can force ConvertDirectory.Tests to not run by setting EnableRoslynTests to return false they take at least 2 hours to run the rest of the test run in under a minute. If FCC works I will enhance detection to disable it when FCC is running and have them run only under command line. Coverage is over 75% without EnableRoslynTests.

**Comment by paul1956** [comment]
I do have a Trait to skip all the Roslyn Tests when live unit testing, do you have a similar away?
```
<Trait("Category", "SkipWhenLiveUnitTesting")>
```

**Comment by tonyhallett** [comment]
FCC has no knowledge of the tests that you have chosen to run, only that a test project is running tests.  As such, traits will have no effect and the skipping of tests will need to be performed by the test framework.  
I would suggest an environment variable and use a library that facilitates test skipping via attributes.
For instance https://github.com/natemcmaster/xunit-extensions  [nuget](https://www.nuget.org/packages/McMaster.Extensions.Xunit/)
Or mine https://github.com/tonyhallett/XUnit_Conditional_Fact [nuget](https://www.nuget.org/packages/XUnit_Conditional_Fact/).  With mine you would still have a small amount of work as my library provides the skip functionality - you provide the condition ( attribute ) that determines the skip.

I have the data collector code 95% complete ( I just need the vsix to accept the coverlet collector files without complaing ).
Below is the results of FCC with the data collector against your project ( branch Support16.8) which is better than the 0% results with the global tool !

![image](https://user-images.githubusercontent.com/11292998/108630828-c8d3be80-745e-11eb-8355-ba6a7ac4b4b7.png)

Note that this is without your DataCollector configuration ( which will be respected when I release the changes tomorrow )

**Comment by paul1956** [comment]
@tonyhallett I have redone the skipping logic to use attributes and an Environment Variable.

I was using conditionalfact until recently I switched to SkippableFact but could easily switch back.

Where do I specify DataCollector configuration? I don't want to profile HashLibrary and ProgressReportLibrary they are tested in other projects and I just include them in source for simplicity.

I also use the attribute below to ignore stuff that I don't want counted like code for future use or that I working to make obsolete, does your collector respect that or is there another way to do that?
```
<ExcludeFromCodeCoverage>
```

**Comment by tonyhallett** [comment]
> I was using conditionalfact until recently I switched to SkippableFact but could easily switch back.

Whatever works !

> Where do I specify DataCollector configuration? 

You can continue to use runsettings just be sure that when you run your tests that you tell visual studio to use them.
It will be possible to supply without runsettings with FCC global options and project options.
**I will release tomorrow as I have decided to change how these work together.**

> <ExcludeFromCodeCoverage>

Applying this attribute to classes and members will work as expected.

**Comment by paul1956** [comment]
I don't have a runsettings file (that I know of), I don't see anything in the documentation that I need to set except possibility the coverage collector as I am not running Visual Studio Enterprise.

**Comment by tonyhallett** [comment]
You have runsettings in both branches which are not being used.

https://github.com/paul1956/CSharpToVB/blob/master/CSharpToVB.Tests/CoverletArgs.runsettings
https://github.com/paul1956/CSharpToVB/blob/Support16.8/CSharpToVB.Tests/CoverletArgs.runsettings

You have commented out in https://github.com/paul1956/CSharpToVB/blob/adf6029d06b2483a723ed5b29fecbedbf95c046f/CSharpToVB.Tests/CodeCoverage.cmd

( Does the uncommented work ? )

-----------------------

Your options with FCC which will be documented in the readme is to run your tests with runsettings so that FCC can pick them up.
[see here for your options with regards to runsettings](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#specify-a-run-settings-file-in-the-ide) 

Alternatively, FCC will generate from global visual studio options and project options.  It is also possible to have a combination of the two.

Note that FCC does not provide all of the settings available in the runsettings.  It will not set IncludeDirectory, SingleHit, UseSourceLink and SkipAutoProps.

-----------------
Please try [this vix](https://ci.appveyor.com/api/buildjobs/5uiywd05yx2xjd79/artifacts/FineCodeCoverage.vsix) 
[Readme](https://github.com/FortuneN/FineCodeCoverage/blob/f3cf3022ddde43aca974e2617128a5915b9ea270/README.md)

**Comment by paul1956** [comment]
Sorry I guess I either inhered that code or just never understood what it did. The comments in CodeCoverage.cmd are for other options that I don't use now but thought I might in the future. I was looking for a way to figure out what tests cover what lines so I could eliminate most of the Roslyn tests that duplicate each other.

**Comment by tonyhallett** [comment]
I will correct both bugs and get back to you.

**Comment by tonyhallett** [comment]
This [vsix](https://ci.appveyor.com/api/buildjobs/oixulkkqlbpjwr58/artifacts/FineCodeCoverage.vsix) corrects the missing margin glyphs.

**Comment by tonyhallett** [comment]
This [vsix](https://ci.appveyor.com/api/buildjobs/v6lf9o06q8sjy21d/artifacts/FineCodeCoverage.vsix) corrects both issues.

**Comment by paul1956** [comment]
With the latest version (4 hours ago) I get the no coverage
![image](https://user-images.githubusercontent.com/12789369/109200957-10f02b00-7756-11eb-927c-97dbcb828c25.png)

**Comment by tonyhallett** [comment]
Have you added UseDataCollector msbuild property ?
https://github.com/tonyhallett/FineCodeCoverage/blob/6789dfaaaea03ac9fbec7031f3c6f76d2ed3b803/README.md#coverlet-specific

**Comment by paul1956** [comment]
I added UseDataCollector to the VB project files and now I have data. Thanks again.

**Comment by paul1956** [comment]
@tonyhallett It looks like everything is working as expected. Thanks again.

**Comment by tonyhallett** [comment]
@paul1956 No problem. Thanks for bringing to our attention the hotspot bugs.  Good luck with your project
