### ISSUE TITLE
Feature Request: Option to exclude the test assembly 

### ISSUE THREAD

**Issue by JohnCampionJr** [FortuneN/FineCodeCoverage#9]
It seems this adds the --include-test-assembly to the CLI; could that be configurable?

**Comment by FortuneN** [comment]
Check latest version

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
