### ISSUE TITLE
Not showing without a test

### ISSUE THREAD

**Issue by MutatePat** [FortuneN/FineCodeCoverage#98]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 1.1.116

### Description
Files with no unit tests do not show UI

### Steps to recreate
1. Create two classes
2. Create a unit test for one
3. Run the test and generate FCC

### Current behavior
Currently, it does the class with the test, will show the helpers on the left( green for tested, red for untested). This should show even if no test exists. Since we should aim for 100% code coverage.

### Expected behavior
Add a settings option to enable the UI Helpers to always be shown.

**Comment by tonyhallett** [comment]
I follow your steps.  
Upon running a test the class being tested receives green for the method tested and red for untested.  The other class also gets the colouring which is red as there are no tests that target it.

**Comment by tonyhallett** [comment]
I think it is likely that you encountered a bug that has been fixed with this [vsix](https://ci.appveyor.com/api/buildjobs/oixulkkqlbpjwr58/artifacts/FineCodeCoverage.vsix)

Please use this vsix until the new version is published to the marketplace

**Comment by tonyhallett** [comment]
@MutatePat Closing as I believe that this has been resolved.  Will reopen if you are still having issues.
